stages:
- build
- deploy

raastin_build:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
      - main
      - develop
      - release/gold
  script:
    - export IMAGE="registry.hamdocker.ir/raastin/core"
    - 'darkube build --push -t $IMAGE:$CI_COMMIT_SHORT_SHA -t $IMAGE:$CI_COMMIT_REF_SLUG'
  retry:
    max: 2

  stage: build
  tags:
    - hamravesh

deploy_gold:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
    - release/gold
  script:

    # Tochal API Deployments
    - 'darkube deploy --token ${TOCHAL_API_DEPLOY_TOKEN}
      --app-id ${TOCHAL_API_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${TOCHAL_API_CELERY_BEAT_DEPLOY_TOKEN}
      --app-id ${TOCHAL_API_CELERY_BEAT_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${TOCHAL_API_CELERY_WORKERS_DEPLOY_TOKEN}
      --app-id ${TOCHAL_API_CELERY_WORKERS_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'

  stage: deploy
  tags:
    - hamravesh