stages:
- build
- deploy

raastin_build:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
      - main
      - develop
  script:
    - export IMAGE="registry.hamdocker.ir/raastin/core"
    - 'darkube build --push -t $IMAGE:$CI_COMMIT_SHORT_SHA -t $IMAGE:$CI_COMMIT_REF_SLUG'
  stage: build
  tags:
    - hamravesh

deploy_staging:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
    - develop
  script:
    - 'darkube deploy --token ${STAGING_API_DEPLOY_TOKEN}
      --app-id ${STAGING_API_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${STAGING_CELERY_BEAT_DEPLOY_TOKEN}
      --app-id ${STAGING_CELERY_BEAT_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${STAGING_CELERY_WORKERS_DEPLOY_TOKEN}
      --app-id ${STAGING_CELERY_WORKERS_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${STAGING_SOCKET_SYNCHRONIZER_DEPLOY_TOKEN}
      --app-id ${STAGING_SOCKET_SYNCHRONIZER_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
  stage: deploy
  tags:
    - hamravesh

arzplus_deploy_production:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
    - main
  script:
    - 'darkube deploy --token ${ARZPLUS_CELERY_CELERY_TOKEN}
      --app-id ${ARZPLUS_CELERY_CELERY_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${ARZPLUS_API_DEPLOY_TOKEN}
      --app-id ${ARZPLUS_API_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${ARZPLUS_CELERY_BEAT_DEPLOY_TOKEN}
      --app-id ${ARZPLUS_CELERY_BEAT_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${ARZPLUS_CELERY_KYC_TOKEN}
      --app-id ${ARZPLUS_CELERY_KYC_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${ARZPLUS_CELERY_TRANSFER_TOKEN}
      --app-id ${ARZPLUS_CELERY_TRANSFER_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${ARZPLUS_SOCKET_PROVIDER_DEPLOY_TOKEN}
      --app-id ${ARZPLUS_SOCKET_PROVIDER_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${ARZPLUS_NOTIF_MANAGER_DEPLOY_TOKEN}
      --app-id ${ARZPLUS_NOTIF_MANAGER_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${ARZPLUS_CELERY_MARGIN_DEPLOY_TOKEN}
      --app-id ${ARZPLUS_CELERY_MARGIN_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'

  stage: deploy
  tags:
    - hamravesh

raastin_deploy_production:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
    - main
  script:
    - 'darkube deploy --token ${RAASTIN_CELERY_CELERY_TOKEN}
      --app-id ${RAASTIN_CELERY_CELERY_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${RAASTIN_API_DEPLOY_TOKEN}
      --app-id ${RAASTIN_API_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${RAASTIN_CELERY_BEAT_TOKEN}
      --app-id ${RAASTIN_CELERY_BEAT_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${RAASTIN_CELERY_KYC_TOKEN}
      --app-id ${RAASTIN_CELERY_KYC_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${RAASTIN_CELERY_TRANSFER_TOKEN}
      --app-id ${RAASTIN_CELERY_TRANSFER_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${RAASTIN_SOCKET_PROVIDER_DEPLOY_TOKEN}
      --app-id ${RAASTIN_SOCKET_PROVIDER_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${RAASTIN_NOTIF_MANAGER_DEPLOY_TOKEN}
      --app-id ${RAASTIN_NOTIF_MANAGER_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${RAASTIN_CELERY_MARGIN_DEPLOY_TOKEN}
      --app-id ${RAASTIN_CELERY_MARGIN_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'

  stage: deploy
  tags:
    - hamravesh


tgju_deploy_production:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
    - main
  script:
    - 'darkube deploy --token ${TGJU_CELERY_CELERY_TOKEN}
      --app-id ${TGJU_CELERY_CELERY_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${TGJU_API_DEPLOY_TOKEN}
      --app-id ${TGJU_API_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${TGJU_CELERY_BEAT_TOKEN}
      --app-id ${TGJU_CELERY_BEAT_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
#    - 'darkube deploy --token ${TGJU_CELERY_KYC_TOKEN}
#      --app-id ${TGJU_CELERY_KYC_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
#      --job-id "${CI_JOB_ID}"'
#    - 'darkube deploy --token ${TGJU_CELERY_TRANSFER_TOKEN}
#      --app-id ${TGJU_CELERY_TRANSFER_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
#      --job-id "${CI_JOB_ID}"'
    - 'darkube deploy --token ${TGJU_ORDERBOOK_DEPLOY_TOKEN}
      --app-id ${TGJU_ORDERBOOK_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
#    - 'darkube deploy --token ${TGJU_NOTIF_MANAGER_DEPLOY_TOKEN}
#      --app-id ${TGJU_NOTIF_MANAGER_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
#      --job-id "${CI_JOB_ID}"'
#    - 'darkube deploy --token ${TGJU_CELERY_MARGIN_DEPLOY_TOKEN}
#      --app-id ${TGJU_CELERY_MARGIN_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
#      --job-id "${CI_JOB_ID}"'

  stage: deploy
  tags:
    - hamravesh
