# Generated by Django 4.0 on 2022-07-27 08:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0114_merge_0112_alter_trx_scope_0113_merge_20220726_1729'),
        ('accounts', '0070_alter_externalnotification_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apr', models.DecimalField(blank=True, decimal_places=3, max_digits=6)),
                ('enable', models.BooleanField(default=False)),
                ('max_amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset')),
            ],
        ),
        migrations.CreateModel(
            name='StakeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('process', 'process'), ('pending', 'pending'), (' done', ' done'), ('cancel_process', 'cancel_process'), ('cancel_pending', 'cancel_pending'), ('cancel_complete', 'cancel_complete')], default='process', max_length=16)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('stake_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stake.stakeoption')),
            ],
        ),
        migrations.CreateModel(
            name='StakeRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('revenue', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('stake_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stake.stakerequest')),
            ],
            options={
                'unique_together': {('created', 'stake_request')},
            },
        ),
    ]
