# Generated by Django 4.0 on 2022-08-02 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0002_stakerequest_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stakeoption',
            old_name='max_amount',
            new_name='total_cap',
        ),
        migrations.RenameField(
            model_name='stakeoption',
            old_name='min_amount',
            new_name='user_max_amount',
        ),
        migrations.AddField(
            model_name='stakeoption',
            name='user_min_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
