# Generated by Django 4.0 on 2022-08-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0003_rename_max_amount_stakeoption_total_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeoption',
            name='landing',
            field=models.BooleanField(default=False),
        ),
    ]
