# Generated by Django 4.0 on 2022-08-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0004_stakeoption_landing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakerequest',
            name='status',
            field=models.CharField(choices=[('process', 'process'), ('pending', 'pending'), ('done', 'done'), ('cancel_process', 'cancel_process'), ('cancel_pending', 'cancel_pending'), ('cancel_complete', 'cancel_complete')], default='process', max_length=16),
        ),
    ]
