# Generated by Django 4.0 on 2022-09-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0006_stakeoption_fee'),
        ('stake', '0006_stakeoption_precision'),
    ]

    operations = [
    ]
