# Generated by Django 4.0 on 2022-09-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0007_merge_0006_stakeoption_fee_0006_stakeoption_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakerevenue',
            name='wallet_source',
            field=models.CharField(choices=[('spot', 'spot'), ('stake', 'stake')], default='spot', max_length=8),
            preserve_default=False,
        ),
    ]
