# Generated by Django 4.1.3 on 2022-12-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0008_stakerevenue_wallet_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakerequest',
            name='status',
            field=models.CharField(choices=[('process', 'process'), ('pending', 'pending'), ('done', 'done'), ('cancel_process', 'cancel_process'), ('cancel_pending', 'cancel_pending'), ('cancel_complete', 'cancel_complete'), ('finished', 'finished')], default='process', max_length=16),
        ),
    ]
