# Generated by Django 4.0.4 on 2023-04-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0010_alter_stakerequest_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakerequest',
            name='cancel_pending_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakerequest',
            name='cancel_request_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakerequest',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakerequest',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
