# Generated by Django 4.1.3 on 2023-07-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stake", "0011_stakerequest_cancel_pending_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stakerequest",
            name="is_bot",
            field=models.BooleanField(default=False),
        ),
    ]
