# Generated by Django 4.1.3 on 2023-07-08 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0135_delete_externalnotification'),
        ('stake', '0011_stakerequest_cancel_pending_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakerequest',
            name='login_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.loginactivity'),
        ),
    ]
