# Generated by Django 4.1.3 on 2023-08-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0013_merge_20230716_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakerequest',
            name='is_bot',
        ),
        migrations.AddField(
            model_name='stakeoption',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
