# Generated by Django 4.1.3 on 2023-10-10 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0014_remove_stakerequest_is_bot_stakeoption_is_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeoption',
            name='fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
