# Generated by Django 4.1.3 on 2023-12-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0015_alter_stakeoption_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakerevenue',
            name='created',
            field=models.DateField(db_index=True),
        ),
    ]
