# Generated by Django 4.1.3 on 2024-05-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0017_remove_stakeoption_is_bot_stakeoption_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeoption',
            name='type',
            field=models.CharField(choices=[('defi', 'defi'), ('pool', 'pool'), ('bot', 'bot')], default='defi', max_length=6),
        ),
    ]
