# Generated by Django 4.1.3 on 2024-08-04 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0018_alter_stakeoption_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stakerequest',
            options={'permissions': [('list_stakerequest', 'Can list stake request')]},
        ),
    ]
