# Generated by Django 4.1.3 on 2023-04-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(db_index=True, unique=True)),
                ('active_30', models.PositiveSmallIntegerField()),
                ('churn_30', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Daily analytics',
                'verbose_name_plural': 'Daily analytics',
            },
        ),
    ]
