# Generated by Django 4.1.3 on 2023-04-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_dailyanalytics_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyanalytics',
            name='new_30',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
