# Generated by Django 4.1.3 on 2023-04-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_dailyanalytics_new_30'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(db_index=True)),
                ('period', models.SmallIntegerField(choices=[(1, 'daily'), (7, 'weekly'), (30, 'monthly')])),
                ('active', models.PositiveSmallIntegerField()),
                ('new', models.PositiveSmallIntegerField()),
                ('churn', models.PositiveSmallIntegerField()),
            ],
            options={
                'unique_together': {('created', 'period')},
            },
        ),
        migrations.DeleteModel(
            name='DailyAnalytics',
        ),
    ]
