# Generated by Django 4.1.3 on 2023-06-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_activetrader_delete_dailyanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('last_id', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('trade', 'trade'), ('otc_trade', 'otc_trade'), ('transfer', 'transfer'), ('fiat_withdraw', 'fiat_withdraw'), ('payment', 'payment'), ('user', 'user'), ('login', 'login'), ('traffic_source', 'traffic_source'), ('prize', 'prize'), ('staking', 'staking')], max_length=20, unique=True)),
            ],
        ),
    ]
