# Generated by Django 4.1.3 on 2023-07-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_eventtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtracker',
            name='type',
            field=models.CharField(choices=[('trade', 'trade'), ('otc_trade', 'otc_trade'), ('transfer', 'transfer'), ('fiat_withdraw', 'fiat_withdraw'), ('payment', 'payment'), ('user', 'user'), ('login', 'login'), ('traffic_source', 'traffic_source'), ('prize', 'prize'), ('staking', 'staking'), ('wallet', 'wallet'), ('transaction', 'transaction')], max_length=20, unique=True),
        ),
    ]
