# Generated by Django 4.1.3 on 2024-09-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_reportpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpermission',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
