# Generated by Django 4.1.3 on 2024-09-24 07:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_reportpermission_enable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('source', models.CharField(choices=[('tgju', 'tgju'), ('nobitex', 'nobitex'), ('mexc', 'mexc')], max_length=64)),
                ('exchange_id', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'unique_together': {('name', 'source')},
            },
        ),
        migrations.CreateModel(
            name='SymbolPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('close', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('high', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('low', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.symbol')),
            ],
            options={
                'unique_together': {('symbol', 'created')},
            },
        ),
    ]
