# Generated by Django 4.1.3 on 2024-09-29 15:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


def populate_group_id(apps, schema_editor):
    ReportPermission = apps.get_model('analytics', 'ReportPermission')

    for p in ReportPermission.objects.all():
        p.group_id = uuid.uuid4()
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0008_reportpermission_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpermission',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='reportpermission',
            name='referral_percent_revenue',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='reportpermission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='reportpermission',
            name='utm_medium',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='reportpermission',
            name='utm_source',
            field=models.CharField(max_length=256),
        ),
        migrations.RunPython(
            code=populate_group_id,
            reverse_code=migrations.RunPython.noop
        )
    ]
