# Generated by Django 4.1.3 on 2025-01-06 06:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_reportpermission_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpermission',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
