# Generated by Django 4.1.3 on 2024-09-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_symbol_symbolprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbol',
            old_name='exchange_id',
            new_name='market_id',
        ),
        migrations.AddField(
            model_name='symbol',
            name='account_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='symbol',
            name='auth',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='source',
            field=models.CharField(choices=[('tgju', 'tgju'), ('nobitex', 'nobitex'), ('mexc', 'mexc'), ('exness', 'exness'), ('binance', 'binance')], max_length=64),
        ),
    ]
