# Generated by Django 4.1.3 on 2024-09-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_rename_exchange_id_symbol_market_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='auth',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
