# Generated by Django 4.1.3 on 2025-01-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_alter_eventtracker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtracker',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
