# Generated by Django 4.1.3 on 2024-09-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_alter_symbol_auth'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='symbolprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='symbolprice',
            name='frame',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterUniqueTogether(
            name='symbolprice',
            unique_together={('symbol', 'created', 'frame')},
        ),
    ]
