# Generated by Django 4.1.3 on 2024-10-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_reportpermission_group_id_and_more'),
        ('analytics', '0012_alter_symbolprice_unique_together_symbolprice_frame_and_more'),
    ]

    operations = [
    ]
