# Generated by Django 4.1.3 on 2024-10-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_merge_20241001_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='auto_collect',
            field=models.BooleanField(default=True),
        ),
    ]
