# Generated by Django 4.1.3 on 2025-01-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_alter_reportpermission_group_id'),
        ('analytics', '0014_symbol_auto_collect'),
    ]

    operations = [
    ]
