# Generated by Django 4.1.3 on 2025-02-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_eventtracker_enable'),
        ('analytics', '0015_merge_20250106_1540'),
    ]

    operations = [
    ]
