# Generated by Django 4.0 on 2022-01-01 14:18

from django.db import migrations, models
import django.db.models.deletion
import ledger.utils.random
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('name_fa', models.CharField(max_length=64)),
                ('image', models.FileField(upload_to='asset-logo/')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('release_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('freed', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=8, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('name_fa', models.CharField(max_length=64)),
                ('can_withdraw', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=18, max_digits=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Trx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_trx', to='ledger.wallet')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_trx', to='ledger.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='OTCRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.UUIDField(db_index=True, default=ledger.utils.random.secure_uuid4)),
                ('price', models.DecimalField(decimal_places=18, max_digits=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('dest_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_otc', to='ledger.asset')),
                ('src_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_otc', to='ledger.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=8)),
                ('status', models.CharField(choices=[('pend', 'pend'), ('cancel', 'cancel'), ('done', 'done')], db_index=True, default='pend', max_length=8)),
                ('lock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ledger.balancelock')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='balancelock',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.wallet'),
        ),
        migrations.CreateModel(
            name='NetworkWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('address_tag', models.CharField(default='', max_length=32)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.network')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='networks', to='ledger.wallet')),
            ],
            options={
                'unique_together': {('network', 'wallet')},
            },
        ),
        migrations.CreateModel(
            name='NetworkAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.DecimalField(decimal_places=18, max_digits=25)),
                ('min_transfer', models.DecimalField(decimal_places=18, max_digits=25)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.asset')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.network')),
            ],
            options={
                'unique_together': {('asset', 'network')},
            },
        ),
    ]
