# Generated by Django 4.0 on 2022-01-02 07:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otcrequest',
            name='dest_asset',
        ),
        migrations.RemoveField(
            model_name='otcrequest',
            name='src_asset',
        ),
        migrations.AddField(
            model_name='asset',
            name='max_trade_quantity',
            field=models.DecimalField(decimal_places=5, default=1000000000.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='asset',
            name='min_trade_quantity',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='asset',
            name='trade_quantity_step',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=15),
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='coin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ledger.asset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='side',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default='', max_length=8),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OTCTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done')], default='pending', max_length=8)),
                ('otc_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ledger.otcrequest')),
            ],
        ),
    ]
