# Generated by Django 4.0 on 2022-01-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_remove_otcrequest_dest_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otctrade',
            name='provider_order_id',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
