# Generated by Django 4.0 on 2022-01-02 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_otctrade_provider_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
    ]
