# Generated by Django 4.0 on 2022-01-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_remove_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancelock',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='price',
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name='otctrade',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name='trx',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
    ]
