# Generated by Django 4.0 on 2022-01-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_alter_networkwallet_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otcrequest',
            old_name='price',
            new_name='to_amount',
        ),
        migrations.RemoveField(
            model_name='otcrequest',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='otcrequest',
            name='side',
        ),
        migrations.RemoveField(
            model_name='otctrade',
            name='amount',
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='from_asset',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='from_otc_requests', to='ledger.asset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='to_asset',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='to_otc_requests', to='ledger.asset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='to_price',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=40),
            preserve_default=False,
        ),
    ]
