# Generated by Django 4.0 on 2022-01-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_otcrequest_from_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='min_trade_quantity',
            field=models.DecimalField(decimal_places=10, default='0.000001', max_digits=15),
        ),
        migrations.AlterField(
            model_name='asset',
            name='trade_quantity_step',
            field=models.DecimalField(decimal_places=10, default='0.000001', max_digits=15),
        ),
    ]
