# Generated by Django 4.0 on 2022-01-19 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_type'),
        ('ledger', '0009_alter_asset_min_trade_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otctrade',
            name='provider_order_id',
        ),
        migrations.AddField(
            model_name='otctrade',
            name='lock',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ledger.balancelock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='from_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_selfs', to='ledger.asset'),
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='to_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_selfs', to='ledger.asset'),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('account', 'asset')},
        ),
    ]
