# Generated by Django 4.0 on 2022-01-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_remove_otctrade_provider_order_id_otctrade_lock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancelock',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
