# Generated by Django 4.0 on 2022-01-23 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_type'),
        ('ledger', '0012_remove_asset_image_remove_asset_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=256, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.network')),
            ],
            options={
                'unique_together': {('network', 'account')},
            },
        ),
        migrations.DeleteModel(
            name='NetworkWallet',
        ),
    ]
