# Generated by Django 4.0 on 2022-01-23 12:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_networkaddress_delete_networkwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=40)),
                ('deposit', models.BooleanField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done')], db_index=True, default='pending', max_length=8)),
                ('trx_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('block_hash', models.CharField(blank=True, db_index=True, max_length=128, unique=True)),
                ('block_number', models.PositiveIntegerField(blank=True, null=True)),
                ('out_address', models.CharField(max_length=256)),
                ('lock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ledger.balancelock')),
                ('network_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.networkaddress')),
            ],
        ),
    ]
