# Generated by Django 4.0 on 2022-01-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0014_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='lock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.balancelock'),
        ),
    ]
