# Generated by Django 4.0 on 2022-01-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0015_alter_transfer_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='minimum_block_to_confirm',
            field=models.IntegerField(default=0),
        ),
    ]
