# Generated by Django 4.0 on 2022-01-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_type'),
        ('ledger', '0015_alter_transfer_lock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wallet',
            name='market',
            field=models.CharField(choices=[('s', 'spot'), ('m', 'margin')], default='s', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('account', 'asset', 'market')},
        ),
    ]
