# Generated by Django 4.0 on 2022-01-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0016_alter_wallet_unique_together_wallet_market_and_more'),
        ('ledger', '0016_network_minimum_block_to_confirm'),
    ]

    operations = [
    ]
