# Generated by Django 4.0 on 2022-01-25 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0017_merge_20220125_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='wallet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ledger.wallet'),
            preserve_default=False,
        ),
    ]
