# Generated by Django 4.0 on 2022-01-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0018_transfer_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='explorer_link',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
