# Generated by Django 4.0 on 2022-01-25 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0019_asset_explorer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='minimum_block_to_confirm',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
