# Generated by Django 4.0 on 2022-01-25 13:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_type'),
        ('ledger', '0020_alter_network_minimum_block_to_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='trx',
            name='scope',
            field=models.CharField(choices=[('t', 'trade'), ('f', 'transfer'), ('m', 'margin transfer'), ('b', 'margin borrow')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='market',
            field=models.CharField(choices=[('s', 'spot'), ('m', 'margin'), ('b', 'borrow')], max_length=1),
        ),
        migrations.CreateModel(
            name='MarginTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('sm', 'spot to margin'), ('ms', 'margin to spot')], max_length=2)),
                ('group_id', models.UUIDField(default=uuid.uuid4)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='MarginLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('b', 'borrow'), ('r', 'r')], max_length=1)),
                ('group_id', models.UUIDField(default=uuid.uuid4)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
