# Generated by Django 4.0 on 2022-01-26 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0022_addressschema_depositaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marginloan',
            name='asset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ledger.asset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marginloan',
            name='lock',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ledger.balancelock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marginloan',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done')], default='pending', max_length=8),
        ),
        migrations.AddField(
            model_name='margintransfer',
            name='lock',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ledger.balancelock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='market',
            field=models.CharField(choices=[('s', 'spot'), ('m', 'margin')], default='s', max_length=1),
        ),
        migrations.AlterField(
            model_name='balancelock',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marginloan',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marginloan',
            name='type',
            field=models.CharField(choices=[('b', 'borrow'), ('r', 'repay')], max_length=1),
        ),
        migrations.AlterField(
            model_name='networkasset',
            name='min_withdraw',
            field=models.DecimalField(decimal_places=18, max_digits=25, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='networkasset',
            name='withdraw_commission',
            field=models.DecimalField(decimal_places=18, max_digits=25, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='from_amount',
            field=models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='to_amount',
            field=models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='to_price',
            field=models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='trx_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trx',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
