# Generated by Django 4.0 on 2022-01-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0023_marginloan_asset_marginloan_lock_marginloan_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='block_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
    ]
