# Generated by Django 4.0 on 2022-01-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0024_alter_transfer_block_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='network',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ledger.network'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='deposit_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.depositaddress'),
        ),
    ]
