# Generated by Django 4.0 on 2022-01-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0025_transfer_network_alter_transfer_deposit_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marginloan',
            name='type',
            field=models.CharField(choices=[('borrow', 'borrow'), ('repay', 'repay')], max_length=8),
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='market',
            field=models.CharField(choices=[('spot', 'spot'), ('margin', 'margin')], default='spot', max_length=8),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='market',
            field=models.CharField(choices=[('spot', 'spot'), ('margin', 'margin'), ('loan', 'loan')], max_length=8),
        ),
    ]
