# Generated by Django 4.0 on 2022-01-29 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_last_margin_warn'),
        ('ledger', '0028_remove_network_schema_depositaddress_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsecret',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
    ]
