# Generated by Django 4.0 on 2022-01-30 14:40
import math

from django.db import migrations


def create_assets(apps, schema_editor):
    Asset = apps.get_model('ledger', 'Asset')

    Asset.objects.get_or_create(symbol='IRT')

    symbols = ['USDT', 'BTC', 'ETH', 'BNB', 'SOL', 'SHIB', 'ADA', 'DOGE']

    for i, symbol in enumerate(symbols):
        Asset.objects.get_or_create(symbol=symbol, defaults={'order': i + 1})


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0030_remove_asset_explorer_link_network_explorer_link'),
    ]

    operations = [
        migrations.RunPython(create_assets, migrations.RunPython.noop),
    ]
