# Generated by Django 4.0 on 2022-01-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0031_create_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
    ]
