# Generated by Django 4.0 on 2022-02-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0032_alter_asset_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('not_brod', 'not_brod'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done')], db_index=True, default='pending', max_length=8),
        ),
    ]
