# Generated by Django 4.0 on 2022-02-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0033_alter_transfer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='is_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='block_hash',
            field=models.CharField(db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='block_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='trx_hash',
            field=models.CharField(db_index=True, max_length=128, null=True, unique=True),
        ),
    ]
