# Generated by Django 4.0 on 2022-02-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0036_asset_important'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ('-trend', 'order')},
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='important',
            new_name='trend',
        ),
    ]
