# Generated by Django 4.0 on 2022-02-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0038_network_address_regex_transfer_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='provider_transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.transfer'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='source',
            field=models.CharField(choices=[('self', 'self'), ('binance', 'binance')], default='self', max_length=8),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done')], db_index=True, default='pending', max_length=8),
        ),
    ]
