# Generated by Django 4.0 on 2022-02-06 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0040_alter_asset_options_asset_pin_to_top'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkasset',
            old_name='withdraw_commission',
            new_name='withdraw_fee',
        ),
        migrations.RenameField(
            model_name='networkasset',
            old_name='min_withdraw',
            new_name='withdraw_min',
        ),
        migrations.RemoveField(
            model_name='network',
            name='minimum_block_to_confirm',
        ),
        migrations.AddField(
            model_name='asset',
            name='withdraw_step',
            field=models.DecimalField(decimal_places=10, default='0.001', max_digits=15),
        ),
        migrations.AddField(
            model_name='network',
            name='min_confirm',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='network',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='network',
            name='unlock_confirm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkasset',
            name='withdraw_max',
            field=models.DecimalField(decimal_places=18, default=10000, max_digits=40, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='network',
            name='symbol',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
