# Generated by Django 4.0 on 2022-02-06 13:35
import json

from django.db import migrations


def create_network_assets(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0041_rename_withdraw_commission_networkasset_withdraw_fee_and_more'),
    ]

    operations = [
        migrations.RunPython(create_network_assets, migrations.RunPython.noop),
    ]
