# Generated by Django 4.0 on 2022-02-08 09:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0043_asset_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='fee_amount',
            field=models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=40, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
