# Generated by Django 4.0 on 2022-02-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0046_cryptobalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='block_hash',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='trx_hash',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('trx_hash', 'network'), name='unique_transfer_tx_hash_network'),
        ),
    ]
