# Generated by Django 4.0 on 2022-02-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0047_alter_transfer_block_hash_alter_transfer_trx_hash_and_more'),
        ('ledger', '0047_alter_trx_unique_together'),
    ]

    operations = [
    ]
