# Generated by Django 4.0 on 2022-02-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0048_merge_20220213_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='block_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='trx_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
            preserve_default=False,
        ),
    ]
