# Generated by Django 4.0 on 2022-02-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0049_alter_transfer_block_hash_alter_transfer_trx_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='block_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
