# Generated by Django 4.0 on 2022-02-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0050_alter_transfer_block_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='depositaddress',
            unique_together={('network', 'account_secret')},
        ),
        migrations.AlterField(
            model_name='depositaddress',
            name='address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='depositaddress',
            unique_together={('network', 'account_secret'), ('network', 'address')},
        ),
    ]
