# Generated by Django 4.0 on 2022-02-15 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0050_alter_transfer_block_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marginloan',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
