# Generated by Django 4.0 on 2022-02-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0051_alter_depositaddress_unique_together_and_more'),
        ('ledger', '0051_alter_marginloan_group_id'),
    ]

    operations = [
    ]
