# Generated by Django 4.0 on 2022-02-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0052_merge_20220216_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done')], db_index=True, default='process', max_length=8),
        ),
    ]
