# Generated by Django 4.0 on 2022-02-19 15:33
import math
from decimal import Decimal

from django.db import migrations, models


def populate_precision(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0053_alter_transfer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='withdraw_step',
        ),
        migrations.AddField(
            model_name='networkasset',
            name='withdraw_precision',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=populate_precision, reverse_code=migrations.RunPython.noop
        ),
    ]
