# Generated by Django 4.0 on 2022-02-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0055_remove_transfer_unique_transfer_tx_hash_network_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transfer',
            name='unique_transfer_tx_hash_network',
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'done'])), fields=('trx_hash', 'network', 'deposit'), name='unique_transfer_tx_hash_network'),
        ),
    ]
