# Generated by Django 4.0 on 2022-02-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0056_remove_transfer_unique_transfer_tx_hash_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marginloan',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده')], default='pending', max_length=8),
        ),
    ]
