# Generated by Django 4.0 on 2022-02-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0057_alter_marginloan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
