# Generated by Django 4.0 on 2022-02-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0058_transfer_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='description',
        ),
    ]
