# Generated by Django 4.0 on 2022-03-06 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0059_remove_asset_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='otcrequest',
            name='to_price_absolute_irt',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=40, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
