# Generated by Django 4.0 on 2022-03-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0060_otcrequest_to_price_absolute_irt'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkasset',
            name='binance_withdraw_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='asset',
            field=models.ForeignKey(limit_choices_to={'enable': True}, on_delete=django.db.models.deletion.PROTECT, to='ledger.asset'),
        ),
    ]
