# Generated by Django 4.0 on 2022-03-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0061_networkasset_binance_withdraw_enable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='hedge_method',
            field=models.CharField(choices=[('binance-future', 'binance-future'), ('binance-spot', 'binance-spot')], default='binance-future', max_length=16),
        ),
    ]
