# Generated by Django 4.0 on 2022-03-08 20:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0063_asset_buy_diff_asset_sell_diff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='buy_diff',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='sell_diff',
        ),
        migrations.AddField(
            model_name='asset',
            name='ask_diff',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='our ask (taker buy price): (1 + ask_diff) * binance_ask', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('0.1'))]),
        ),
        migrations.AddField(
            model_name='asset',
            name='bid_diff',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='our bid (taker sell price): (1 - bid_diff) * binance_bid', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('0.1'))]),
        ),
    ]
