# Generated by Django 4.0 on 2022-03-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0065_alter_asset_ask_diff_alter_asset_bid_diff'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='balancelock',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='check_amount'),
        ),
    ]
