# Generated by Django 4.0 on 2022-04-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0067_addressbook'),
        ('ledger', '0067_marginliquidation'),
    ]

    operations = [
    ]
