# Generated by Django 4.0 on 2022-04-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0066_balancelock_check_amount'),
        ('ledger', '0067_marginliquidation'),
    ]

    operations = [
    ]
