# Generated by Django 4.0 on 2022-04-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0067_marginliquidation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trx',
            name='scope',
            field=models.CharField(choices=[('t', 'trade'), ('f', 'transfer'), ('m', 'margin transfer'), ('b', 'margin borrow'), ('c', 'commission'), ('l', 'liquid'), ('fl', 'fast liquid')], max_length=2),
        ),
    ]
