# Generated by Django 4.0 on 2022-04-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0068_alter_trx_scope'),
        ('ledger', '0068_merge_0067_addressbook_0067_marginliquidation'),
    ]

    operations = [
    ]
