# Generated by Django 4.0 on 2022-04-06 07:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_historicaluser_first_trade_prize_activate_and_more'),
        ('ledger', '0070_alter_addressbook_options_alter_addressbook_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trx',
            name='scope',
            field=models.CharField(choices=[('t', 'trade'), ('f', 'transfer'), ('m', 'margin transfer'), ('b', 'margin borrow'), ('c', 'commission'), ('l', 'liquid'), ('fl', 'fast liquid'), ('p', 'prize')], max_length=2),
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)])),
                ('scope', models.CharField(choices=[('level 2 verification', 'level 2 verification'), ('sign up', 'sign up'), ('first trade', 'first trade')], max_length=25, verbose_name='نوع')),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='کاربر')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset')),
            ],
            options={
                'unique_together': {('account', 'scope')},
            },
        ),
    ]
