# Generated by Django 4.0 on 2022-04-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0071_alter_trx_scope_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='scope',
            field=models.CharField(choices=[('level2_verify', 'level2_verify'), ('signup', 'signup'), ('first_trade', 'first_trade')], max_length=25, verbose_name='نوع'),
        ),
    ]
