# Generated by Django 4.0 on 2022-04-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0068_merge_20220404_1125'),
        ('ledger', '0072_alter_prize_scope'),
    ]

    operations = [
    ]
