# Generated by Django 4.0 on 2022-04-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0070_network_is_universal'),
        ('ledger', '0073_merge_0068_merge_20220404_1125_0072_alter_prize_scope'),
    ]

    operations = [
    ]
