# Generated by Django 4.0 on 2022-04-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0074_delete_order'),
        ('ledger', '0074_merge_20220413_1043'),
    ]

    operations = [
    ]
