# Generated by Django 4.0 on 2022-04-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0069_merge_20220406_1017'),
        ('ledger', '0075_merge_0074_delete_order_0074_merge_20220413_1043'),
    ]

    operations = [
    ]
