# Generated by Django 4.0 on 2022-04-30 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0075_merge_0074_delete_order_0074_merge_20220413_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marginloan',
            name='lock',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.balancelock'),
        ),
        migrations.AlterField(
            model_name='margintransfer',
            name='lock',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.balancelock'),
        ),
        migrations.AlterField(
            model_name='otctrade',
            name='lock',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.balancelock'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='lock',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.balancelock'),
        ),
    ]
