# Generated by Django 4.0 on 2022-05-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0076_alter_marginloan_lock_alter_margintransfer_lock_and_more'),
        ('ledger', '0076_merge_20220427_1454'),
    ]

    operations = [
    ]
