# Generated by Django 4.0 on 2022-05-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0078_alter_prize_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='fake',
            field=models.BooleanField(default=False),
        ),
    ]
