# Generated by Django 4.0 on 2022-05-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_merge_20220511_1130'),
        ('ledger', '0079_prize_fake'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prize',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='prize',
            name='variant',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='prize',
            name='scope',
            field=models.CharField(choices=[('trade_2m', 'trade_2m'), ('referral_trade_2m', 'referral_trade_2m')], max_length=25, verbose_name='نوع'),
        ),
        migrations.AlterUniqueTogether(
            name='prize',
            unique_together={('account', 'scope', 'variant')},
        ),
    ]
