# Generated by Django 4.0 on 2022-05-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0080_alter_prize_unique_together_prize_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='trade_enable',
            field=models.BooleanField(default=True),
        ),
    ]
