# Generated by Django 4.0 on 2022-05-13 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0081_asset_trade_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkasset',
            name='withdraw_fee',
            field=models.DecimalField(decimal_places=18, max_digits=32, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='networkasset',
            name='withdraw_min',
            field=models.DecimalField(decimal_places=18, max_digits=32, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
