# Generated by Django 4.0 on 2022-05-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0082_alter_networkasset_withdraw_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='has_description',
            field=models.BooleanField(default=False),
        ),
    ]
