# Generated by Django 4.0 on 2022-05-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0083_coincategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coincategory',
            options={'verbose_name': 'دسته بندی رمزارزها', 'verbose_name_plural': 'دسته بندی رمزارزها'},
        ),
        migrations.AddField(
            model_name='prize',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
