# Generated by Django 4.0 on 2022-05-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0083_asset_has_description'),
        ('ledger', '0084_alter_coincategory_options_prize_redeemed'),
    ]

    operations = [
    ]
