# Generated by Django 4.0 on 2022-05-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0084_remove_asset_has_description'),
        ('ledger', '0085_merge_20220522_1532'),
    ]

    operations = [
    ]
