# Generated by Django 4.0 on 2022-05-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0086_merge_20220522_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='candidate',
            field=models.BooleanField(default=False),
        ),
    ]
