# Generated by Django 4.0 on 2022-05-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0086_merge_20220522_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coincategory',
            old_name='coin',
            new_name='coins',
        ),
        migrations.RemoveField(
            model_name='coincategory',
            name='name_fa',
        ),
        migrations.AlterField(
            model_name='coincategory',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
