# Generated by Django 4.0 on 2022-05-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0087_asset_candidate'),
        ('ledger', '0087_rename_coin_coincategory_coins_and_more'),
    ]

    operations = [
    ]
