# Generated by Django 4.0 on 2022-05-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0088_merge_20220524_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='margin_enable',
            field=models.BooleanField(default=False),
        ),
    ]
