# Generated by Django 4.0 on 2022-05-30 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0089_asset_margin_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='margintransfer',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ledger.asset'),
            preserve_default=False,
        ),
    ]
