# Generated by Django 4.0 on 2022-05-31 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0089_alter_trx_scope'),
        ('ledger', '0090_margintransfer_asset'),
    ]

    operations = [
    ]
