# Generated by Django 4.0 on 2022-06-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0092_wallet_balance_wallet_check_balance_wallet_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='margintransfer',
            name='lock',
        ),
    ]
