# Generated by Django 4.0 on 2022-06-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0093_remove_margintransfer_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hedge_method',
            field=models.CharField(blank=True, choices=[('', 'none'), ('binance-future', 'binance-future'), ('binance-spot', 'binance-spot')], default='binance-future', max_length=16),
        ),
        migrations.AlterField(
            model_name='trx',
            name='scope',
            field=models.CharField(choices=[('t', 'trade'), ('f', 'transfer'), ('m', 'margin transfer'), ('b', 'margin borrow'), ('c', 'commission'), ('l', 'liquid'), ('fl', 'fast liquid'), ('p', 'prize'), ('r', 'revert'), ('ad', 'airdrop')], max_length=2),
        ),
    ]
