# Generated by Django 4.0 on 2022-06-13 14:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0094_alter_asset_hedge_method_alter_trx_scope'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='balancelock',
            name='check_amount',
        ),
        migrations.AlterField(
            model_name='balancelock',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cryptobalance',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marginliquidation',
            name='margin_level',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marginloan',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='networkasset',
            name='withdraw_fee',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='networkasset',
            name='withdraw_max',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='networkasset',
            name='withdraw_min',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='from_amount',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='to_amount',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='to_price_absolute_irt',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='to_price_absolute_usdt',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='prize',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='fee_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='trx',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='balancelock',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='check_ledger_balance_lock_amount'),
        ),
        migrations.AddConstraint(
            model_name='cryptobalance',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='check_ledger_crypto_balance_amount'),
        ),
        migrations.AddConstraint(
            model_name='marginliquidation',
            constraint=models.CheckConstraint(check=models.Q(('margin_level__gte', 0)), name='check_margin_level'),
        ),
        migrations.AddConstraint(
            model_name='marginloan',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='check_ledger_margin_loan_amount'),
        ),
        migrations.AddConstraint(
            model_name='networkasset',
            constraint=models.CheckConstraint(check=models.Q(('withdraw_fee__gte', 0), ('withdraw_max__gte', 0), ('withdraw_min__gte', 0)), name='check_ledger_network_amounts'),
        ),
        migrations.AddConstraint(
            model_name='otcrequest',
            constraint=models.CheckConstraint(check=models.Q(('from_amount__gte', 0), ('to_amount__gte', 0), ('to_price__gte', 0), ('to_price_absolute_irt__gte', 0), ('to_price_absolute_usdt__gte', 0)), name='check_ledger_otc_request_amounts'),
        ),
        migrations.AddConstraint(
            model_name='prize',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='check_ledger_prize_amount'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0), ('fee_amount__gte', 0)), name='check_ledger_transfer_amounts'),
        ),
        migrations.AddConstraint(
            model_name='trx',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='check_ledger_trx_amount'),
        ),
    ]
