# Generated by Django 4.0 on 2022-06-14 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0095_remove_balancelock_check_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='precision',
        ),
    ]
