# Generated by Django 4.0 on 2022-06-19 10:53

from django.db import migrations, models


def populate_fake_verify_prize(apps, schema_editor):
    Account = apps.get_model('accounts', 'Account')
    Prize = apps.get_model('ledger', 'Prize')
    Asset = apps.get_model('ledger', 'Asset')

    asset, _ = Asset.objects.get_or_create(symbol='SHIB')

    prizes = []

    accounts = list(Prize.objects.filter(scope='level2_verify').values_list('account', flat=True))

    for account in Account.objects.filter(user__level__gte=2).exclude(id__in=accounts):
        prize = Prize(
            account=account,
            scope='level2_verify',
            asset=asset,
            amount=0,
            fake=True,
            redeemed=True,
        )
        prizes.append(prize)

    Prize.objects.bulk_create(prizes)


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0096_remove_asset_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='scope',
            field=models.CharField(choices=[('level2_verify', 'level2_verify'), ('trade_2m', 'trade_2m'), ('trade_s2', 'trade_s2'), ('referral_trade_2m', 'referral_trade_2m')], max_length=25, verbose_name='نوع'),
        ),
        migrations.RunPython(
            code=populate_fake_verify_prize, reverse_code=migrations.RunPython.noop
        )
    ]
