# Generated by Django 4.0 on 2022-06-20 07:08
from uuid import uuid4

import django.core.validators
from django.db import migrations, models
from django.db.models import F


def populate_balance_lock_keys(apps, schema_editor):
    BalanceLock = apps.get_model('ledger', 'BalanceLock')

    BalanceLock.objects.update(original_amount=F('amount'))
    BalanceLock.objects.filter(freed=True).update(amount=0)

    Order = apps.get_model('market', 'Order')
    Transfer = apps.get_model('ledger', 'Transfer')
    OTCTrade = apps.get_model('ledger', 'OTCTrade')
    MarginLoan = apps.get_model('ledger', 'MarginLoan')

    FiatWithdrawRequest = apps.get_model('financial', 'FiatWithdrawRequest')

    lock_mapping = {}

    lock_mapping.update(dict(Order.objects.filter(status='new').values_list('lock', 'group_id')))
    lock_mapping.update(dict(Transfer.objects.values_list('lock', 'group_id')))
    lock_mapping.update(dict(OTCTrade.objects.values_list('lock', 'group_id')))
    lock_mapping.update(dict(MarginLoan.objects.values_list('lock', 'group_id')))
    lock_mapping.update(dict(FiatWithdrawRequest.objects.values_list('lock', 'group_id')))

    locks = list(BalanceLock.objects.filter(id__in=list(lock_mapping)))

    for balance_lock in locks:
        balance_lock.key = balance_lock.key = lock_mapping[balance_lock.id]

    BalanceLock.objects.bulk_update(locks, ['key'])


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0097_alter_prize_scope'),
        ('market', '0023_populate_order_group_id'),
        ('financial', '0036_rename_withdraw_chanel_fiatwithdrawrequest_withdraw_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancelock',
            name='key',
            field=models.UUIDField(null=True, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balancelock',
            name='original_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),

        migrations.RunPython(code=populate_balance_lock_keys, reverse_code=migrations.RunPython.noop),
    ]
