# Generated by Django 4.0 on 2022-06-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0098_remove_trx_check_ledger_trx_amount_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trx',
            name='check_ledger_trx_amount',
        ),
        migrations.RemoveField(
            model_name='balancelock',
            name='freed',
        ),
        migrations.RemoveField(
            model_name='balancelock',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='marginloan',
            name='lock',
        ),
        migrations.RemoveField(
            model_name='otctrade',
            name='lock',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='lock',
        ),
        migrations.AddConstraint(
            model_name='trx',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='check_ledger_trx_amount'),
        ),
    ]
