# Generated by Django 4.0 on 2022-06-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0100_system_balance_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='new_coin',
            field=models.BooleanField(default=False),
        ),
    ]
