# Generated by Django 4.0 on 2022-06-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0101_asset_new_coin'),
        ('ledger', '0101_closerequest_balancelock_reason_and_more'),
    ]

    operations = [
    ]
