# Generated by Django 4.0 on 2022-07-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0103_remove_closerequest_unique_margin_close_request_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='need_memo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='memo',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
