# Generated by Django 4.0 on 2022-07-05 11:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_alter_externalnotification_options_and_more'),
        ('ledger', '0103_remove_closerequest_unique_margin_close_request_account_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wallet',
            name='variant',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('account', 'asset', 'market', 'variant')},
        ),
        migrations.CreateModel(
            name='ReserveWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('refund_completed', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserved_wallet', to='ledger.wallet')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserve_wallet', to='ledger.wallet')),
            ],
            options={
                'unique_together': {('group_id', 'sender', 'receiver')},
            },
        ),
    ]
