# Generated by Django 4.0 on 2022-07-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0104_network_need_memo_transfer_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trx',
            name='scope',
            field=models.CharField(choices=[('t', 'trade'), ('f', 'transfer'), ('m', 'margin transfer'), ('b', 'margin borrow'), ('c', 'commission'), ('l', 'liquid'), ('fl', 'fast liquid'), ('p', 'prize'), ('r', 'revert'), ('ad', 'airdrop'), ('st', 'stake')], max_length=2),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='market',
            field=models.CharField(choices=[('spot', 'spot'), ('margin', 'margin'), ('loan', 'loan'), ('stake', 'stake')], max_length=8),
        ),
    ]
