# Generated by Django 4.0 on 2022-07-16 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0104_network_need_memo_transfer_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='margintransfer',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
