# Generated by Django 4.0 on 2022-07-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0104_alter_wallet_unique_together_wallet_variant_id_and_more'),
        ('ledger', '0104_network_need_memo_transfer_memo'),
    ]

    operations = [
    ]
