# Generated by Django 4.0 on 2022-07-24 10:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_alter_externalnotification_scope'),
        ('ledger', '0105_alter_margintransfer_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNLHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('market', models.CharField(choices=[('spot', 'spot'), ('margin', 'margin')], default='spot', max_length=8)),
                ('base_asset', models.CharField(choices=[('IRT', 'IRT'), ('USDT', 'USDT')], max_length=8)),
                ('snapshot_balance', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('profit', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
