# Generated by Django 4.0 on 2022-07-26 05:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0106_alter_cryptobalance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30),
        ),
    ]
