# Generated by Django 4.0 on 2022-07-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0106_alter_cryptobalance_unique_together_and_more'),
        ('ledger', '0106_pnlhistory'),
    ]

    operations = [
    ]
