# Generated by Django 4.0 on 2022-07-25 14:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_alter_externalnotification_scope'),
        ('ledger', '0107_merge_20220725_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnlhistory',
            name='profit',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30),
        ),
        migrations.AlterUniqueTogether(
            name='pnlhistory',
            unique_together={('date', 'account', 'market', 'base_asset')},
        ),
    ]
