# Generated by Django 4.0 on 2022-07-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0105_merge_20220711_1529'),
        ('ledger', '0107_alter_wallet_balance'),
    ]

    operations = [
    ]
