# Generated by Django 4.0 on 2022-07-26 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0108_alter_pnlhistory_profit_alter_wallet_balance_and_more'),
        ('ledger', '0108_merge_20220726_1201'),
    ]

    operations = [
    ]
