# Generated by Django 4.0 on 2022-07-26 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0108_assetspreadcategory_alter_coincategory_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='categoryspread',
            name='step',
            field=models.PositiveIntegerField(choices=[(1, '0$ - 3$'), (2, '3$ - 10$'), (3, '10$ - 1000$'), (4, '1000$ - 2000$'), (5, '> 2000$')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='categoryspread',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True)), fields=('side', 'step'), name='asset_spread_uniqueness_for_null_category'),
        ),
        migrations.AddConstraint(
            model_name='categoryspread',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('category', 'side', 'step'), name='asset_spread_uniqueness_for_non_null_category'),
        ),
    ]
