# Generated by Django 4.0 on 2022-07-26 12:56
from decimal import Decimal

from django.db import migrations


def populate_asset_spread(apps, schema_editor):
    Asset = apps.get_model('ledger', 'Asset')
    AssetSpreadCategory = apps.get_model('ledger', 'AssetSpreadCategory')
    CategorySpread = apps.get_model('ledger', 'CategorySpread')

    usdt = AssetSpreadCategory.objects.create(name='tether')
    stable = AssetSpreadCategory.objects.create(name='stable-coins')
    popular = AssetSpreadCategory.objects.create(name='popular')
    high_risk = AssetSpreadCategory.objects.create(name='high-risk')

    coins_category = {
        usdt: ['USDT'],
        stable: ['USDC', 'BUSD', 'TUSD', 'TRIBE'],
        popular: ['BTC', 'ETH', 'BNB', 'TRX', 'DOGE', 'SOL'],
        high_risk: ['LUNA', 'LUNC']
    }

    for spread_category, coins in coins_category.items():
        Asset.objects.filter(symbol__in=coins).update(spread_category=spread_category)

    category_spreads = {
        usdt: [Decimal('0.25'), Decimal('0.5'), Decimal('1'), Decimal('2'), Decimal('4')],
        stable: [Decimal('0.25'), Decimal('0.5'), Decimal('1'), Decimal('2'), Decimal('4')],
        popular: [Decimal('0.25'), Decimal('0.5'), Decimal('1'), Decimal('2'), Decimal('4')],
        None: [Decimal('0.5'), Decimal('1'), Decimal('2'), Decimal('4'), Decimal('8')],
        high_risk: [Decimal('1.5'), Decimal('3'), Decimal('6'), Decimal('10'), Decimal('15')],
    }

    for category, spreads in category_spreads.items():
        for i, spread in enumerate(spreads):
            CategorySpread.objects.create(category=category, side='buy', step=i + 1, spread=spread)
            CategorySpread.objects.create(category=category, side='sell', step=i + 1, spread=spread)


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0109_alter_wallet_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_asset_spread, reverse_code=migrations.RunPython.noop)
    ]
