# Generated by Django 4.0 on 2022-07-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0108_assetspreadcategory_alter_coincategory_options_and_more'),
        ('ledger', '0110_alter_wallet_unique_together_and_more'),
    ]

    operations = [
    ]
