# Generated by Django 4.0 on 2022-07-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0110_auto_20220726_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetspreadcategory',
            options={'verbose_name': 'دسته\u200cبندی اسپرید', 'verbose_name_plural': 'دسته\u200cبندی اسپرید'},
        ),
        migrations.AlterModelOptions(
            name='categoryspread',
            options={'verbose_name': 'اسپرید', 'verbose_name_plural': 'اسپرید'},
        ),
        migrations.AlterField(
            model_name='categoryspread',
            name='side',
            field=models.CharField(choices=[('buy', 'bid'), ('sell', 'ask')], max_length=8),
        ),
    ]
