# Generated by Django 4.0 on 2022-07-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0106_alter_trx_scope'),
        ('ledger', '0110_alter_wallet_unique_together_and_more'),
    ]

    operations = [
    ]
