# Generated by Django 4.0 on 2022-07-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0109_alter_wallet_unique_together_and_more'),
        ('ledger', '0111_merge_20220726_1641'),
    ]

    operations = [
    ]
