# Generated by Django 4.0 on 2022-07-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0111_merge_20220726_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trx',
            name='scope',
            field=models.CharField(choices=[('t', 'trade'), ('f', 'transfer'), ('m', 'margin transfer'), ('b', 'margin borrow'), ('c', 'commission'), ('l', 'liquid'), ('fl', 'fast liquid'), ('p', 'prize'), ('r', 'revert'), ('ad', 'airdrop'), ('st', 'stake'), ('sr', 'stake_revenue'), ('rs', 'reserve')], max_length=2),
        ),
    ]
