# Generated by Django 4.0 on 2022-07-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_alter_externalnotification_scope'),
        ('ledger', '0111_alter_assetspreadcategory_options_and_more'),
    ]
