# Generated by Django 4.0 on 2022-07-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0110_auto_20220726_1726'),
        ('ledger', '0112_merge_20220726_1657'),
    ]

    operations = [
    ]
