# Generated by Django 4.0 on 2022-07-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0112_alter_trx_scope'),
        ('ledger', '0113_merge_20220726_1729'),
    ]

    operations = [
    ]
