# Generated by Django 4.0 on 2022-07-31 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0112_alter_wallet_unique_together'),
        ('ledger', '0114_merge_0112_alter_trx_scope_0113_merge_20220726_1729'),
    ]

    operations = [
    ]
