# Generated by Django 4.0 on 2022-08-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0113_delete_cryptobalance'),
        ('ledger', '0115_merge_20220731_1006'),
    ]

    operations = [
    ]
