# Generated by Django 4.0 on 2022-08-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0112_rename_binance_withdraw_enable_networkasset_hedger_withdraw_enable_and_more'),
        ('ledger', '0117_alter_transfer_source'),
    ]

    operations = [
    ]
