# Generated by Django 4.0 on 2022-08-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0118_merge_20220813_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='source',
            field=models.CharField(choices=[('self', 'self'), ('internal', 'internal'), ('binance', 'binance'), ('kucoin', 'kucoin')], default='self', max_length=8),
        ),
    ]
