# Generated by Django 4.0 on 2022-08-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0119_alter_transfer_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coincategory',
            name='coins',
            field=models.ManyToManyField(to='ledger.Asset'),
        ),
    ]
