# Generated by Django 4.0 on 2022-08-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0119_alter_transfer_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='kucoin_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
