# Generated by Django 4.0 on 2022-08-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0121_systemsnapshot_assetsnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetsnapshot',
            options={'verbose_name': 'تاریخچه دارایی', 'verbose_name_plural': 'تاریخچه دارایی'},
        ),
        migrations.AlterModelOptions(
            name='systemsnapshot',
            options={'verbose_name': 'تاریخچه سیستم', 'verbose_name_plural': 'تاریخچه سیستم'},
        ),
    ]
