# Generated by Django 4.0 on 2022-08-18 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0122_alter_assetsnapshot_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsnapshot',
            old_name='margin_futures_initial_margin',
            new_name='binance_futures_initial_margin',
        ),
        migrations.RenameField(
            model_name='systemsnapshot',
            old_name='margin_futures_maintenance_margin',
            new_name='binance_futures_maintenance_margin',
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='hedge',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='binance_futures_available_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='binance_futures_margin_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='binance_futures_margin_ratio',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
