# Generated by Django 4.0 on 2022-08-18 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0123_rename_margin_futures_initial_margin_systemsnapshot_binance_futures_initial_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsnapshot',
            name='cumulated_hedge',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='prize',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
