# Generated by Django 4.0 on 2022-08-18 14:21
from decimal import Decimal

import django.core.validators
from django.db import migrations, models
from django.db.models import F


def populate_prize_value(apps, schema_editor):
    Prize = apps.get_model('ledger', 'Prize')

    Prize.objects.update(value=F('amount') * Decimal('0.000015'))


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0124_systemsnapshot_cumulated_hedge_systemsnapshot_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='value',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),

        migrations.RunPython(populate_prize_value, reverse_code=migrations.RunPython.noop)
    ]
