# Generated by Django 4.0 on 2022-08-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0125_prize_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hedge_method',
            field=models.CharField(blank=True, choices=[('kucoin-spot', 'kucoin-spot'), ('kucoin-future', 'kucoin-future'), ('binance-spot', 'binance-spot'), ('binance-future', 'binance-future'), ('', '')], default='binance-future', max_length=32),
        ),
    ]
