# Generated by Django 4.0 on 2022-08-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0120_network_kucoin_name_alter_asset_symbol'),
        ('ledger', '0126_alter_asset_hedge_method'),
    ]

    operations = [
    ]
