# Generated by Django 4.0 on 2022-08-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0127_merge_20220822_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='original_symbol',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
