# Generated by Django 4.0 on 2022-08-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0128_alter_asset_hedge_method'),
        ('ledger', '0128_asset_original_symbol'),
    ]

    operations = [
    ]
