# Generated by Django 4.0 on 2022-08-30 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0130_alter_asset_hedge_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsnapshot',
            name='kucoin_spot',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='mexc_spot',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
