# Generated by Django 4.0 on 2022-08-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0131_systemsnapshot_kucoin_spot_systemsnapshot_mexc_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkasset',
            name='can_withdraw',
            field=models.BooleanField(default=True),
        ),
    ]
