# Generated by Django 4.0 on 2022-08-31 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0132_asset_original_name_fa'),
        ('ledger', '0132_networkasset_can_withdraw'),
    ]

    operations = [
    ]
