# Generated by Django 4.0 on 2022-09-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0134_merge_20220831_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsnapshot',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
