# Generated by Django 4.0 on 2022-09-04 13:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0058_fiathedgetrx'),
        ('ledger', '0135_systemsnapshot_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastBuyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('status', models.CharField(choices=[('process', 'process'), ('deposit', 'deposit'), ('done', 'done')], default='process', max_length=16)),
                ('amount', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset')),
                ('otc_request', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.otcrequest')),
                ('payment_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='financial.paymentrequest')),
            ],
            options={
                'verbose_name': 'خرید آنی',
                'verbose_name_plural': 'خرید آنی',
            },
        ),
    ]
