# Generated by Django 4.0 on 2022-10-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0139_alter_prize_unique_together_prize_achievement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='candidate',
        ),
    ]
