# Generated by Django 4.0 on 2022-11-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0142_networkasset_hedger_deposit_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='hedge_method',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='provider_transfer',
        ),
        migrations.AddField(
            model_name='asset',
            name='hedge',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='source',
            field=models.CharField(choices=[('self', 'self'), ('internal', 'internal'), ('provider', 'provider')], default='self', max_length=8),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done')], db_index=True, default='process', max_length=8),
        ),
    ]
