# Generated by Django 4.1.3 on 2022-12-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0143_remove_asset_hedge_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='source',
            field=models.CharField(choices=[('self', 'self'), ('internal', 'internal'), ('provider', 'provider'), ('manual', 'manual')], default='self', max_length=8),
        ),
    ]
