# Generated by Django 4.1.3 on 2022-12-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0146_transfer_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='hidden',
        ),
    ]
