# Generated by Django 4.1.3 on 2022-12-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0147_remove_transfer_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='is_fee',
        ),
    ]
