# Generated by Django 4.1.3 on 2022-12-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0148_remove_transfer_is_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='accepted_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='finished_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
