# Generated by Django 4.1.3 on 2022-12-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0149_transfer_accepted_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkasset',
            name='allow_provider_withdraw',
            field=models.BooleanField(default=True),
        ),
    ]
