# Generated by Django 4.1.3 on 2022-12-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0150_networkasset_allow_provider_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='risks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
