# Generated by Django 4.0.4 on 2022-12-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0150_networkasset_allow_provider_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservewallet',
            name='request_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
