# Generated by Django 4.1.3 on 2022-12-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0151_reservewallet_request_id'),
        ('ledger', '0151_transfer_risks'),
    ]

    operations = [
    ]
