# Generated by Django 4.1.3 on 2023-01-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0155_alter_marketspread_spread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetspreadcategory',
            options={'verbose_name': 'Spread Category', 'verbose_name_plural': 'Spread Categories'},
        ),
        migrations.AlterModelOptions(
            name='categoryspread',
            options={'verbose_name': 'Asset Spread', 'verbose_name_plural': 'Asset Spread'},
        ),
        migrations.AlterModelOptions(
            name='marketspread',
            options={'verbose_name': 'Market Spread', 'verbose_name_plural': 'Market Spread'},
        ),
        migrations.AddConstraint(
            model_name='marketspread',
            constraint=models.UniqueConstraint(fields=('side', 'step'), name='market_spread_uniqueness'),
        ),
    ]
