# Generated by Django 4.1.3 on 2023-01-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0156_alter_assetspreadcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transfer',
            name='unique_transfer_tx_hash_network',
        ),
        migrations.AlterField(
            model_name='otctrade',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('revert', 'revert')], default='pending', max_length=8, verbose_name='وضعیت'),
        ),
    ]
