# Generated by Django 4.1.3 on 2023-01-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0157_remove_transfer_unique_transfer_tx_hash_network_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallet',
            name='valid_balance_constraint',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='market',
            field=models.CharField(choices=[('spot', 'spot'), ('margin', 'margin'), ('loan', 'loan'), ('stake', 'stake'), ('voucher', 'voucher'), ('debt', 'debt')], max_length=8),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('check_balance', False), models.Q(models.Q(('market__in', ('loan', 'debt')), _negated=True), ('balance__gte', 0), ('balance__gte', models.F('locked'))), models.Q(('market__in', ('loan', 'debt')), ('balance__lte', 0), ('locked', 0)), _connector='OR'), name='valid_balance_constraint'),
        ),
    ]
