# Generated by Django 4.1.3 on 2023-01-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0158_remove_wallet_valid_balance_constraint_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'self'), ('trx_hash__isnull', False)), fields=('trx_hash', 'network', 'wallet', 'deposit_address', 'out_address'), name='unique_ledger_transfer_trx_hash_addresses'),
        ),
    ]
