# Generated by Django 4.1.3 on 2023-01-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0159_transfer_unique_ledger_transfer_trx_hash_addresses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetsnapshot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='systemsnapshot',
            options={},
        ),
        migrations.RemoveField(
            model_name='assetsnapshot',
            name='cash_amount',
        ),
        migrations.RemoveField(
            model_name='assetsnapshot',
            name='internal_amount',
        ),
        migrations.RemoveField(
            model_name='assetsnapshot',
            name='investment_amount',
        ),
        migrations.RemoveField(
            model_name='assetsnapshot',
            name='provider_amount',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='binance_futures',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='binance_futures_available_balance',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='binance_futures_initial_margin',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='binance_futures_maintenance_margin',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='binance_futures_margin_balance',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='binance_futures_margin_ratio',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='binance_spot',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='cumulated_hedge',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='fiat_gateway',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='internal',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='kucoin_spot',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='mexc_spot',
        ),
    ]
