# Generated by Django 4.1.3 on 2023-02-08 14:58
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0102_historicaluser_first_crypto_deposit_date_and_more'),
        ('market', '0041_remove_trade_gap_revenue_remove_trade_hedge_price_and_more'),
        ('ledger', '0161_systemsnapshot_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='otcrequest',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=30, null=True,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='base_irt_price',
            field=models.DecimalField(decimal_places=8,  null=True, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='base_usdt_price',
            field=models.DecimalField(decimal_places=8, null=True, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='fee_amount',
            field=models.DecimalField(decimal_places=8, null=True, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='fee_revenue',
            field=models.DecimalField(decimal_places=8, null=True, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='fee_usdt_value',
            field=models.DecimalField(decimal_places=8, null=True, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='price',
            field=models.DecimalField(decimal_places=8, null=True, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='side',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], null=True, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.pairsymbol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otctrade',
            name='execution_type',
            field=models.CharField(choices=[('m', 'market'), ('p', 'provider')], default='p', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otctrade',
            name='gap_revenue',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='otctrade',
            name='order_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
