# Generated by Django 4.1.3 on 2023-02-09 13:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0163_populate_otc_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otcrequest',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='base_irt_price',
            field=models.DecimalField(decimal_places=8, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='base_usdt_price',
            field=models.DecimalField(decimal_places=8, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='fee_amount',
            field=models.DecimalField(decimal_places=8, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='fee_revenue',
            field=models.DecimalField(decimal_places=8, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='fee_usdt_value',
            field=models.DecimalField(decimal_places=8, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='side',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.pairsymbol'),
            preserve_default=False,
        ),

        migrations.RemoveConstraint(
            model_name='otcrequest',
            name='check_ledger_otc_request_amounts',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='max_trade_quantity',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='min_trade_quantity',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='trade_quantity_step',
        ),
        migrations.RemoveField(
            model_name='otcrequest',
            name='to_price',
        ),
        migrations.RemoveField(
            model_name='otcrequest',
            name='to_price_absolute_irt',
        ),
        migrations.RemoveField(
            model_name='otcrequest',
            name='to_price_absolute_usdt',
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='from_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True,
                                      validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='market',
            field=models.CharField(
                choices=[('spot', 'spot'), ('margin', 'margin'), ('loan', 'loan'), ('stake', 'stake'),
                         ('voucher', 'voucher'), ('debt', 'debt')], max_length=8),
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='to_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True,
                                      validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='otctrade',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='otctrade',
            name='status',
            field=models.CharField(
                choices=[('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('revert', 'revert')],
                default='pending', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='otcrequest',
            constraint=models.CheckConstraint(check=models.Q(('from_amount__gte', 0), ('to_amount__gte', 0)),
                                              name='check_ledger_otc_request_amounts'),
        ),
        migrations.AddConstraint(
            model_name='otcrequest',
            constraint=models.CheckConstraint(
                check=models.Q(('amount__gte', 0), ('fee_amount__gte', 0), ('price__gte', 0)),
                name='otc_request_check_trade_amounts'),
        ),
    ]
