# Generated by Django 4.1.3 on 2023-02-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0164_remove_otcrequest_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trx',
            name='scope',
            field=models.CharField(choices=[('t', 'trade'), ('f', 'transfer'), ('m', 'margin transfer'), ('b', 'margin borrow'), ('c', 'commission'), ('l', 'liquid'), ('fl', 'fast liquid'), ('p', 'prize'), ('r', 'revert'), ('ad', 'airdrop'), ('st', 'stake'), ('sr', 'stake revenue'), ('sf', 'stake fee'), ('rs', 'reserve'), ('du', 'dust')], max_length=2),
        ),
    ]
