# Generated by Django 4.1.3 on 2023-02-13 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0042_alter_trade_base_usdt_price'),
        ('ledger', '0166_networkasset_update_fee_with_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otcrequest',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.pairsymbol'),
        ),
    ]
