# Generated by Django 4.1.3 on 2023-02-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0168_alter_trx_scope_manualtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='new_coin',
        ),
        migrations.AddField(
            model_name='asset',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
