# Generated by Django 4.1.3 on 2023-02-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0169_remove_asset_new_coin_asset_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='otc_status',
            field=models.CharField(choices=[('active', 'active'), ('buy', 'buy'), ('sell', 'sell')], default='active', max_length=8),
        ),
    ]
