# Generated by Django 4.1.3 on 2023-02-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0170_asset_otc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='otc_status',
            field=models.CharField(choices=[('active', 'active'), ('buy', 'buy'), ('sell', 'sell'), ('disabled', 'disabled')], default='active', max_length=8),
        ),
    ]
