# Generated by Django 4.1.3 on 2023-02-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0171_alter_asset_otc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='market',
            field=models.CharField(choices=[('spot', 'spot'), ('margin', 'margin'), ('loan', 'loan'), ('stake', 'stake'), ('voucher', 'voucher'), ('debt', 'debt')], db_index=True, max_length=8),
        ),
    ]
