# Generated by Django 4.1.3 on 2023-02-23 17:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ledger', '0173_alter_categoryspread_step_alter_marketspread_spread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryspread',
            name='spread',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.25'), max_digits=30, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='categoryspread',
            name='step',
            field=models.PositiveIntegerField(choices=[(1, '0$ - 3$'), (2, '3$ - 10$'), (3, '10$ - 1000$'), (4, '1000$ - 2000$'), (5, '> 2000$')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
