# Generated by Django 4.1.3 on 2023-02-28 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0174_alter_categoryspread_spread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closerequest',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='manualtransaction',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='marginloan',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
