# Generated by Django 4.1.3 on 2023-05-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0176_addresskey_deleted_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='addresskey',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('account', 'architecture'), name='ledger_addresskey_unique_account_architecture'),
        ),
    ]
