# Generated by Django 4.1.3 on 2023-05-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0178_prize_voucher_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsnapshot',
            name='created',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='assetsnapshot',
            unique_together={('created', 'asset')},
        ),
    ]
