# Generated by Django 4.1.3 on 2023-05-20 13:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0180_systemsnapshot_binance_margin_ratio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assetsnapshot',
        ),

        migrations.CreateModel(
            name='HistoricalAssetSnapshot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('updated', models.DateTimeField(db_index=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=30,
                                              validators=[django.core.validators.MinValueValidator(0)])),
                ('hedge_amount', models.DecimalField(decimal_places=8, max_digits=30,
                                                     validators=[django.core.validators.MinValueValidator(0)])),
                ('hedge_value', models.DecimalField(decimal_places=8, max_digits=30,
                                                    validators=[django.core.validators.MinValueValidator(0)])),
                ('calc_hedge_amount', models.DecimalField(decimal_places=8, max_digits=30,
                                                          validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=8, max_digits=30,
                                                     validators=[django.core.validators.MinValueValidator(0)])),
                ('users_amount', models.DecimalField(decimal_places=8, max_digits=30,
                                                     validators=[django.core.validators.MinValueValidator(0)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('asset', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                            on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                            to='ledger.asset')),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical asset snapshot',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AssetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(db_index=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=30,
                                              validators=[django.core.validators.MinValueValidator(0)])),
                ('hedge_amount', models.DecimalField(decimal_places=8, max_digits=30,
                                                     validators=[django.core.validators.MinValueValidator(0)])),
                ('hedge_value', models.DecimalField(decimal_places=8, max_digits=30,
                                                    validators=[django.core.validators.MinValueValidator(0)])),
                ('calc_hedge_amount', models.DecimalField(decimal_places=8, max_digits=30,
                                                          validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=8, max_digits=30,
                                                     validators=[django.core.validators.MinValueValidator(0)])),
                ('users_amount', models.DecimalField(decimal_places=8, max_digits=30,
                                                     validators=[django.core.validators.MinValueValidator(0)])),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset')),
            ],
        ),
    ]
