# Generated by Django 4.1.3 on 2023-05-20 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0181_alter_assetsnapshot_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsnapshot',
            name='hedge_value_abs',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalassetsnapshot',
            name='hedge_value_abs',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assetsnapshot',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalassetsnapshot',
            name='updated',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
    ]
