# Generated by Django 4.1.3 on 2023-05-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0183_alter_trx_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='block_hash',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='block_number',
        ),
    ]
