# Generated by Django 4.1.3 on 2023-06-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0184_remove_transfer_block_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closerequest',
            name='status',
            field=models.CharField(choices=[('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='manualtransaction',
            name='status',
            field=models.CharField(choices=[('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='marginloan',
            name='status',
            field=models.CharField(choices=[('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده')], default='pending', max_length=8),
        ),
    ]
