# Generated by Django 4.1.3 on 2023-06-28 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0185_alter_closerequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='address_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.addressbook'),
        ),
    ]
