# Generated by Django 4.1.3 on 2023-07-05 07:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0186_transfer_address_book'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallet',
            name='valid_balance_constraint',
        ),
        migrations.AddField(
            model_name='wallet',
            name='credit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='categoryspread',
            name='spread',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.25'), max_digits=30, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('check_balance', False), models.Q(models.Q(('market__in', ('loan', 'debt')), _negated=True), ('balance__gte', django.db.models.expressions.CombinedExpression(models.F('credit'), '*', models.Value(-1))), ('balance__gte', models.F('locked'))), models.Q(('market__in', ('loan', 'debt')), ('balance__lte', 0), ('locked', 0)), _connector='OR'), name='valid_balance_constraint'),
        ),
    ]
