# Generated by Django 4.1.3 on 2023-07-05 08:09

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0187_remove_wallet_valid_balance_constraint_wallet_credit_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallet',
            name='valid_balance_constraint',
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('check_balance', False), models.Q(models.Q(('market__in', ('loan', 'debt')), _negated=True), ('balance__gte', django.db.models.expressions.CombinedExpression(models.F('locked'), '-', models.F('credit')))), models.Q(('market__in', ('loan', 'debt')), ('balance__lte', 0), ('locked', 0)), _connector='OR'), name='valid_balance_constraint'),
        ),
    ]
