# Generated by Django 4.1.3 on 2023-07-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0188_remove_wallet_valid_balance_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='price_page',
            field=models.BooleanField(default=False),
        ),
    ]
