# Generated by Django 4.1.3 on 2023-07-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0189_asset_price_page'),
        ('ledger', '0189_otcrequest_login_activity_transfer_login_activity'),
    ]

    operations = [
    ]
