# Generated by Django 4.1.3 on 2023-07-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0192_alter_systemsnapshot_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='exchange_potential',
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='exchange',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='margin_insurance',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='reserved',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
    ]
