# Generated by Django 4.1.3 on 2023-07-26 11:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0138_merge_20230711_1255'),
        ('market', '0052_cancelrequest_login_activity_order_login_activity_and_more'),
        ('ledger', '0193_remove_systemsnapshot_exchange_potential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marginloan',
            name='variant',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='margintransfer',
            name='position_symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='market.pairsymbol'),
        ),
        migrations.AlterField(
            model_name='assetsnapshot',
            name='updated',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalassetsnapshot',
            name='updated',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='margintransfer',
            name='type',
            field=models.CharField(choices=[('sm', 'spot to margin'), ('ms', 'margin to spot'), ('mp', 'margin to position'), ('pm', 'position to margin')], max_length=2),
        ),
        migrations.CreateModel(
            name='MarginPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_price', models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('liquidation_price', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('side', models.CharField(choices=[('long', 'long'), ('short', 'short')], max_length=8)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=8)),
                ('leverage', models.IntegerField(default=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.pairsymbol')),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ledger.wallet')),
            ],
        ),
    ]
