# Generated by Django 4.1.3 on 2023-07-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0193_remove_systemsnapshot_exchange_potential_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsnapshot',
            name='updated',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalassetsnapshot',
            name='updated',
            field=models.DateTimeField(db_index=True),
        ),
    ]
