# Generated by Django 4.1.3 on 2023-07-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0194_alter_assetsnapshot_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsnapshot',
            name='created',
            field=models.DateTimeField(db_index=True, unique=True),
        ),
    ]
