# Generated by Django 4.1.3 on 2023-07-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0194_marginloan_variant_margintransfer_position_symbol_and_more'),
        ('ledger', '0195_alter_systemsnapshot_created'),
    ]

    operations = [
    ]
