# Generated by Django 4.1.3 on 2023-07-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0195_alter_systemsnapshot_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='coincategory',
            name='binance_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
