# Generated by Django 4.1.3 on 2023-07-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0196_coincategory_binance_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coincategory',
            options={'ordering': ('order',), 'verbose_name': 'گروه\u200cبندی نمایش رمزارزها', 'verbose_name_plural': 'گروه\u200cبندی نمایش رمزارزها'},
        ),
        migrations.AddField(
            model_name='coincategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coincategory',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='coincategory',
            name='title',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
