# Generated by Django 4.1.3 on 2023-08-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0196_merge_20230731_1638'),
        ('ledger', '0198_alter_coincategory_coins'),
    ]

    operations = [
    ]
