# Generated by Django 4.1.3 on 2023-08-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0198_alter_coincategory_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='distribution_factor',
            field=models.FloatField(default=0),
        ),
    ]
