# Generated by Django 4.1.3 on 2023-08-06 10:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0199_asset_distribution_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='spread_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.assetspreadcategory'),
        ),
        migrations.AlterField(
            model_name='categoryspread',
            name='step',
            field=models.PositiveIntegerField(choices=[(1, '> 0$'), (2, '>= 3$'), (3, '>= 10$'), (4, '>= 1000$'), (5, '> 2000$')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
