# Generated by Django 4.1.3 on 2023-08-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0203_manualtrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransfer',
            name='finished_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='finished_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
