# Generated by Django 4.1.3 on 2023-08-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0204_alter_historicaltransfer_finished_datetime_and_more'),
        ('ledger', '0204_assetalert'),
    ]

    operations = [
    ]
