# Generated by Django 4.1.3 on 2023-08-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0205_merge_20230817_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsnapshot',
            name='cum_hedge',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='hedge',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
    ]
