# Generated by Django 4.1.3 on 2023-08-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0209_alerttrigger_alerttrigger_alert_trigger_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttrigger',
            name='change_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alerttrigger',
            name='interval',
            field=models.CharField(choices=[('5m', '5m'), ('1h', '1h')], max_length=15),
        ),
    ]
