# Generated by Django 4.1.3 on 2023-08-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0210_alerttrigger_change_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerttrigger',
            name='interval',
            field=models.CharField(choices=[('5m', 'پنج\u200c دقیقه'), ('1h', '\u200cیک\u200c ساعت')], max_length=15),
        ),
    ]
