# Generated by Django 4.1.3 on 2023-08-30 16:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0212_historicaltransfer_accepted_by_transfer_accepted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkasset',
            name='deposit_min',
            field=models.DecimalField(decimal_places=8, default=Decimal('1E-8'), max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))]),
        ),
    ]
