# Generated by Django 4.1.3 on 2023-08-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0213_networkasset_deposit_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkasset',
            name='last_provider_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
