# Generated by Django 4.1.3 on 2023-09-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0215_bulkassetalert_alerttrigger_chanel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='kucoin_name',
        ),
    ]
