# Generated by Django 4.1.3 on 2023-09-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0199_merge_20230802_1535'),
        ('ledger', '0199_otctrade_hedged_otctrade_to_buy_amount'),
        ('ledger', '0215_remove_network_kucoin_name'),
    ]

    operations = [
    ]
