# Generated by Django 4.1.3 on 2023-09-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0217_auto_20230918_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='coincategory',
            name='header',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
