# Generated by Django 4.1.3 on 2023-09-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0154_merge_20230917_1513'),
        ('ledger', '0218_coincategory_header'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addresskey',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='addresskey',
            name='memo',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='addresskey',
            unique_together={('account', 'address', 'memo')},
        ),
        migrations.AlterUniqueTogether(
            name='depositaddress',
            unique_together={('address_key', 'network', 'address')},
        ),
        migrations.AddConstraint(
            model_name='addresskey',
            constraint=models.UniqueConstraint(condition=models.Q(('memo', ''), _negated=True), fields=('memo', 'architecture'), name='ledger_addresskey_unique_memo_architecture'),
        ),
    ]
