# Generated by Django 4.1.3 on 2023-09-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0219_alter_addresskey_unique_together_addresskey_memo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresskey',
            name='memo',
            field=models.CharField(blank=True, db_index=True, max_length=256),
        ),
    ]
