# Generated by Django 4.1.3 on 2023-10-08 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0220_alter_addresskey_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkasset',
            name='expected_hw_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
