# Generated by Django 4.1.3 on 2023-10-04 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0220_alter_addresskey_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی بازخورد برداشت',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای بازخورد برداشت',
            },
        ),
        migrations.CreateModel(
            name='WithdrawFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.feedbackcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بازخورد برداشت',
                'verbose_name_plural': 'بازخورد های برداشت',
            },
        ),
    ]
