# Generated by Django 4.1.3 on 2023-10-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0221_networkasset_expected_hw_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='expected_confirmation_minutes',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
