# Generated by Django 4.1.3 on 2023-10-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0221_feedbackcategory_withdrawfeedback'),
        ('ledger', '0221_networkasset_expected_hw_balance'),
    ]

    operations = [
    ]
