# Generated by Django 4.1.3 on 2023-10-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0222_merge_20231011_1640'),
        ('ledger', '0222_network_expected_confirmation_minutes'),
    ]

    operations = [
    ]
