# Generated by Django 4.1.3 on 2023-11-11 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0224_depositrecoveryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='stale_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
