# Generated by Django 4.1.3 on 2023-11-14 10:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0225_asset_stale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trx',
            name='scope',
            field=models.CharField(choices=[('t', 'trade'), ('f', 'transfer'), ('m', 'margin transfer'), ('b', 'margin borrow'), ('c', 'commission'), ('l', 'liquid'), ('fl', 'fast liquid'), ('p', 'prize'), ('r', 'revert'), ('ad', 'airdrop'), ('st', 'stake'), ('sr', 'stake revenue'), ('sf', 'stake fee'), ('rs', 'reserve'), ('du', 'dust'), ('mn', 'manual'), ('dl', 'delist'), ('rb', 'rebrand')], max_length=2),
        ),
        migrations.CreateModel(
            name='TokenRebrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('new_asset_multiplier', models.DecimalField(decimal_places=8, default=1, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده')], default='pending', max_length=8)),
                ('group_id', models.UUIDField(default=uuid.uuid4)),
                ('new_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_rebrand_new', to='ledger.asset')),
                ('old_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_rebrand_old', to='ledger.asset')),
                ('testers', models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
