# Generated by Django 4.1.3 on 2023-11-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0228_alter_feedbackcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsnapshot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
