# Generated by Django 4.1.3 on 2023-12-10 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0172_alter_userfeatureperm_feature'),
        ('ledger', '0229_systemsnapshot_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='حساب'),
        ),
    ]
