# Generated by Django 4.1.3 on 2024-01-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0234_alter_marginhistorymodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrecoveryrequest',
            name='status',
            field=models.CharField(choices=[('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], default='process', max_length=8),
        ),
        migrations.AlterField(
            model_name='manualtrade',
            name='status',
            field=models.CharField(choices=[('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='manualtransaction',
            name='status',
            field=models.CharField(choices=[('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='tokenrebrand',
            name='status',
            field=models.CharField(choices=[('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], default='pending', max_length=8),
        ),
    ]
