# Generated by Django 4.1.3 on 2024-01-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0235_alter_depositrecoveryrequest_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['account', 'asset', 'variant', 'market'], name='wallet_get_idx'),
        ),
    ]
