# Generated by Django 4.1.3 on 2024-01-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0235_alter_depositrecoveryrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coincategory',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
    ]
