# Generated by Django 4.1.3 on 2024-02-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0236_coincategory_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrecoveryrequest',
            name='status',
            field=models.CharField(choices=[('init', 'در حال بررسی'), ('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], db_index=True, default='process', max_length=8),
        ),
        migrations.AlterField(
            model_name='historicaltransfer',
            name='status',
            field=models.CharField(choices=[('init', 'در حال بررسی'), ('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='manualtrade',
            name='status',
            field=models.CharField(choices=[('init', 'در حال بررسی'), ('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='manualtransaction',
            name='status',
            field=models.CharField(choices=[('init', 'در حال بررسی'), ('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='tokenrebrand',
            name='status',
            field=models.CharField(choices=[('init', 'در حال بررسی'), ('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('init', 'در حال بررسی'), ('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], db_index=True, default='pending', max_length=8),
        ),
    ]
