# Generated by Django 4.1.3 on 2024-01-31 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0236_coincategory_meta_description'),
        ('ledger', '0236_wallet_wallet_get_idx'),
    ]

    operations = [
    ]
