# Generated by Django 4.1.3 on 2024-02-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0237_merge_20240131_1236'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wallet',
            name='wallet_get_idx',
        ),
    ]
