# Generated by Django 4.1.3 on 2024-02-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0237_alter_depositrecoveryrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrecoveryrequest',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='process', max_length=8),
        ),
        migrations.AlterField(
            model_name='historicaltransfer',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='manualtrade',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='manualtransaction',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='tokenrebrand',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8),
        ),
    ]
