# Generated by Django 4.1.3 on 2024-02-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0239_networkasset_max_allowed_daily_deposit_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkasset',
            name='can_withdraw',
            field=models.BooleanField(default=False),
        ),
    ]
