# Generated by Django 4.1.3 on 2024-03-03 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0239_networkasset_max_allowed_daily_deposit_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositrecoveryrequest',
            old_name='coin',
            new_name='asset',
        ),
        migrations.AddField(
            model_name='depositrecoveryrequest',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
