# Generated by Django 4.1.3 on 2024-03-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0240_alter_networkasset_can_withdraw'),
        ('ledger', '0240_rename_coin_depositrecoveryrequest_asset_and_more'),
    ]

    operations = [
    ]
