# Generated by Django 4.1.3 on 2024-03-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0241_merge_20240303_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkasset',
            name='hedger_deposit_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='networkasset',
            name='hedger_withdraw_enable',
            field=models.BooleanField(default=False),
        ),
    ]
