# Generated by Django 4.1.3 on 2024-03-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0242_alter_networkasset_hedger_deposit_enable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trx',
            name='scope',
            field=models.CharField(choices=[('t', 'trade'), ('f', 'transfer'), ('m', 'margin_transfer'), ('b', 'margin_borrow'), ('mi', 'margin_insurance'), ('in', 'margin_interest'), ('cm', 'close_margin'), ('fl', 'fast_liquid'), ('l', 'liquid'), ('c', 'fee'), ('p', 'prize'), ('r', 'revert'), ('ad', 'airdrop'), ('sz', 'seize'), ('rs', 'reserve'), ('sr', 'stake_revenue'), ('st', 'stake'), ('sf', 'stake_fee'), ('fx', 'fix'), ('dc', 'debt_clear'), ('du', 'dust'), ('mn', 'manual'), ('dl', 'delist'), ('rb', 'rebrand')], max_length=2),
        ),
    ]
