# Generated by Django 4.1.3 on 2024-04-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0243_alter_trx_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='trading_view_symbol',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
