# Generated by Django 4.1.3 on 2024-04-14 13:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0059_alter_order_time_in_force'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0187_historicalsystemconfig_market_maker_emergency_break_and_more'),
        ('ledger', '0244_asset_trading_view_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMarginPosition',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('group_id', models.UUIDField(default=uuid.uuid4)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('equity', models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_price', models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('liquidation_price', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('side', models.CharField(choices=[('long', 'long'), ('short', 'short')], max_length=8)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('terminating', 'terminating')], default='open', max_length=12)),
                ('leverage', models.PositiveSmallIntegerField()),
                ('alert_mode', models.BooleanField(db_index=True, default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account')),
                ('asset_wallet', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.wallet')),
                ('base_wallet', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.wallet')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('symbol', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='market.pairsymbol')),
            ],
            options={
                'verbose_name': 'historical margin position',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
