# Generated by Django 4.1.3 on 2024-05-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0245_historicalmarginposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkasset',
            name='update_with_provider',
            field=models.BooleanField(default=True),
        ),
    ]
