# Generated by Django 4.1.3 on 2024-05-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0246_networkasset_update_with_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='slow_withdraw',
        ),
    ]
