# Generated by Django 4.1.3 on 2024-05-26 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0247_remove_network_slow_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='rebranded_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.asset'),
        ),
    ]
