# Generated by Django 4.1.3 on 2024-05-26 07:05

from django.db import migrations


def populate_token_rebrand(apps, schema_editor):
    TokenRebrand = apps.get_model('ledger', 'TokenRebrand')

    for rebrand in TokenRebrand.objects.all():
        rebrand.old_asset.rebranded_to = rebrand.new_asset
        rebrand.old_asset.save(update_fields=['rebranded_to'])


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0248_asset_rebranded_to'),
    ]

    operations = [
        migrations.RunPython(
            code=populate_token_rebrand,
            reverse_code=migrations.RunPython.noop
        )
    ]
