# Generated by Django 4.1.3 on 2024-05-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0249_auto_20240526_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='whitelist',
            field=models.BooleanField(default=False),
        ),
    ]
