# Generated by Django 4.1.3 on 2024-06-09 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0249_auto_20240526_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenDelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8)),
                ('group_id', models.UUIDField(default=uuid.uuid4)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset')),
                ('testers', models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
