# Generated by Django 4.1.3 on 2024-05-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0250_addressbook_whitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransfer',
            name='whitelist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='whitelist',
            field=models.BooleanField(default=False),
        ),
    ]
