# Generated by Django 4.1.3 on 2024-06-09 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0250_tokendelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendelist',
            name='delist_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
