# Generated by Django 4.1.3 on 2024-06-09 07:48

from django.db import migrations, models


def populate_price_page(apps, schema_editor):
    Asset = apps.get_model('ledger', 'Asset')
    Asset.objects.filter(enable=True).update(price_page=True)


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0251_tokendelist_delist_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='price_page',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(
            code=populate_price_page,
            reverse_code=migrations.RunPython.noop
        ),
    ]
