# Generated by Django 4.1.3 on 2024-05-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0251_historicaltransfer_whitelist_transfer_whitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='memo',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
