# Generated by Django 4.1.3 on 2024-06-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0252_alter_asset_price_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='memo_name',
            field=models.CharField(default='memo', max_length=64),
        ),
        migrations.AddField(
            model_name='network',
            name='memo_name_fa',
            field=models.CharField(default='ممو', max_length=64),
        ),
        migrations.AddField(
            model_name='network',
            name='memo_title_fa',
            field=models.CharField(default='آدرس تگ یا ممو', max_length=64),
        ),
    ]
