# Generated by Django 4.1.3 on 2024-06-22 10:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0252_alter_asset_price_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualWithdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receiver_address', models.CharField(max_length=256)),
                ('coin', models.CharField(db_index=True, max_length=16)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('memo', models.CharField(blank=True, max_length=256)),
                ('comment', models.CharField(blank=True, max_length=256)),
                ('triggered', models.BooleanField(db_index=True, default=False)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.network')),
            ],
        ),
    ]
