# Generated by Django 4.1.3 on 2024-06-15 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0252_alter_asset_price_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coincategory',
            options={'ordering': ('order', 'id'), 'verbose_name': 'گروه\u200cبندی نمایش رمزارزها', 'verbose_name_plural': 'گروه\u200cبندی نمایش رمزارزها'},
        ),
        migrations.AddField(
            model_name='depositrecoveryrequest',
            name='block_link_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='depositrecoveryrequest',
            name='scope',
            field=models.CharField(choices=[('sys', 'sys'), ('user', 'user')], db_index=True, default='user', max_length=4),
        ),
        migrations.AlterField(
            model_name='depositrecoveryrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
