# Generated by Django 4.1.3 on 2024-06-24 11:33

from django.db import migrations, models
import django.db.models.deletion


def populate_assets(apps, sch):
    Asset = apps.get_model('ledger', 'Asset')
    ManualWithdraw = apps.get_model('ledger', 'ManualWithdraw')

    for mw in ManualWithdraw.objects.all():
        asset = Asset.objects.get(symbol=mw.coin)
        mw.asset = asset
        mw.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0253_manualwithdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualwithdraw',
            name='asset',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.asset'),
            preserve_default=False,
        ),
        migrations.RunPython(code=populate_assets, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='manualwithdraw',
            name='coin',
        ),
        migrations.AlterField(
            model_name='manualwithdraw',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset'),
            preserve_default=False,
        ),
    ]
