# Generated by Django 4.1.3 on 2024-06-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0253_alter_coincategory_options_and_more'),
        ('ledger', '0253_network_memo_name_network_memo_name_fa_and_more'),
    ]

    operations = [
    ]
