# Generated by Django 4.1.3 on 2024-06-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0254_merge_20240615_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositrecoveryrequest',
            old_name='block_link_id',
            new_name='blocklink_id',
        ),
    ]
