# Generated by Django 4.1.3 on 2024-06-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0255_rename_block_link_id_depositrecoveryrequest_blocklink_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkasset',
            name='network_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
