# Generated by Django 4.1.3 on 2024-06-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0256_networkasset_network_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositrecoveryrequest',
            options={'permissions': [('manage_deposit_recovery', 'Manage Deposit Recovery Request')]},
        ),
    ]
