# Generated by Django 4.1.3 on 2024-06-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0252_addressbook_memo'),
        ('ledger', '0258_historicaldepositrecoveryrequest'),
    ]

    operations = [
    ]
