# Generated by Django 4.1.3 on 2024-06-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0253_manualwithdraw'),
        ('ledger', '0258_historicaldepositrecoveryrequest'),
    ]

    operations = [
    ]
