# Generated by Django 4.1.3 on 2024-06-19 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0193_alter_historicalsystemconfig_dust_convert_threshold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0258_historicaldepositrecoveryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='memo',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='whitelist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltransfer',
            name='whitelist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='whitelist',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HistoricalAddressBook',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس')),
                ('deleted', models.BooleanField(default=False)),
                ('whitelist', models.BooleanField(default=False)),
                ('memo', models.CharField(blank=True, max_length=64)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account', verbose_name='حساب')),
                ('asset', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.asset', verbose_name='رمزارز')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('network', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.network', verbose_name='شبکه')),
            ],
            options={
                'verbose_name': 'historical دفترچه آدرس\u200cها',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
