# Generated by Django 4.1.3 on 2024-06-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0253_manualwithdraw'),
        ('ledger', '0259_addressbook_memo_addressbook_whitelist_and_more'),
    ]

    operations = [
    ]
