# Generated by Django 4.1.3 on 2024-06-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0260_merge_20240624_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualwithdraw',
            name='triggered',
        ),
        migrations.AddField(
            model_name='manualwithdraw',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='process', max_length=8),
        ),
        migrations.AlterField(
            model_name='manualwithdraw',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
