# Generated by Django 4.1.3 on 2024-06-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0260_merge_20240622_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='is_universal',
        ),
    ]
