# Generated by Django 4.1.3 on 2024-06-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0254_remove_manualwithdraw_coin_manualwithdraw_asset'),
        ('ledger', '0261_remove_network_is_universal'),
    ]

    operations = [
    ]
