# Generated by Django 4.1.3 on 2024-06-26 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0262_historicalmanualwithdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrecoveryrequest',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.asset'),
        ),
        migrations.AlterField(
            model_name='depositrecoveryrequest',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.network'),
        ),
        migrations.AlterField(
            model_name='depositrecoveryrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
