# Generated by Django 4.1.3 on 2024-06-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0262_merge_20240624_1553'),
        ('ledger', '0262_merge_20240624_1710'),
    ]

    operations = [
    ]
