# Generated by Django 4.1.3 on 2024-06-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0261_remove_network_is_universal'),
        ('ledger', '0263_alter_depositrecoveryrequest_asset_and_more'),
    ]

    operations = [
    ]
