# Generated by Django 4.1.3 on 2024-06-30 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0264_merge_20240629_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='otcrequest',
            name='gtd',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='trigger_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='type',
            field=models.CharField(choices=[('market', 'market'), ('limit', 'limit')], default='market', max_length=16),
        ),
    ]
