# Generated by Django 4.1.3 on 2024-06-30 14:12

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F
from django.db.models.functions import Lower


def populate_asset_names(apps, schema_editor):
    Asset = apps.get_model('ledger', 'Asset')
    Asset.objects.filter(name='').update(name=Lower('symbol'))


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0264_merge_20240629_1908'),
    ]

    operations = [
        migrations.RunPython(populate_asset_names, reverse_code=migrations.RunPython.noop),

        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='AssetVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ledger.asset')),
            ],
        ),
    ]
