# Generated by Django 4.1.3 on 2024-06-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0264_merge_20240629_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmanualwithdraw',
            name='trx_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='manualwithdraw',
            name='trx_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmanualwithdraw',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='init', max_length=8),
        ),
        migrations.AlterField(
            model_name='manualwithdraw',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='init', max_length=8),
        ),
    ]
