# Generated by Django 4.1.3 on 2024-07-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0265_alter_asset_name_assetvariant'),
        ('ledger', '0265_historicalmanualwithdraw_trx_hash_and_more'),
    ]

    operations = [
    ]
