# Generated by Django 4.1.3 on 2024-06-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0265_otcrequest_gtd_otcrequest_trigger_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otcrequest',
            name='gtd',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
