# Generated by Django 4.1.3 on 2024-07-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0266_alter_otcrequest_gtd'),
    ]

    operations = [
        migrations.AddField(
            model_name='otctrade',
            name='time_in_force',
            field=models.CharField(choices=[('GTD', 'GTD'), ('FOK', 'FOK')], default='FOK', max_length=6),
        ),
    ]
