# Generated by Django 4.1.3 on 2024-07-02 08:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0266_merge_20240701_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8)),
                ('group_id', models.UUIDField(default=uuid.uuid4)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenTransferPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_asset_multiplier', models.DecimalField(decimal_places=8, default=1, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('new_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers_new', to='ledger.asset')),
                ('old_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers_old', to='ledger.asset')),
                ('token_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='ledger.tokentransfer')),
            ],
        ),
    ]
