# Generated by Django 4.1.3 on 2024-07-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0267_otctrade_time_in_force'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otctrade',
            name='time_in_force',
        ),
    ]
