# Generated by Django 4.1.3 on 2024-07-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0268_alter_trx_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransfer',
            name='block_number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransfer',
            name='last_block_number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='block_number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='last_block_number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
