# Generated by Django 4.1.3 on 2024-07-03 13:16

from django.db import migrations, models


def populate_images(apps, schema_editor):
    DepositRecoveryRequest = apps.get_model('ledger', 'DepositRecoveryRequest')
    for d in DepositRecoveryRequest.objects.all():
        if d.image:
            d.images.add(d.image)


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0025_alter_coinpricecontent_options_and_more'),
        ('ledger', '0269_historicaltransfer_block_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrecoveryrequest',
            name='images',
            field=models.ManyToManyField(related_name='+', to='multimedia.image'),
        ),

        migrations.RunPython(code=populate_images, reverse_code=migrations.RunPython.noop),

        migrations.RemoveField(
            model_name='depositrecoveryrequest',
            name='image',
        ),
        migrations.RemoveField(
            model_name='historicaldepositrecoveryrequest',
            name='image',
        ),
    ]
