# Generated by Django 4.1.3 on 2024-07-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0270_remove_depositrecoveryrequest_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransfer',
            name='block_number',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransfer',
            name='last_block_number',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='block_number',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='last_block_number',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
