# Generated by Django 4.1.3 on 2024-07-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0271_alter_historicaltransfer_block_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrecoveryrequest',
            name='blocklink_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaldepositrecoveryrequest',
            name='blocklink_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
