# Generated by Django 4.1.3 on 2024-07-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0271_alter_historicaltransfer_block_number_and_more'),
        ('ledger', '0271_otcrequest_gtd_otcrequest_trigger_price_and_more'),
    ]

    operations = [
    ]
