# Generated by Django 4.1.3 on 2024-07-22 10:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0272_merge_20240720_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otctrade',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('canceled', 'canceled'), ('user_canceled', 'user_canceled'), ('done', 'done'), ('revert', 'revert'), ('expired', 'expired')], default='pending', max_length=16),
        ),
    ]
