# Generated by Django 4.1.3 on 2024-07-23 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0272_alter_depositrecoveryrequest_blocklink_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendelist',
            name='testers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tokenrebrand',
            name='testers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, to=settings.AUTH_USER_MODEL),
        ),
    ]
