# Generated by Django 4.1.3 on 2024-07-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0272_merge_20240720_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otcrequest',
            name='type',
            field=models.CharField(choices=[('limit', 'limit'), ('market', 'market')], default='market', max_length=16),
        ),
    ]
