# Generated by Django 4.1.3 on 2024-07-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0273_alter_otcrequest_type'),
        ('ledger', '0273_alter_tokendelist_testers_alter_tokenrebrand_testers'),
    ]

    operations = [
    ]
