# Generated by Django 4.1.3 on 2024-07-26 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0273_alter_otcrequest_type_alter_otctrade_status_dust_and_more'),
        ('ledger', '0274_merge_20240723_1100'),
    ]

    operations = [
    ]
