# Generated by Django 4.1.3 on 2024-07-24 12:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0274_merge_20240723_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNetworkAsset',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('withdraw_fee', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('withdraw_min', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('withdraw_max', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('withdraw_precision', models.PositiveSmallIntegerField()),
                ('hedger_withdraw_enable', models.BooleanField(default=False)),
                ('hedger_deposit_enable', models.BooleanField(default=False)),
                ('can_deposit', models.BooleanField(default=False)),
                ('can_withdraw', models.BooleanField(default=False)),
                ('allow_provider_withdraw', models.BooleanField(default=True)),
                ('update_fee_with_provider', models.BooleanField(default=True)),
                ('update_with_provider', models.BooleanField(default=True)),
                ('last_provider_update', models.DateTimeField(blank=True, null=True)),
                ('deposit_min', models.DecimalField(decimal_places=8, default=Decimal('1E-8'), max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('expected_hw_balance', models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_allowed_daily_deposit_value', models.PositiveIntegerField(blank=True, null=True)),
                ('network_order', models.PositiveSmallIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('asset', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.asset')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('network', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.network')),
            ],
            options={
                'verbose_name': 'historical network asset',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNetwork',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('can_withdraw', models.BooleanField(default=True)),
                ('can_deposit', models.BooleanField(default=False)),
                ('min_confirm', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('unlock_confirm', models.PositiveIntegerField(default=0)),
                ('explorer_link', models.CharField(blank=True, max_length=128)),
                ('address_regex', models.CharField(blank=True, max_length=128)),
                ('need_memo', models.BooleanField(default=False)),
                ('memo_title_fa', models.CharField(default='آدرس تگ یا ممو', max_length=64)),
                ('memo_name_fa', models.CharField(default='ممو', max_length=64)),
                ('memo_name', models.CharField(default='memo', max_length=64)),
                ('expected_confirmation_minutes', models.PositiveSmallIntegerField(default=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical network',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAsset',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('name_fa', models.CharField(blank=True, max_length=32)),
                ('original_name_fa', models.CharField(blank=True, max_length=32)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('original_symbol', models.CharField(blank=True, max_length=16)),
                ('trading_view_symbol', models.CharField(blank=True, max_length=32)),
                ('enable', models.BooleanField(default=False)),
                ('order', models.SmallIntegerField(db_index=True, default=0)),
                ('trend', models.BooleanField(default=False)),
                ('pin_to_top', models.BooleanField(default=False)),
                ('trade_enable', models.BooleanField(default=True)),
                ('hedge', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('otc_status', models.CharField(choices=[('active', 'active'), ('buy', 'buy'), ('sell', 'sell'), ('disabled', 'disabled')], default='active', max_length=8)),
                ('price_page', models.BooleanField(default=True)),
                ('price_alert_chanel_sensitivity', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('distribution_factor', models.FloatField(default=0)),
                ('stale_price', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('margin_interest_fee', models.DecimalField(decimal_places=8, default=Decimal('0.00015'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rebranded_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.asset')),
                ('spread_category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.assetspreadcategory')),
            ],
            options={
                'verbose_name': 'historical asset',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
