# Generated by Django 4.1.3 on 2024-07-24 11:39

from django.db import migrations, models
from ledger.models import MarginPosition as MP


def populate_init_position(apps, schz):
    MarginPosition = apps.get_model('ledger', 'MarginPosition')

    MarginPosition.objects.filter(status=MP.OPEN, liquidation_price__isnull=True).update(status=MP.INIT)


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0274_merge_20240723_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmarginposition',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('open', 'open'), ('closed', 'closed'), ('terminating', 'terminating')], default='init', max_length=12),
        ),
        migrations.AlterField(
            model_name='marginposition',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('open', 'open'), ('closed', 'closed'), ('terminating', 'terminating')], default='init', max_length=12),
        ),
        migrations.RunPython(populate_init_position, migrations.RunPython.noop)
    ]
