# Generated by Django 4.1.3 on 2024-07-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0275_alter_historicalmarginposition_status_and_more'),
        ('ledger', '0275_historicalnetworkasset_historicalnetwork_and_more'),
    ]

    operations = [
    ]
