# Generated by Django 4.1.3 on 2024-07-26 20:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0275_merge_20240726_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('converted_amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_dust_trx', to='ledger.wallet')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_dust_trx', to='ledger.wallet')),
            ],
        ),
        migrations.AddIndex(
            model_name='dust',
            index=models.Index(fields=['sender', 'created'], name='ledger_dust_sender_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='dust',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='check_ledger_dust_amount'),
        ),
        migrations.AlterUniqueTogether(
            name='dust',
            unique_together={('group_id', 'sender', 'receiver')},
        ),
    ]
