# Generated by Django 4.1.3 on 2024-07-28 12:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0277_alter_marginhistorymodel_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertDust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('converted_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset')),
            ],
        ),
        migrations.CreateModel(
            name='ConvertDustTrx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('converted_amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.asset')),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dust_asset', to='ledger.asset')),
                ('convert_dust', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convert_dust_trx', to='ledger.convertdust')),
            ],
        ),
        migrations.AddConstraint(
            model_name='convertdusttrx',
            constraint=models.CheckConstraint(check=models.Q(('converted_amount__gt', 0)), name='check_ledger_dust_trx_amount'),
        ),
        migrations.AddIndex(
            model_name='convertdust',
            index=models.Index(fields=['account', 'created'], name='ledger_dust_acc_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='convertdust',
            constraint=models.CheckConstraint(check=models.Q(('converted_amount__gt', 0)), name='check_ledger_dust_converted_amount'),
        ),
    ]
