# Generated by Django 4.1.3 on 2024-07-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0276_convertdust_convertdusttrx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertdust',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='convertdusttrx',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset'),
        ),
        migrations.AlterField(
            model_name='convertdusttrx',
            name='convert_dust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convert_dust_trx', to='ledger.convertdust'),
        ),
    ]
