# Generated by Django 4.1.3 on 2024-07-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0276_merge_20240724_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marginhistorymodel',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
    ]
