# Generated by Django 4.1.3 on 2024-08-04 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0277_alter_marginhistorymodel_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositaddress',
            options={'permissions': [('list_depositaddress', 'Can list deposit address')]},
        ),
        migrations.AlterModelOptions(
            name='otcrequest',
            options={'permissions': [('list_otcrequest', 'Can list otc request')]},
        ),
        migrations.AlterModelOptions(
            name='otctrade',
            options={'permissions': [('list_otctrade', 'Can list otc trade')]},
        ),
        migrations.AlterModelOptions(
            name='prize',
            options={'permissions': [('list_prize', 'Can list prize')]},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'permissions': [('list_transfer', 'Can list transfer')]},
        ),
        migrations.AlterModelOptions(
            name='trx',
            options={'permissions': [('list_trx', 'Can list trx')]},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'permissions': [('list_wallet', 'Can list wallet')]},
        ),
    ]
