# Generated by Django 4.1.3 on 2024-07-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0273_alter_otcrequest_type_alter_otctrade_status_dust_and_more'),
        ('ledger', '0278_auto_20240727_0009'),
    ]

    operations = [
    ]
