# Generated by Django 4.1.3 on 2024-08-05 10:30

from django.db import migrations, models
from django.db.models import F, Q


def populate_convert(apps, sch):
    Trx = apps.get_model('ledger', 'Trx')
    MarginHistoryModel = apps.get_model('ledger', 'MarginHistoryModel')

    _list = []
    for i in MarginHistoryModel.objects.filter(type='dust'):
        i.type = 'convert'
        i.asset = i.position.asset_wallet.asset
        _list.append(i)

    if _list:
        MarginHistoryModel.objects.bulk_update(_list, ['asset', 'type'])

    Trx.objects.filter(
        Q(sender__market='margin', sender__variant__isnull=False) |
        Q(receiver__market='margin', receiver__variant__isnull=False),
        scope='du'
    ).update(scope='mc')


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0278_alter_depositaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trx',
            name='scope',
            field=models.CharField(choices=[('t', 'trade'), ('f', 'transfer'), ('m', 'margin_transfer'), ('b', 'margin_borrow'), ('mi', 'margin_insurance'), ('in', 'margin_interest'), ('mc', 'margin_convert'), ('cm', 'close_margin'), ('fl', 'fast_liquid'), ('l', 'liquid'), ('c', 'fee'), ('p', 'prize'), ('r', 'revert'), ('ad', 'airdrop'), ('sz', 'seize'), ('rs', 'reserve'), ('sr', 'stake_revenue'), ('st', 'stake'), ('sf', 'stake_fee'), ('fx', 'fix'), ('dc', 'debt_clear'), ('du', 'dust'), ('mn', 'manual'), ('dl', 'delist'), ('rb', 'rebrand'), ('tt', 'token_transfer')], max_length=2),
        ),
        migrations.AlterField(
            model_name='marginhistorymodel',
            name='type',
            field=models.CharField(choices=[('pnl', 'pnl'), ('transfer', 'transfer'), ('trade_fee', 'trade_fee'), ('int_fee', 'int_fee'), ('ins_fee', 'ins_fee'), ('p_transfer', 'p_transfer'), ('dust', 'dust'), ('convert', 'convert')], max_length=12),
        ),
        migrations.RunPython(populate_convert, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='marginhistorymodel',
            name='type',
            field=models.CharField(choices=[('pnl', 'pnl'), ('transfer', 'transfer'), ('trade_fee', 'trade_fee'), ('int_fee', 'int_fee'), ('ins_fee', 'ins_fee'), ('p_transfer', 'p_transfer'), ('convert', 'convert')], max_length=12),
        ),
    ]
