# Generated by Django 4.1.3 on 2024-08-04 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0279_merge_20240729_1451'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='convertdust',
            name='check_ledger_dust_converted_amount',
        ),
        migrations.AlterField(
            model_name='convertdust',
            name='converted_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
