# Generated by Django 4.1.3 on 2024-08-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0279_alter_marginhistorymodel_type_alter_trx_scope'),
        ('ledger', '0280_remove_convertdust_check_ledger_dust_converted_amount_and_more'),
    ]

    operations = [
    ]
