# Generated by Django 4.1.3 on 2024-08-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0281_merge_20240806_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otcrequest',
            name='trigger_price',
        ),
    ]
