# Generated by Django 4.1.3 on 2024-08-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0282_remove_otcrequest_trigger_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalnetwork',
            old_name='need_memo',
            new_name='deposit_need_memo',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='need_memo',
            new_name='deposit_need_memo',
        ),
        migrations.AddField(
            model_name='historicalnetwork',
            name='withdraw_allow_memo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='network',
            name='withdraw_allow_memo',
            field=models.BooleanField(default=False),
        ),
    ]
