# Generated by Django 4.1.3 on 2024-08-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0282_remove_otcrequest_trigger_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convertdust',
            options={'ordering': ('-id',)},
        ),
    ]
