# Generated by Django 4.1.3 on 2024-08-10 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0283_alter_convertdust_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertdust',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='convertdusttrx',
            unique_together={('convert_dust', 'asset')},
        ),
    ]
