# Generated by Django 4.1.3 on 2024-08-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0283_rename_need_memo_historicalnetwork_deposit_need_memo_and_more'),
        ('ledger', '0284_alter_convertdust_group_id_and_more'),
    ]

    operations = [
    ]
