# Generated by Django 4.1.3 on 2024-08-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0284_alter_convertdust_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnetworkasset',
            name='withdraw_source',
            field=models.CharField(choices=[('self', 'self'), ('internal', 'internal'), ('provider', 'provider'), ('manual', 'manual')], default='self', max_length=8),
        ),
        migrations.AddField(
            model_name='networkasset',
            name='withdraw_source',
            field=models.CharField(choices=[('self', 'self'), ('internal', 'internal'), ('provider', 'provider'), ('manual', 'manual')], default='self', max_length=8),
        ),
    ]
