# Generated by Django 4.1.3 on 2024-08-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0285_historicalnetworkasset_source_networkasset_source'),
        ('ledger', '0285_merge_20240811_1316'),
    ]

    operations = [
    ]
