# Generated by Django 4.1.3 on 2024-08-12 11:52

from django.db import migrations
from django.db.models import F


def populate_network(apps, sch):
    Network = apps.get_model('ledger', 'Network')
    Network.objects.update(withdraw_allow_memo=F('deposit_need_memo'))


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0286_merge_20240812_1135'),
    ]

    operations = [
        migrations.RunPython(populate_network, migrations.RunPython.noop)
    ]
