# Generated by Django 4.1.3 on 2024-08-13 11:39

from django.db import migrations


def populate_address_key(apps, sch):
    AddressKey = apps.get_model('ledger', 'AddressKey')
    AddressKey.objects.filter(architecture='TON').update(deleted=True)


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0287_alter_networks_withdraw_memo_enable'),
    ]

    operations = [
        migrations.RunPython(populate_address_key, migrations.RunPython.noop)
    ]
