# Generated by Django 4.1.3 on 2024-09-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0288_alter_ton_infra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='trade_enable',
        ),
        migrations.RemoveField(
            model_name='historicalasset',
            name='trade_enable',
        ),
        migrations.AlterField(
            model_name='asset',
            name='otc_status',
            field=models.CharField(choices=[('active', 'active'), ('disabled', 'disabled'), ('buy', 'buy'), ('sell', 'sell'), ('soon', 'soon')], default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='otc_status',
            field=models.CharField(choices=[('active', 'active'), ('disabled', 'disabled'), ('buy', 'buy'), ('sell', 'sell'), ('soon', 'soon')], default='active', max_length=8),
        ),
    ]
