# Generated by Django 4.1.3 on 2024-08-18 14:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0139_auto_20240818_1726'),
        ('ledger', '0288_alter_ton_infra'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastbuytoken',
            name='process_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='fastbuytoken',
            name='otc_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.otcrequest'),
        ),
        migrations.AlterField(
            model_name='fastbuytoken',
            name='payment_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.paymentrequest'),
        ),
        migrations.AlterField(
            model_name='fastbuytoken',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('deposit', 'deposit'), ('done', 'done')], default='process', max_length=16),
        ),
    ]
