# Generated by Django 4.1.3 on 2024-09-11 14:32

from django.db import migrations, models
import multimedia.storage


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0289_remove_asset_trade_enable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=multimedia.storage.PublicMediaStorage(), upload_to='coins/logo/'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='logo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
