# Generated by Django 4.1.3 on 2024-09-11 14:32

from django.db import migrations, models
import multimedia.storage


def populate_asset_logos(apps, schema_editor):
    Asset = apps.get_model('ledger', 'Asset')
    for a in Asset.objects.all():
        a.logo = f'coins/logo/{a.symbol}.png'
        a.save(update_fields=['logo'])


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0289_remove_asset_trade_enable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=multimedia.storage.PublicMediaStorage(), upload_to='coins/logo/'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='logo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(
            code=populate_asset_logos,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='asset',
            name='otc_status',
            field=models.CharField(
                choices=[('active', 'active'), ('disabled', 'disabled'), ('buy', 'buy'), ('sell', 'sell'),
                         ('soon', 'soon')], default='soon', max_length=8),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='otc_status',
            field=models.CharField(
                choices=[('active', 'active'), ('disabled', 'disabled'), ('buy', 'buy'), ('sell', 'sell'),
                         ('soon', 'soon')], default='soon', max_length=8),
        ),
    ]
