# Generated by Django 4.1.3 on 2024-09-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0290_asset_logo_historicalasset_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='external_price_symbol',
            field=models.CharField(blank=True, max_length=16, db_index=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='external_price_symbol',
            field=models.CharField(blank=True, max_length=16, db_index=True),
        ),
    ]
