# Generated by Django 4.1.3 on 2024-09-18 06:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0290_pricechangealert'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetalert',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='alerttrigger',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='alerttrigger',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='alerttrigger',
            name='trigger_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='alerttrigger',
            name='type',
            field=models.CharField(blank=True, choices=[('gt', 'Greater Than'), ('gte', 'Greater Than or Equal To'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal To')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='assetalert',
            name='base_asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asset_alert_base_asset', to='ledger.asset'),
        ),
        migrations.DeleteModel(
            name='PriceChangeAlert',
        ),
    ]
