# Generated by Django 4.1.3 on 2024-09-25 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0290_asset_logo_historicalasset_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('disable_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.network')),
            ],
        ),
    ]
