# Generated by Django 4.1.3 on 2024-09-29 12:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0290_asset_logo_historicalasset_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_triggered', models.BooleanField(default=False)),
                ('trigger_price', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('gt', 'Greater Than'), ('lt', 'Less Than')], max_length=8)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deactive_reason', models.CharField(blank=True, choices=[('user', 'User'), ('trigger', 'Trigger')], max_length=8, null=True)),
                ('asset_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.assetalert')),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_alert_rule_base_asset', to='ledger.asset')),
            ],
        ),
    ]
