# Generated by Django 4.1.3 on 2024-09-22 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0291_alter_assetalert_unique_together_alerttrigger_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetalert',
            name='base_asset',
        ),
        migrations.AddField(
            model_name='alerttrigger',
            name='base_asset',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_alert_base_asset', to='ledger.asset'),
        ),
        migrations.AddField(
            model_name='alerttrigger',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
