# Generated by Django 4.1.3 on 2024-09-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0291_assetalertrule'),
        ('ledger', '0292_historicalnetworkschedule'),
    ]

    operations = [
    ]
