# Generated by Django 4.1.3 on 2024-09-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0290_asset_logo_historicalasset_logo'),
        ('ledger', '0292_remove_assetalert_base_asset_alerttrigger_base_asset_and_more'),
    ]

    operations = [
    ]
