# Generated by Django 4.1.3 on 2024-09-28 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0292_historicalnetworkschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='coincategory',
            name='_description_html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coincategory',
            name='description',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.CreateModel(
            name='HistoricalCoinCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('binance_name', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=32)),
                ('description', django_quill.fields.QuillField(blank=True)),
                ('_description_html', models.TextField(blank=True)),
                ('order', models.SmallIntegerField(db_index=True, default=0)),
                ('header', models.CharField(blank=True, max_length=128)),
                ('meta_description', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical گروه\u200cبندی نمایش رمزارزها',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
