# Generated by Django 4.1.3 on 2024-10-06 14:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0231_fcmtopicsubscription'),
        ('ledger', '0293_merge_20240929_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('login_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.loginactivity')),
                ('receiver_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_internal_transfers', to='ledger.wallet')),
                ('sender_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_internal_transfers', to='ledger.wallet')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalInternalTransfer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('login_activity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.loginactivity')),
                ('receiver_wallet', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.wallet')),
                ('sender_wallet', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.wallet')),
            ],
            options={
                'verbose_name': 'historical internal transfer',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
