# Generated by Django 4.1.3 on 2024-09-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0293_coincategory__description_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnetworkasset',
            name='contract',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='networkasset',
            name='contract',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
