# Generated by Django 4.1.3 on 2024-09-25 13:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0293_merge_20240925_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerttrigger',
            name='active',
        ),
        migrations.RemoveField(
            model_name='alerttrigger',
            name='base_asset',
        ),
        migrations.RemoveField(
            model_name='alerttrigger',
            name='description',
        ),
        migrations.RemoveField(
            model_name='alerttrigger',
            name='trigger_price',
        ),
        migrations.RemoveField(
            model_name='alerttrigger',
            name='type',
        ),
        migrations.RemoveField(
            model_name='alerttrigger',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='assetalert',
            unique_together={('user', 'asset')},
        ),
        migrations.CreateModel(
            name='AssetAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_triggered', models.BooleanField(default=False)),
                ('trigger_price', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('gt', 'Greater Than'), ('gte', 'Greater Than or Equal To'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal To')], max_length=8)),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.assetalert')),
            ],
        ),
    ]
