# Generated by Django 4.1.3 on 2024-09-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0294_remove_alerttrigger_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetalertrule',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='assetalertrule',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
    ]
