# Generated by Django 4.1.3 on 2024-10-01 06:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0294_historicalnetworkasset_contract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOTCTrade',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('canceled', 'canceled'), ('user_canceled', 'user_canceled'), ('done', 'done'), ('revert', 'revert'), ('expired', 'expired')], default='pending', max_length=16)),
                ('execution_type', models.CharField(choices=[('m', 'market'), ('p', 'provider')], max_length=1)),
                ('gap_revenue', models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('order_id', models.PositiveIntegerField(blank=True, null=True)),
                ('to_buy_amount', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('hedged', models.BooleanField(db_index=True, default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('otc_request', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.otcrequest')),
            ],
            options={
                'verbose_name': 'historical otc trade',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
