# Generated by Django 4.1.3 on 2024-10-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0295_historicalotctrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnetwork',
            name='memo_regex',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='network',
            name='memo_regex',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
