# Generated by Django 4.1.3 on 2024-09-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0295_rename_created_at_assetalertrule_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetalertrule',
            name='base_asset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='asset_alert_rule_base_asset', to='ledger.asset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetalertrule',
            name='deactive_reason',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('trigger', 'Trigger')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='assetalertrule',
            name='type',
            field=models.CharField(choices=[('gt', 'Greater Than'), ('lt', 'Less Than')], max_length=8),
        ),
    ]
