# Generated by Django 4.1.3 on 2024-10-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0293_merge_20240929_1635'),
        ('ledger', '0296_historicalnetwork_memo_regex_network_memo_regex'),
    ]

    operations = [
    ]
