# Generated by Django 4.1.3 on 2024-10-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0296_historicalnetwork_memo_regex_network_memo_regex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ('-pin_to_top', '-trend', 'otc_status', 'order')},
        ),
    ]
