# Generated by Django 4.1.3 on 2024-10-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0291_asset_external_price_symbol_and_more'),
        ('ledger', '0297_alter_asset_options'),
    ]

    operations = [
    ]
