# Generated by Django 4.1.3 on 2024-10-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0294_internaltransfer_historicalinternaltransfer_and_more'),
        ('ledger', '0297_merge_20241006_1829'),
    ]

    operations = [
    ]
