# Generated by Django 4.1.3 on 2024-10-15 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0298_merge_20241009_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnetworkasset',
            name='withdraw_source',
            field=models.CharField(choices=[('self', 'self'), ('internal', 'internal'), ('internal_account', 'internal_account'), ('provider', 'provider'), ('manual', 'manual')], default='self', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicaltransfer',
            name='source',
            field=models.CharField(choices=[('self', 'self'), ('internal', 'internal'), ('internal_account', 'internal_account'), ('provider', 'provider'), ('manual', 'manual')], default='self', max_length=16),
        ),
        migrations.AlterField(
            model_name='networkasset',
            name='withdraw_source',
            field=models.CharField(choices=[('self', 'self'), ('internal', 'internal'), ('internal_account', 'internal_account'), ('provider', 'provider'), ('manual', 'manual')], default='self', max_length=16),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.network'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='source',
            field=models.CharField(choices=[('self', 'self'), ('internal', 'internal'), ('internal_account', 'internal_account'), ('provider', 'provider'), ('manual', 'manual')], default='self', max_length=16),
        ),
    ]
