# Generated by Django 4.1.3 on 2024-10-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0298_merge_20241001_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalotctrade',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='otctrade',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
