# Generated by Django 4.1.3 on 2024-10-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0299_alter_historicalotctrade_created_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW ledger_transaction_history_view AS
            SELECT t.created, t.group_id, aa.user_id, t.status, r.side AS type, r.amount, a.symbol AS coin 
                FROM ledger_otctrade t JOIN ledger_otcrequest r ON t.otc_request_id = r.id JOIN accounts_account aa ON r.account_id = aa.id JOIN market_pairsymbol symbol ON r.symbol_id = symbol.id JOIN ledger_asset a ON symbol.asset_id = a.id
            
            UNION ALL
            SELECT created, group_id, user_id, status, 'fiat_deposit' AS side, amount, 'IRT' AS coin FROM financial_payment
            
            UNION ALL
            SELECT w.created, group_id, user_id, status, 'fiat_withdraw' AS side, amount, 'IRT' AS coin FROM financial_fiatwithdrawrequest w JOIN financial_bankaccount fb on w.bank_account_id = fb.id

            """,
            reverse_sql="DROP VIEW IF EXISTS ledger_transaction_history_view;"
        ),
    ]
