# Generated by Django 4.1.3 on 2024-10-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0299_alter_historicalnetworkasset_withdraw_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internaltransfer',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='internaltransfer',
            name='login_activity',
        ),
        migrations.RemoveField(
            model_name='internaltransfer',
            name='receiver_account',
        ),
        migrations.RemoveField(
            model_name='internaltransfer',
            name='sender_account',
        ),
        migrations.DeleteModel(
            name='HistoricalInternalTransfer',
        ),
        migrations.DeleteModel(
            name='InternalTransfer',
        ),
    ]
