# Generated by Django 4.1.3 on 2024-10-14 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ledger', '0300_auto_20241014_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('created', models.DateTimeField()),
                ('group_id', models.UUIDField(primary_key=True)),
                ('status', models.CharField(max_length=16)),
                ('type', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('coin', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'ledger_transaction_history_view',
                'managed': False,
            },
        ),
    ]
