# Generated by Django 4.1.3 on 2024-10-21 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0233_merge_20241006_1828'),
        ('ledger', '0300_remove_internaltransfer_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransfer',
            name='receiver_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='receiver_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
    ]
