# Generated by Django 4.1.3 on 2024-10-22 11:53

from django.db import migrations, models


def populate_receiver_account(apps, schema_editor):
    Transfer = apps.get_model('ledger', 'Transfer')
    DepositAddress = apps.get_model('ledger', 'DepositAddress')

    # internal_account_transfers = Transfer.objects.filter(
    #     source__in=['internal_account']
    # ).delete()

    transfers_query_set = Transfer.objects.filter(
        source__in=['internal'],
        receiver_account__isnull=True
    )

    transfers_to_update = []
    for transfer in transfers_query_set:
        transfer.receiver_account_id = DepositAddress.objects.filter(address=transfer.out_address).first().address_key.account_id
        transfers_to_update.append(transfer)

    if transfers_to_update:
        Transfer.objects.bulk_update(transfers_to_update, ['receiver_account_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0301_historicaltransfer_receiver_account_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=populate_receiver_account,
            reverse_code=migrations.RunPython.noop
        ),

    ]
