# Generated by Django 4.1.3 on 2024-10-19 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0301_transactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otctrade',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
