# Generated by Django 4.1.3 on 2024-10-22 11:53

from django.db import migrations, models


def populate_receiver_account(apps, schema_editor):
    Transfer = apps.get_model('ledger', 'Transfer')
    DepositAddress = apps.get_model('ledger', 'DepositAddress')

    # internal_account_transfers = Transfer.objects.filter(
    #     source__in=['internal_account']
    # ).delete()

    transfers_query_set = Transfer.objects.filter(
        source__in=['internal'],
        receiver_account__isnull=True
    )

    transfers_to_update = []
    for transfer in transfers_query_set:
        transfer.receiver_account_id = DepositAddress.objects.filter(address=transfer.out_address).first().address_key.account_id
        transfers_to_update.append(transfer)

    if transfers_to_update:
        Transfer.objects.bulk_update(transfers_to_update, ['receiver_account_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0301_historicaltransfer_receiver_account_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=populate_receiver_account,
            reverse_code=migrations.RunPython.noop
        ),

        migrations.AlterField(
            model_name='trx',
            name='scope',
            field=models.CharField(choices=[('t', 'trade'), ('f', 'transfer'), ('m', 'margin_transfer'), ('b', 'margin_borrow'), ('mi', 'margin_insurance'), ('in', 'margin_interest'), ('mc', 'margin_convert'), ('cm', 'close_margin'), ('fl', 'fast_liquid'), ('l', 'liquid'), ('c', 'fee'), ('p', 'prize'), ('r', 'revert'), ('ad', 'airdrop'), ('sz', 'seize'), ('rs', 'reserve'), ('sr', 'stake_revenue'), ('st', 'stake'), ('sf', 'stake_fee'), ('fx', 'fix'), ('dc', 'debt_clear'), ('du', 'dust'), ('mn', 'manual'), ('dl', 'delist'), ('rb', 'rebrand'), ('tt', 'token_transfer'), ('it', 'internal_transfer')], max_length=2),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(check=models.Q(('network__isnull', False), ('source', 'internal_account'), _connector='OR'), name='check_ledger_transfer_network_not_null'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(check=models.Q(('receiver_account__isnull', False), models.Q(('source__in', ['internal', 'internal_account']), _negated=True), _connector='OR'), name='c_check_ledger_transfer_receiver_account_not_null'),
        ),
    ]
