# Generated by Django 4.1.3 on 2024-10-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0297_alter_asset_options'),
        ('ledger', '0302_alter_trx_scope_and_more'),
    ]

    operations = [
    ]
