# Generated by Django 4.1.3 on 2024-10-23 11:45

from django.db import migrations
# Generated by Django 4.1.3 on 2024-10-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0297_alter_asset_options'),
        ('ledger', '0302_alter_trx_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trx',
            name='scope',
            field=models.CharField(
                choices=[('t', 'trade'), ('f', 'transfer'), ('m', 'margin_transfer'), ('b', 'margin_borrow'),
                         ('mi', 'margin_insurance'), ('in', 'margin_interest'), ('mc', 'margin_convert'),
                         ('cm', 'close_margin'), ('fl', 'fast_liquid'), ('l', 'liquid'), ('c', 'fee'), ('p', 'prize'),
                         ('r', 'revert'), ('ad', 'airdrop'), ('sz', 'seize'), ('rs', 'reserve'),
                         ('sr', 'stake_revenue'), ('st', 'stake'), ('sf', 'stake_fee'), ('fx', 'fix'),
                         ('dc', 'debt_clear'), ('du', 'dust'), ('mn', 'manual'), ('dl', 'delist'), ('rb', 'rebrand'),
                         ('tt', 'token_transfer'), ('it', 'internal_transfer')], max_length=2),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(
                check=models.Q(('network__isnull', False), ('source', 'internal_account'), _connector='OR'),
                name='check_ledger_transfer_network_not_null'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(check=models.Q(('receiver_account__isnull', False),
                                                             models.Q(('source__in', ['internal', 'internal_account']),
                                                                      _negated=True), _connector='OR'),
                                              name='check_ledger_transfer_receiver_account_not_null'),
        ),

    ]
