# Generated by Django 4.1.3 on 2024-10-23 06:13

from django.db import migrations

# def populate_receiver_account():
#     from ledger.models.deposit_address import DepositAddress
#     from ledger.models.transfer import Transfer

def populate_receiver_account(apps, schema_editor):
    Transfer = apps.get_model('ledger', 'Transfer')
    DepositAddress = apps.get_model('ledger', 'DepositAddress')

    transfers_query_set = Transfer.objects.filter(
        source='internal',
        receiver_account__isnull=True
    )

    total_transfers = transfers_query_set.count()
    batch_size = 1000
    total_batches = (total_transfers + batch_size - 1) // batch_size

    for batch_num in range(total_batches):
        start = batch_num * batch_size
        end = start + batch_size
        batch_transfers = list(transfers_query_set[start:end])

        transfers_to_update = []
        for transfer in batch_transfers:
                transfer.receiver_account_id = DepositAddress.objects.filter(address=transfer.out_address).first().address_key.account.id
                transfers_to_update.append(transfer)

        if transfers_to_update:
            Transfer.objects.bulk_update(transfers_to_update, ['receiver_account_id'])

        print(f'Processed batch {batch_num + 1} of {total_batches}')

class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0302_alter_trx_scope_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_receiver_account),
    ]
