# Generated by Django 4.1.3 on 2024-10-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0303_merge_20241023_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetalertrule',
            name='deactive_reason',
        ),
    ]
