# Generated by Django 4.1.3 on 2024-10-29 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0304_remove_assetalertrule_deactive_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
