# Generated by Django 4.1.3 on 2024-10-30 12:25

import django.core.validators
from django.db import migrations, models


def populate_default_price_alert(apps, schema_editor):
    Asset = apps.get_model('ledger', 'Asset')

    Asset.objects.filter(
        symbol__in=["USDT", "BTC", "ETH", "SHIB", "DOGE"]
    ).update(default_price_alert=True)


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0305_alter_assetalert_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alerttrigger',
            name='alert_trigger_idx',
        ),
        migrations.RemoveIndex(
            model_name='alerttrigger',
            name='chanel_change_alert_idx',
        ),
        migrations.RemoveIndex(
            model_name='alerttrigger',
            name='ledger_aler_asset_i_2e8e17_idx',
        ),
        migrations.RenameField(
            model_name='alerttrigger',
            old_name='price',
            new_name='new_price',
        ),
        migrations.RemoveField(
            model_name='alerttrigger',
            name='chanel',
        ),
        migrations.RemoveField(
            model_name='alerttrigger',
            name='change_percent',
        ),
        migrations.RemoveField(
            model_name='alerttrigger',
            name='is_chanel_changed',
        ),
        migrations.RemoveField(
            model_name='alerttrigger',
            name='is_triggered',
        ),
        migrations.AddField(
            model_name='alerttrigger',
            name='old_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerttrigger',
            name='trigger_type',
            field=models.CharField(choices=[('ratio', 'ratio'), ('channel', 'channel')], db_index=True, default='ratio', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='default_price_alert',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='default_price_alert',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='alerttrigger',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.RunPython(
            code=populate_default_price_alert,
            reverse_code=migrations.RunPython.noop
        ),
    ]
