# Generated by Django 4.1.3 on 2024-10-31 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0306_remove_alerttrigger_alert_trigger_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='price_alert_chanel_sensitivity',
            new_name='price_alert_channel_sensitivity',
        ),
        migrations.RenameField(
            model_name='historicalasset',
            old_name='price_alert_chanel_sensitivity',
            new_name='price_alert_channel_sensitivity',
        ),
    ]
