# Generated by Django 4.1.3 on 2024-11-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0307_rename_price_alert_chanel_sensitivity_asset_price_alert_channel_sensitivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttrigger',
            name='fcm_key',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
