# Generated by Django 4.1.3 on 2024-11-04 09:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


def populate_active(apps, schema_editor):
    AssetAlert = apps.get_model('ledger', 'AssetAlert')
    AssetAlert.objects.update(active=True)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0308_alerttrigger_fcm_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetalertrule',
            name='is_triggered',
        ),
        migrations.AddField(
            model_name='assetalert',
            name='active',
            field=models.BooleanField(db_index=True, default=False),
        ),

        migrations.RunPython(code=populate_active, reverse_code=migrations.RunPython.noop),

        migrations.AddField(
            model_name='assetalertrule',
            name='current_state',
            field=models.CharField(blank=True, choices=[('lt', 'کمتر از'), ('gt', 'بیشتر از')], max_length=8),
        ),
        migrations.AddField(
            model_name='assetalertrule',
            name='last_trigger_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetalertrule',
            name='asset_alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='ledger.assetalert'),
        ),
        migrations.AlterField(
            model_name='assetalertrule',
            name='type',
            field=models.CharField(choices=[('lt', 'کمتر از'), ('gt', 'بیشتر از')], max_length=8),
        ),
        migrations.CreateModel(
            name='HistoricalAssetAlertRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('trigger_price', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('lt', 'کمتر از'), ('gt', 'بیشتر از')], max_length=8)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('current_state', models.CharField(blank=True, choices=[('lt', 'کمتر از'), ('gt', 'بیشتر از')], max_length=8)),
                ('last_trigger_time', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('asset_alert', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.assetalert')),
                ('base_asset', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.asset')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical asset alert rule',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
