# Generated by Django 4.1.3 on 2024-11-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0309_remove_assetalertrule_is_triggered_assetalert_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetalertrule',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='assetalertrule',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalassetalertrule',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
    ]
