# Generated by Django 4.1.3 on 2024-11-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0310_alter_assetalertrule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetalertrule',
            options={'ordering': ('id',)},
        ),
    ]
