# Generated by Django 4.1.3 on 2024-11-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0311_alter_assetalertrule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetalertrule',
            name='base_asset',
            field=models.ForeignKey(limit_choices_to={'symbol__in': ['IRT', 'USDT']}, on_delete=django.db.models.deletion.CASCADE, related_name='base_asset_alert_rules', to='ledger.asset'),
        ),
        migrations.AlterField(
            model_name='historicalassetalertrule',
            name='base_asset',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'symbol__in': ['IRT', 'USDT']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.asset'),
        ),
    ]
