# Generated by Django 4.1.3 on 2024-11-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0312_alter_assetalertrule_base_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='max_otc_irt_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='max_otc_irt_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
