# Generated by Django 4.1.3 on 2024-11-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0313_asset_max_otc_irt_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalotctrade',
            name='reason',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='otctrade',
            name='reason',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
