# Generated by Django 4.1.3 on 2024-11-16 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0314_historicalotctrade_reason_otctrade_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=256, unique=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.network')),
            ],
        ),
    ]
