# Generated by Django 4.1.3 on 2024-11-27 09:16

from django.db import migrations, models
import ledger.models.token_delist


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0315_proxywallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendelist',
            name='delist_at',
            field=models.DateTimeField(default=ledger.models.token_delist.default_delist_at),
        ),
    ]
