# Generated by Django 4.1.3 on 2024-11-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0315_proxywallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxywallet',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
