# Generated by Django 4.1.3 on 2024-11-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0315_proxywallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('architecture', models.CharField(db_index=True, max_length=12)),
                ('address', models.CharField(max_length=256, unique=True)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
