# Generated by Django 4.1.3 on 2024-11-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0316_alter_tokendelist_delist_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'permissions': [('list_transfer', 'Can list transfer'), ('manage_transfers', 'Can manage transfers')]},
        ),
    ]
