# Generated by Django 4.1.3 on 2024-11-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0316_coldwallet'),
        ('ledger', '0316_proxywallet_comment'),
    ]

    operations = [
    ]
