# Generated by Django 4.1.3 on 2024-11-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0317_alter_transfer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnetwork',
            name='contract_link',
            field=models.URLField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='network',
            name='contract_link',
            field=models.URLField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='historicalnetwork',
            name='explorer_link',
            field=models.URLField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='network',
            name='explorer_link',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
