# Generated by Django 4.1.3 on 2024-11-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0317_alter_transfer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendelist',
            name='can_withdraw',
            field=models.BooleanField(default=True, help_text='Changes notification texts'),
        ),
    ]
