# Generated by Django 4.1.3 on 2024-11-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0317_alter_transfer_options'),
        ('ledger', '0318_historicalnetwork_contract_link_and_more'),
    ]

    operations = [
    ]
