# Generated by Django 4.1.3 on 2024-12-01 06:24

from django.db import migrations, models


def populate_do_care_hedge(apps, schema_editor):
    Asset = apps.get_model('ledger', 'Asset')
    Asset.objects.filter(symbol__in=['IRT', 'USDT']).update(do_care_hedge=False)


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0318_tokendelist_can_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='do_care_hedge',
            field=models.BooleanField(default=True, help_text='To be affected in hedge calculations'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='do_care_hedge',
            field=models.BooleanField(default=True, help_text='To be affected in hedge calculations'),
        ),
        migrations.RunPython(
            code=populate_do_care_hedge,
            reverse_code=migrations.RunPython.noop,
        )
    ]
