# Generated by Django 4.1.3 on 2024-12-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0319_asset_dont_care_hedge_and_more'),
        ('ledger', '0319_merge_20241130_1028'),
    ]

    operations = [
    ]
