# Generated by Django 4.1.3 on 2024-12-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0316_coldwallet'),
        ('ledger', '0318_historicalnetwork_contract_link_and_more'),
        ('ledger', '0319_asset_dont_care_hedge_and_more'),
    ]

    operations = [
    ]
