# Generated by Django 4.1.3 on 2024-12-21 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0320_merge_20241201_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^\\S+$', message='No whitespace allowed')]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='original_symbol',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\S+$', message='No whitespace allowed')]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(db_index=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\S+$', message='No whitespace allowed')]),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='name',
            field=models.CharField(db_index=True, max_length=32, validators=[django.core.validators.RegexValidator('^\\S+$', message='No whitespace allowed')]),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='original_symbol',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\S+$', message='No whitespace allowed')]),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='symbol',
            field=models.CharField(db_index=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\S+$', message='No whitespace allowed')]),
        ),
    ]
