# Generated by Django 4.1.3 on 2024-12-22 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0321_alter_asset_name_alter_asset_original_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset'),
        ),
        migrations.AlterField(
            model_name='networkasset',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.network'),
        ),
    ]
