# Generated by Django 4.1.3 on 2024-12-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0322_alter_networkasset_asset_alter_networkasset_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresskey',
            name='accept_deposits',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
