# Generated by Django 4.1.3 on 2024-12-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0323_addresskey_accept_deposits'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='depositaddress',
            unique_together={('address_key', 'network')},
        ),
    ]
