# Generated by Django 4.1.3 on 2025-01-01 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0324_alter_depositaddress_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='dest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='صاحب آدرس'),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='type',
            field=models.CharField(choices=[('internal', 'internal'), ('external', 'external')], default='external', max_length=8),
        ),
        migrations.AddField(
            model_name='historicaladdressbook',
            name='dest_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='صاحب آدرس'),
        ),
        migrations.AddField(
            model_name='historicaladdressbook',
            name='type',
            field=models.CharField(choices=[('internal', 'internal'), ('external', 'external')], default='external', max_length=8),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.network', verbose_name='شبکه'),
        ),
        migrations.AlterField(
            model_name='historicaladdressbook',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='آدرس'),
        ),
    ]
