# Generated by Django 4.1.3 on 2025-01-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0325_addressbook_dest_user_and_more'),
        ('ledger', '0325_alter_reservewallet_group_id_and_more'),
    ]

    operations = [
    ]
