# Generated by Django 4.1.3 on 2025-01-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0302_alter_otctrade_group_id'),
        ('ledger', '0325_alter_reservewallet_group_id_and_more'),
    ]

    operations = [
    ]
