# Generated by Django 4.1.3 on 2025-01-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0326_merge_20250107_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositrecoveryrequest',
            options={'permissions': [('manage_deposit_recovery', 'Can manage deposit recovery request')]},
        ),
    ]
