# Generated by Django 4.1.3 on 2025-01-04 13:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def transfer_data_to_address_book(apps, schema_editor):
    ManualWithdraw = apps.get_model('ledger', 'ManualWithdraw')
    ManualAddressBook = apps.get_model('ledger', 'ManualAddressBook')

    for withdraw in ManualWithdraw.objects.all():
        address_book = ManualAddressBook.objects.get_or_create(
            address=withdraw.receiver_address,
            defaults={
                'name': f"For Network {withdraw.network}",
                'memo': withdraw.memo,
                'network': withdraw.network,
            }
        )

        withdraw.address_book = address_book
        withdraw.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0327_alter_depositrecoveryrequest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('address', models.CharField(max_length=256, verbose_name='آدرس')),
                ('memo', models.CharField(blank=True, max_length=256)),
                ('deleted', models.BooleanField(default=False)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.network',
                                              verbose_name='شبکه')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalManualAddressBook',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('address', models.CharField(max_length=256, verbose_name='آدرس')),
                ('memo', models.CharField(blank=True, max_length=256)),
                ('deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('network', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                              on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                              to='ledger.network', verbose_name='شبکه')),
            ],
            options={
                'verbose_name': 'historical manual address book',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalmanualwithdraw',
            name='address_book',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='ledger.manualaddressbook'),
        ),
        migrations.AddField(
            model_name='manualwithdraw',
            name='address_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='ledger.manualaddressbook'),
            preserve_default=False,
        ),
        migrations.RunPython(transfer_data_to_address_book),
        migrations.RemoveField(
            model_name='historicalmanualwithdraw',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='historicalmanualwithdraw',
            name='network',
        ),
        migrations.RemoveField(
            model_name='historicalmanualwithdraw',
            name='receiver_address',
        ),
        migrations.RemoveField(
            model_name='manualwithdraw',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='manualwithdraw',
            name='network',
        ),
        migrations.RemoveField(
            model_name='manualwithdraw',
            name='receiver_address',
        ),
    ]
