# Generated by Django 4.1.3 on 2025-01-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0326_merge_20250106_1540'),
        ('ledger', '0327_alter_depositrecoveryrequest_options'),
    ]

    operations = [
    ]
