# Generated by Django 4.1.3 on 2025-01-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0328_merge_20250111_1106'),
        ('ledger', '0328_remove_historicalmanualwithdraw_memo_and_more'),
    ]

    operations = [
    ]
