# Generated by Django 4.1.3 on 2025-01-21 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ledger', '0329_merge_20250121_1229'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
               CREATE OR REPLACE VIEW ledger_transaction_history_view AS
               SELECT t.created, t.group_id, aa.user_id, t.status, r.side AS type, r.amount, a.symbol AS coin, r.fee_amount as fee
                   FROM ledger_otctrade t 
                   JOIN ledger_otcrequest r ON t.otc_request_id = r.id 
                   JOIN accounts_account aa ON r.account_id = aa.id 
                   JOIN market_pairsymbol symbol ON r.symbol_id = symbol.id 
                   JOIN ledger_asset a ON symbol.asset_id = a.id

               UNION ALL
               SELECT created, group_id, user_id, status, 'fiat_deposit' AS side, amount, 'IRT' AS coin, fee
               FROM financial_payment

               UNION ALL
               SELECT w.created, group_id, user_id, status, 'fiat_withdraw' AS side, amount, 'IRT' AS coin, w.fee_amount as fee
               FROM financial_fiatwithdrawrequest w 
               JOIN financial_bankaccount fb on w.bank_account_id = fb.id
               """,
            reverse_sql="""
               CREATE OR REPLACE VIEW ledger_transaction_history_view AS
               SELECT t.created, t.group_id, aa.user_id, t.status, r.side AS type, r.amount, a.symbol AS coin 
                   FROM ledger_otctrade t 
                   JOIN ledger_otcrequest r ON t.otc_request_id = r.id 
                   JOIN accounts_account aa ON r.account_id = aa.id 
                   JOIN market_pairsymbol symbol ON r.symbol_id = symbol.id 
                   JOIN ledger_asset a ON symbol.asset_id = a.id

               UNION ALL
               SELECT created, group_id, user_id, status, 'fiat_deposit' AS side, amount, 'IRT' AS coin 
               FROM financial_payment

               UNION ALL
               SELECT w.created, group_id, user_id, status, 'fiat_withdraw' AS side, amount, 'IRT' AS coin 
               FROM financial_fiatwithdrawrequest w 
               JOIN financial_bankaccount fb on w.bank_account_id = fb.id;
               """
        ),
    ]
