# Generated by Django 4.1.3 on 2025-10-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0330_add_fee_to_transaction_history_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsnapshot',
            name='margin_insurance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
    ]
