# Generated by Django 4.1.3 on 2025-02-01 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multimedia.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(storage=multimedia.storage.PublicMediaStorage(), upload_to='highlights/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(storage=multimedia.storage.PublicMediaStorage(), upload_to='stories/')),
                ('text', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Determines the order of this story within the highlight.')),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='engage.highlight')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='engage.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='storyview',
            index=models.Index(fields=['user', 'story'], name='engage_stor_user_id_96b984_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storyview',
            unique_together={('user', 'story')},
        ),
    ]
