# Generated by Django 4.1.3 on 2025-02-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['order'], 'verbose_name_plural': 'Stories'},
        ),
    ]
