# Generated by Django 4.0 on 2022-09-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='')),
                ('link', models.URLField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
