# Generated by Django 4.1.3 on 2022-12-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0004_alter_banner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='app_link',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
