# Generated by Django 4.1.3 on 2023-02-13 08:13

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0167_alter_otcrequest_symbol'),
        ('multimedia', '0005_banner_app_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPriceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ledger.asset')),
            ],
        ),
    ]
