# Generated by Django 4.1.3 on 2023-03-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0006_coinpricecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='limit',
            field=models.CharField(blank=True, choices=[('only_desktop', 'only_desktop')], max_length=16),
        ),
    ]
