# Generated by Django 4.1.3 on 2023-10-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0009_baseitem_section_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقاله\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'بخش', 'verbose_name_plural': 'بخش\u200c\u200cها'},
        ),
    ]
