# Generated by Django 4.1.3 on 2023-10-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0010_alter_article_options_alter_section_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitem',
            name='slug',
            field=models.SlugField(editable=False, max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='title',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='title_en',
            field=models.TextField(max_length=256),
        ),
    ]
