# Generated by Django 4.1.3 on 2023-10-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0011_alter_baseitem_slug_alter_baseitem_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('order', 'id'), 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقاله\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('order', 'id'), 'verbose_name': 'بخش', 'verbose_name_plural': 'بخش\u200c\u200cها'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='parent_section',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
