# Generated by Django 4.1.3 on 2023-10-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0012_alter_article_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitem',
            name='slug',
            field=models.SlugField(max_length=1024, unique=True),
        ),
    ]
