# Generated by Django 4.1.3 on 2023-10-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0013_alter_baseitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=1024, unique=True),
        ),
    ]
