# Generated by Django 4.1.3 on 2023-10-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0014_alter_baseitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='icon',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
