# Generated by Django 4.1.3 on 2023-10-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0015_section_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='icon',
            field=models.CharField(blank=True, choices=[('getting-started', 'getting-started'), ('signup', 'signup'), ('accounts', 'accounts'), ('transfer', 'transfer'), ('trade', 'trade'), ('earn', 'earn')], max_length=256),
        ),
    ]
