# Generated by Django 4.1.3 on 2023-10-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0016_alter_section_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section'
        ),
        migrations.DeleteModel(
            name='Article'
        ),
        migrations.DeleteModel(
            name='BaseItem',
        ),
    ]
