# Generated by Django 4.1.3 on 2023-10-23 15:39

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0019_article__content_html_article__content_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
