# Generated by Django 4.1.3 on 2023-10-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0020_alter_article_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('parent', 'order', 'id'), 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقاله\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('-parent', 'order', 'id'), 'verbose_name': 'بخش', 'verbose_name_plural': 'بخش\u200c\u200cها'},
        ),
    ]
