# Generated by Django 4.1.3 on 2023-10-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0021_alter_article_options_alter_section_options'),
        ('multimedia', '0021_file'),
    ]

    operations = [
    ]
