# Generated by Django 4.1.3 on 2023-10-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0022_merge_20231030_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('order', 'id'), 'verbose_name': 'بخش', 'verbose_name_plural': 'بخش\u200c\u200cها'},
        ),
    ]
