# Generated by Django 4.1.3 on 2024-01-01 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multimedia', '0024_file_created_image_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinpricecontent',
            options={'verbose_name': 'توضیحات کوین', 'verbose_name_plural': 'توضیحات کوین\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='historicalcoinpricecontent',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical توضیحات کوین'},
        ),
        migrations.CreateModel(
            name='HistoricalSection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
                ('title_en', models.TextField(max_length=256)),
                ('slug', models.SlugField(blank=True, max_length=1024)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('icon', models.CharField(blank=True, choices=[('getting-started', 'getting-started'), ('signup', 'signup'), ('accounts', 'accounts'), ('transfer', 'transfer'), ('trade', 'trade'), ('earn', 'earn')], max_length=256)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='multimedia.section')),
            ],
            options={
                'verbose_name': 'historical بخش',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalArticle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
                ('title_en', models.TextField(max_length=256)),
                ('slug', models.SlugField(blank=True, max_length=1024)),
                ('is_pinned', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('content', django_quill.fields.QuillField(blank=True)),
                ('_content_html', models.TextField(blank=True)),
                ('_content_text', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='multimedia.section')),
            ],
            options={
                'verbose_name': 'historical مقاله',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
