# Generated by Django 4.1.3 on 2024-08-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0026_guidegroup_historicalguidegroup_historicalguide_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ('order', 'id'), 'verbose_name': 'راهنما', 'verbose_name_plural': 'راهنما\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='guidegroup',
            options={'verbose_name': 'دسته راهنما', 'verbose_name_plural': 'دسته راهنما\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='historicalguide',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical راهنما'},
        ),
        migrations.AlterModelOptions(
            name='historicalguidegroup',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical دسته راهنما'},
        ),
    ]
