# Generated by Django 4.1.3 on 2024-09-10 14:24

from django.db import migrations, models
import multimedia.storage


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0027_alter_guide_options_alter_guidegroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=multimedia.storage.PublicMediaStorage(), upload_to='multimedia/guide/'),
        ),
    ]
