# Generated by Django 4.1.3 on 2024-09-10 14:27

from django.db import migrations, models
import multimedia.storage


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0028_alter_guide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(storage=multimedia.storage.PublicMediaStorage(), upload_to=''),
        ),
    ]
