# Generated by Django 4.1.3 on 2024-09-11 14:25

from django.db import migrations, models
import multimedia.storage


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0029_alter_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=64)),
                ('video', models.FileField(storage=multimedia.storage.PublicMediaStorage(), upload_to='videos/')),
            ],
        ),
    ]
