# Generated by Django 4.1.3 on 2024-10-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0031_faqcategory_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcategory',
            name='slug',
            field=models.SlugField(default='', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
