# Generated by Django 4.1.3 on 2024-10-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0032_faqcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='type',
            field=models.CharField(choices=[('link', 'link'), ('qa', 'qa')], default='qa', max_length=4),
        ),
    ]
