# Generated by Django 4.1.3 on 2024-10-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0033_faq_link_faq_title_faq_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='type',
            field=models.CharField(choices=[('link', 'link'), ('qa', 'qa')], max_length=4),
        ),
    ]
