# Generated by Django 4.1.3 on 2024-10-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0034_alter_faq_answer_text_alter_faq_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='type',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='type',
            field=models.CharField(choices=[('link', 'Link'), ('qa', 'qa')], default='qa', max_length=4),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
