# Generated by Django 4.1.3 on 2024-10-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0035_remove_faq_answer_text_remove_faq_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategory',
            name='type',
            field=models.CharField(choices=[('link', 'Link'), ('qa', 'QA')], default='qa', max_length=4),
        ),
    ]
