# Generated by Django 4.1.3 on 2025-01-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0036_alter_faqcategory_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
