# Generated by Django 4.1.3 on 2025-01-06 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


def populate_variants(apps, schema_editor):
    GuideGroup = apps.get_model('multimedia', 'GuideGroup')
    GuideVariant = apps.get_model('multimedia', 'GuideVariant')
    Guide = apps.get_model('multimedia', 'Guide')

    for group in GuideGroup.objects.all():
        variant = GuideVariant.objects.create(
            title='پیش فرض',
            slug='default',
            group=group,
        )
        Guide.objects.filter(group=group).update(variant=variant)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multimedia', '0037_alter_faq_options_faq_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalGuideVariant',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256, blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='multimedia.guidegroup')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical گونه راهنما',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GuideVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256, blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='multimedia.guidegroup')),
            ],
            options={
                'verbose_name': 'گونه راهنما',
                'verbose_name_plural': 'گونه راهنما\u200cها',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='guide',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='multimedia.guidevariant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalguide',
            name='variant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='multimedia.guidevariant'),
        ),

        migrations.RunPython(
            code=populate_variants,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='guide',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides',
                                    to='multimedia.guidevariant'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='guide',
            name='group',
        ),
        migrations.RemoveField(
            model_name='historicalguide',
            name='group',
        ),
        migrations.AddField(
            model_name='guidegroup',
            name='type',
            field=models.CharField(choices=[('edu', 'آموزشی'), ('fast', 'تصویر محور')], default='edu', max_length=8),
        ),
        migrations.AddField(
            model_name='historicalguidegroup',
            name='type',
            field=models.CharField(choices=[('edu', 'آموزشی'), ('fast', 'تصویر محور')], default='edu', max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='guidevariant',
            unique_together={('group', 'slug')},
        ),
    ]
