# Generated by Django 4.1.3 on 2025-01-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0038_remove_guide_group_remove_historicalguide_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidevariant',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalguidevariant',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
