# Generated by Django 4.1.3 on 2025-01-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0038_remove_guide_group_remove_historicalguide_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidevariant',
            name='slug',
            field=models.SlugField(default='default', max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalguidevariant',
            name='slug',
            field=models.SlugField(default='default', max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='guidevariant',
            unique_together={('group', 'slug')},
        ),
    ]
