# Generated by Django 4.0 on 2022-03-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('depth', 'depth'), (None, 'ordinary')], max_length=8, null=True),
        ),
    ]
