# Generated by Django 4.0 on 2022-03-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_order_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_order_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
