# Generated by Django 4.0 on 2022-03-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0066_balancelock_check_amount'),
        ('market', '0003_alter_order_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pairsymbol',
            unique_together={('asset', 'base_asset')},
        ),
    ]
