# Generated by Django 4.0 on 2022-03-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_create_fill_order_for_existing_otc_trades'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fillorder',
            index=models.Index(fields=['created', 'symbol'], name='market_fill_created_ce1544_idx'),
        ),
    ]
