# Generated by Django 4.0 on 2022-03-13 09:23

from django.db import migrations


def set_maker_quantities(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('market', '0007_fillorder_market_fill_created_ce1544_idx'),
    ]

    operations = [
        migrations.RunPython(
            code=set_maker_quantities, reverse_code=migrations.RunPython.noop
        ),
    ]
