# Generated by Django 4.0 on 2022-04-13 12:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_referral_account_referred_by'),
        ('market', '0008_set_maker_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralTrx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('referrer_amount', models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)])),
                ('trader_amount', models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)])),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.referral')),
            ],
        ),
    ]
