# Generated by Django 4.0 on 2022-04-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_fillorder_irt_value'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['symbol', 'status'], name='market_orde_symbol__4fd1e4_idx'),
        ),
    ]
