# Generated by Django 4.0 on 2022-04-16 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_account_referred_by'),
        ('market', '0009_referraltrx'),
    ]

    operations = [
        migrations.AddField(
            model_name='referraltrx',
            name='trader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
            preserve_default=False,
        ),
    ]
