# Generated by Django 4.0 on 2022-04-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_fillorder_irt_value'),
        ('market', '0010_referraltrx_trader'),
    ]

    operations = [
    ]
