# Generated by Django 4.0 on 2022-04-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_order_market_orde_symbol__4fd1e4_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status', 'new')), fields=['price'], name='market_new_orders_price_idx'),
        ),
    ]
