# Generated by Django 4.0 on 2022-04-18 12:49
from decimal import Decimal

import django.core.validators
from django.db import migrations, models, transaction
from django.db.models import Sum

from ledger.utils.precision import floor_precision


def populate_filled_amount(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_fillorder_trade_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='filled_amount',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=40, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=populate_filled_amount, reverse_code=migrations.RunPython.noop
        )
    ]
