# Generated by Django 4.0 on 2022-04-18 14:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_order_filled_amount_alter_fillorder_trade_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='filled_amount',
            field=models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=40, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
