# Generated by Django 4.0 on 2022-04-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_merge_20220416_1829'),
        ('market', '0015_alter_order_managers_alter_fillorder_trade_source'),
    ]

    operations = [
    ]
