# Generated by Django 4.0 on 2022-04-30 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0076_alter_marginloan_lock_alter_margintransfer_lock_and_more'),
        ('market', '0016_merge_20220419_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lock',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_order', to='ledger.balancelock'),
        ),
    ]
