# Generated by Django 4.0 on 2022-05-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_alter_order_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairsymbol',
            name='taker_fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=9),
        ),
    ]
