# Generated by Django 4.0 on 2022-05-21 12:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0084_alter_coincategory_options_prize_redeemed'),
        ('market', '0018_alter_pairsymbol_taker_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)])),
                ('filled_amount', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=40, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)])),
                ('side', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=8)),
                ('completed', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('lock', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_stop_loss', to='ledger.balancelock')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.pairsymbol')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stop_losses', to='ledger.wallet')),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='stop_loss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.stoploss'),
        ),
    ]
