# Generated by Django 4.0 on 2022-05-23 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_stoploss_order_stop_loss'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stoploss',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='stoploss',
            name='completed',
        ),
    ]
