# Generated by Django 4.0 on 2022-05-31 09:28

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_alter_stoploss_managers_remove_stoploss_completed'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('filled_amount__lte', django.db.models.expressions.F('amount'))), name='check_filled_amount'),
        ),
    ]
