# Generated by Django 4.0 on 2022-06-08 12:38

from django.db import migrations, models


def populate_trades(apps, schema_editor):
    FillOrder = apps.get_model('market', 'FillOrder')
    Trade = apps.get_model('market', 'Trade')

    trades = []
    for fill_order in FillOrder.objects.all():
        trades.append(
            Trade(
                created=fill_order.created,
                symbol=fill_order.symbol,
                order=fill_order.maker_order,
                account=fill_order.maker_order.wallet.account,
                side=fill_order.maker_order.side,
                is_maker=True,
                trade_source=fill_order.trade_source,
                amount=fill_order.amount,
                price=fill_order.price,
                irt_value=fill_order.irt_value,
                group_id=fill_order.group_id,
                base_amount=fill_order.base_amount,
                fee_amount=fill_order.maker_fee_amount,
            )
        )
        trades.append(
            Trade(
                created=fill_order.created,
                symbol=fill_order.symbol,
                order=fill_order.taker_order,
                account=fill_order.taker_order.wallet.account,
                side=fill_order.taker_order.side,
                is_maker=False,
                trade_source=fill_order.trade_source,
                amount=fill_order.amount,
                price=fill_order.price,
                irt_value=fill_order.irt_value,
                group_id=fill_order.group_id,
                base_amount=fill_order.base_amount,
                fee_amount=fill_order.taker_fee_amount,
            )
        )
    Trade.objects.bulk_create(trades)


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_trade_trade_market_trad_account_ac402e_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_trades, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='trade',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
