# Generated by Django 4.0 on 2022-06-20 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_populate_order_group_id'),
        ('ledger', '0098_remove_trx_check_ledger_trx_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='lock',
        ),
        migrations.RemoveField(
            model_name='stoploss',
            name='lock',
        ),
        migrations.AddField(
            model_name='stoploss',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
