# Generated by Django 4.0 on 2022-06-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_alter_fillorder_amount_alter_fillorder_base_amount_and_more'),
        ('market', '0023_populate_trades'),
    ]

    operations = [
    ]
