# Generated by Django 4.0 on 2022-06-22 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_remove_order_lock_remove_stoploss_lock_and_more'),
        ('market', '0025_remove_fillorder_maker_order_remove_fillorder_symbol_and_more'),
    ]

    operations = [
    ]
