# Generated by Django 4.0 on 2022-07-02 10:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0027_delete_fillorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='gap_revenue',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='trade',
            name='hedge_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_source',
            field=models.CharField(choices=[('otc', 'otc'), ('market', 'market'), ('system', 'system'), ('sys-make', 'sys-make'), ('sys-take', 'sys-take')], db_index=True, default='market', max_length=8),
        ),
    ]
