# Generated by Django 4.0 on 2022-07-03 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0028_trade_gap_revenue_trade_hedge_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoploss',
            name='fill_type',
            field=models.CharField(choices=[('limit', 'limit'), ('market', 'market')], default='market', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoploss',
            name='trigger_price',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stoploss',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
