# Generated by Django 4.0 on 2022-07-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0029_stoploss_fill_type_stoploss_trigger_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('depth', 'depth'), ('bot', 'bot'), (None, 'ordinary')], max_length=8, null=True),
        ),
    ]
