# Generated by Django 4.0 on 2022-09-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0031_alter_pairsymbol_taker_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairsymbol',
            name='strategy_enable',
            field=models.BooleanField(default=False),
        ),
    ]
