# Generated by Django 4.0 on 2022-10-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0032_pairsymbol_strategy_enable'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['created'], name='market_trad_created_b8defd_idx'),
        ),
    ]
