# Generated by Django 4.1.3 on 2023-01-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0033_trade_market_trad_created_b8defd_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('d', 'done'), ('r', 'revert')], db_index=True, default='d', max_length=1),
        ),
    ]
