# Generated by Django 4.1.3 on 2023-01-21 12:50
from decimal import Decimal

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0035_alter_trade_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelrequest',
            name='order',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.RenameField(
            model_name='cancelrequest',
            old_name='order',
            new_name='order_id',
        ),

        migrations.AlterField(
            model_name='trade',
            name='order',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='order',
            new_name='order_id',
        ),

        migrations.AddField(
            model_name='trade',
            name='base_irt_price',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='market',
            field=models.CharField(choices=[('spot', 'spot'), ('margin', 'margin'), ('loan', 'loan'), ('stake', 'stake'), ('voucher', 'voucher'), ('debt', 'debt')], default='spot', max_length=8),
            preserve_default=False,
        ),
        migrations.RemoveConstraint(
            model_name='trade',
            name='check_market_trade_amounts',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='base_amount',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='irt_value',
        ),
        migrations.AddField(
            model_name='trade',
            name='base_usdt_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.CheckConstraint(
                check=models.Q(('amount__gte', 0), ('fee_amount__gte', 0), ('price__gte', 0)),
                name='check_market_trade_amounts'),
        ),
    ]
