# Generated by Django 4.1.3 on 2023-01-26 11:34

from django.db import migrations, models
from django.db.models import Max


def populate_last_trade_time(apps, schema_editor):
    PairSymbol = apps.get_model('market', 'PairSymbol')
    Trade = apps.get_model('market', 'Trade')

    trades_map = dict(Trade.objects.values('symbol').annotate(last=Max('created')).values_list('symbol', 'last'))
    for p in PairSymbol.objects.filter(enable=True):
        p.last_trade_time = trades_map.get(p.id)
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0038_alter_trade_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairsymbol',
            name='last_trade_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(populate_last_trade_time, migrations.RunPython.noop)
    ]
