# Generated by Django 4.1.3 on 2023-01-26 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0039_pairsymbol_last_trade_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairsymbol',
            name='last_trade_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
