# Generated by Django 4.1.3 on 2023-02-08 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0040_pairsymbol_last_trade_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='gap_revenue',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='hedge_price',
        ),
        migrations.AddField(
            model_name='order',
            name='time_in_force',
            field=models.CharField(blank=True, choices=[(None, 'GTC'), ('FOK', 'FOK')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='fee_revenue',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='fee_usdt_value',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_source',
            field=models.CharField(choices=[('market', 'market'), ('system', 'system'), ('sys-make', 'sys-make'), ('sys-take', 'sys-take')], db_index=True, default='market', max_length=8),
        ),
    ]
