# Generated by Django 4.1.3 on 2023-02-08 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0041_remove_trade_gap_revenue_remove_trade_hedge_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='base_usdt_price',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
