# Generated by Django 4.1.3 on 2023-02-13 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0167_alter_otcrequest_symbol'),
        ('market', '0042_alter_trade_base_usdt_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.pairsymbol'),
        ),
        migrations.AlterField(
            model_name='pairsymbol',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pair', to='ledger.asset'),
        ),
        migrations.AlterField(
            model_name='pairsymbol',
            name='base_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trading_pair', to='ledger.asset'),
        ),
        migrations.AlterField(
            model_name='stoploss',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.pairsymbol'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.pairsymbol'),
        ),
    ]
