# Generated by Django 4.1.3 on 2023-02-28 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0043_alter_order_symbol_alter_pairsymbol_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='group_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='group_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
