# Generated by Django 4.0.4 on 2023-03-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0044_alter_order_group_id_alter_trade_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_in_force',
            field=models.CharField(blank=True, choices=[(None, 'GTC'), ('FOK', 'FOK'), ('IOC', 'IOC')], max_length=4, null=True),
        ),
    ]
