# Generated by Django 4.1.3 on 2023-03-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0105_merge_20230314_1509'),
        ('market', '0046_order_account'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('account', 'client_order_id', 'status')},
        ),
    ]
