# Generated by Django 4.1.3 on 2023-03-28 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0105_merge_20230314_1509'),
        ('market', '0047_alter_order_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
            preserve_default=False,
        ),
    ]
