# Generated by Django 4.1.3 on 2023-04-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0048_alter_order_account'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'new')), fields=('account', 'client_order_id', 'status'), name='unique_client_order_id_new_order'),
        ),
    ]
