# Generated by Django 4.1.3 on 2023-06-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0050_order_market_order_unique_group_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pairsymbol',
            name='check_market_pairsymbol_amounts',
        ),
        migrations.RemoveField(
            model_name='pairsymbol',
            name='maker_amount',
        ),
        migrations.RemoveField(
            model_name='pairsymbol',
            name='market_maker_enabled',
        ),
        migrations.AddConstraint(
            model_name='pairsymbol',
            constraint=models.CheckConstraint(check=models.Q(('max_trade_quantity__gte', 0), ('min_trade_quantity__gte', 0)), name='check_market_pairsymbol_amounts'),
        ),
    ]
