# Generated by Django 4.1.3 on 2023-08-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0054_oco_order_oco_stoploss_oco_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('oco', 'status'), name='market_order_unique_oco'),
        ),
    ]
