# Generated by Django 4.1.3 on 2023-08-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0055_order_market_order_unique_oco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['status']},
        ),
    ]
