# Generated by Django 4.1.3 on 2023-10-24 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0056_alter_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairsymbol',
            name='maker_fee',
        ),
        migrations.RemoveField(
            model_name='pairsymbol',
            name='taker_fee',
        ),
        migrations.AddField(
            model_name='pairsymbol',
            name='custom_maker_fee',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pairsymbol',
            name='custom_taker_fee',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
