# Generated by Django 4.1.3 on 2023-12-23 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0231_marginhistorymodel_marginleverage_and_more'),
        ('market', '0057_remove_pairsymbol_maker_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_open_position',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.marginposition'),
        ),
        migrations.AddField(
            model_name='pairsymbol',
            name='margin_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.marginposition'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('depth', 'depth'), ('bot', 'bot'), (None, 'ordinary'), ('liquid', 'liquid')], max_length=8, null=True),
        ),
    ]
