# Generated by Django 4.1.3 on 2024-01-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0058_order_is_open_position_order_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_in_force',
            field=models.CharField(blank=True, choices=[(None, 'GTC'), ('FOK', 'FOK'), ('IOC', 'IOC'), ('ME_IOC', 'ME_IOC')], max_length=6, null=True),
        ),
    ]
