# Generated by Django 4.1.3 on 2024-08-04 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0059_alter_order_time_in_force'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['status'], 'permissions': [('list_order', 'Can list order')]},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'permissions': [('list_trade', 'Can list trade')]},
        ),
    ]
