# Generated by Django 4.1.3 on 2024-01-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0059_alter_order_time_in_force'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status', 'new')), fields=['symbol', 'status', 'side'], name='symbol_side_new_orders_ids'),
        ),
    ]
