# Generated by Django 4.1.3 on 2024-08-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0060_alter_order_options_alter_trade_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('depth', 'depth'), ('bot', 'bot'), (None, 'ordinary'), ('liquid', 'liquid'), ('f_close', 'fast_close')], max_length=8, null=True),
        ),
    ]
