# Generated by Django 4.1.3 on 2024-02-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0060_order_symbol_side_new_orders_ids'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='symbol_side_new_orders_ids',
        ),
    ]
