# Generated by Django 4.1.3 on 2024-12-04 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0320_merge_20241201_1303'),
        ('market', '0061_alter_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.marginposition'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.marginposition'),
        ),
    ]
