# Generated by Django 4.1.3 on 2024-12-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0062_alter_order_position_alter_trade_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('list_order', 'Can list order')]},
        ),
    ]
