# Generated by Django 4.1.3 on 2025-01-27 09:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0063_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairsymbol',
            name='maker_buy_discount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='pairsymbol',
            name='maker_sell_discount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='pairsymbol',
            name='taker_buy_discount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='pairsymbol',
            name='taker_sell_discount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
