# Generated by Django 4.1.3 on 2025-02-01 12:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0064_pairsymbol_maker_buy_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairsymbol',
            name='maker_buy_discount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Maker Buy Discount (%)'),
        ),
        migrations.AlterField(
            model_name='pairsymbol',
            name='maker_sell_discount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Maker Sell Discount (%)'),
        ),
        migrations.AlterField(
            model_name='pairsymbol',
            name='taker_buy_discount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Taker Buy Discount (%)'),
        ),
        migrations.AlterField(
            model_name='pairsymbol',
            name='taker_sell_discount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Taker Sell Discount (%)'),
        ),
    ]
