# Generated by Django 4.1.3 on 2025-01-15 11:09

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='MaterializedCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('timeframe', models.CharField(choices=[('15min', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day')], max_length=10)),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=30)),
            ],
        ),
        migrations.AddIndex(
            model_name='materializedcandle',
            index=models.Index(fields=['symbol', 'timeframe'], name='ohlc_materi_symbol_8906c8_idx'),
        ),
        migrations.AddIndex(
            model_name='materializedcandle',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['symbol', 'timeframe', 'timestamp'], name='ohlc_materi_symbol_59d6b5_brin', pages_per_range=128),
        ),
        migrations.AlterUniqueTogether(
            name='materializedcandle',
            unique_together={('symbol', 'timestamp', 'timeframe')},
        ),
        migrations.AddIndex(
            model_name='candle',
            index=models.Index(fields=['symbol'], name='ohlc_candle_symbol_7e5d80_idx'),
        ),
        migrations.AddIndex(
            model_name='candle',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['timestamp'], name='ohlc_candle_timesta_e5b315_brin', pages_per_range=128),
        ),
        migrations.AlterUniqueTogether(
            name='candle',
            unique_together={('symbol', 'timestamp')},
        ),
    ]
