# Generated by Django 4.1.3 on 2025-01-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ohlc', '0002_materialized_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ohlc1D',
            fields=[
                ('row_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=30)),
            ],
            options={
                'db_table': 'ohlc_1d',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ohlc1H',
            fields=[
                ('row_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=30)),
            ],
            options={
                'db_table': 'ohlc_1h',
                'managed': False,
            },
        ),
    ]
