# Generated by Django 4.0 on 2022-02-07 13:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0043_asset_description'),
        ('accounts', '0004_account_last_margin_warn'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiatTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('amount', models.PositiveIntegerField()),
                ('deposit', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done')], db_index=True, default='pending', max_length=8)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ledger.trx')),
            ],
        ),
    ]
