# Generated by Django 4.0 on 2022-02-13 13:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_card_number_bankcard_card_pan'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('zarinpal', 'zarinpal')], max_length=8)),
                ('merchant_id', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField()),
                ('authority', models.CharField(blank=True, db_index=True, max_length=64)),
                ('bank_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.bankcard')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.gateway')),
            ],
            options={
                'unique_together': {('authority', 'gateway')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('group_id', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done')], default='pending', max_length=8)),
                ('ref_id', models.PositiveIntegerField()),
                ('ref_status', models.SmallIntegerField()),
                ('payment_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='financial.paymentrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ZarinpalGateway',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('financial.gateway',),
        ),
    ]
