# Generated by Django 4.0 on 2022-02-14 09:21

import financial.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_bankcard_user'),
        ('financial', '0002_gateway_paymentrequest_payment_zarinpalgateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('card_pan', models.CharField(max_length=20, unique=True, validators=[financial.validators.bank_card_pan_validator], verbose_name='شماره کارت')),
                ('iban', models.CharField(max_length=26, unique=True, validators=[financial.validators.iban_validator], verbose_name='شبا')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
            ],
            options={
                'verbose_name': 'کارت بانکی',
                'verbose_name_plural': 'کارت\u200cهای بانکی',
            },
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='bank_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.bankcard'),
        ),
    ]
