# Generated by Django 4.0 on 2022-02-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_remove_bankcard_iban_remove_bankcard_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiattransferrequest',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='fiattransferrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done')], default='pending', max_length=8),
        ),
    ]
