# Generated by Django 4.0 on 2022-02-15 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_remove_fiattransferrequest_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiattransferrequest',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
