# Generated by Django 4.0 on 2022-02-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_alter_fiattransferrequest_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ref_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref_status',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
