# Generated by Django 4.0 on 2022-02-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_alter_payment_ref_id_alter_payment_ref_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ref_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
