# Generated by Django 4.0 on 2022-02-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_notification_title_alter_user_verification'),
        ('financial', '0008_alter_payment_ref_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FiatTransferRequest',
            new_name='FiatTransaction',
        ),
    ]
