# Generated by Django 4.0 on 2022-02-20 15:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0054_remove_asset_withdraw_step_and_more'),
        ('financial', '0009_rename_fiattransferrequest_fiattransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiatWithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('amount', models.PositiveIntegerField()),
                ('fee_amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done')], default='pending', max_length=8)),
                ('ref_id', models.CharField(blank=True, max_length=128)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.bankaccount')),
                ('lock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ledger.balancelock')),
            ],
        ),
    ]
