# Generated by Django 4.0 on 2022-02-21 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0055_remove_transfer_unique_transfer_tx_hash_network_and_more'),
        ('financial', '0010_fiatwithdrawrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatwithdrawrequest',
            name='lock',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='ledger.balancelock'),
        ),
    ]
