# Generated by Django 4.0 on 2022-02-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0012_bankaccount_bank_name_bankaccount_card_pan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatwithdrawrequest',
            name='ref_doc',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='رسید انتقال'),
        ),
        migrations.AlterField(
            model_name='fiatwithdrawrequest',
            name='ref_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='شماره پیگیری'),
        ),
    ]
