# Generated by Django 4.0 on 2022-02-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0013_fiatwithdrawrequest_ref_doc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiatwithdrawrequest',
            options={'verbose_name': 'درخواست انتقال', 'verbose_name_plural': 'درخواست\u200cهای انتقال'},
        ),
    ]
