# Generated by Django 4.0 on 2022-02-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0014_alter_fiatwithdrawrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiattransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='fiatwithdrawrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده')], default='pending', max_length=8),
        ),
    ]
