# Generated by Django 4.0 on 2022-02-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0015_alter_fiattransaction_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiatwithdrawrequest',
            options={'verbose_name': 'درخواست برداشت', 'verbose_name_plural': 'درخواست\u200cهای برداشت'},
        ),
    ]
