# Generated by Django 4.0 on 2022-02-27 08:03

from django.db import migrations, models
import financial.validators


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0016_alter_fiatwithdrawrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(max_length=26, validators=[financial.validators.iban_validator], verbose_name='شبا'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='card_pan',
            field=models.CharField(max_length=20, validators=[financial.validators.bank_card_pan_validator], verbose_name='شماره کارت'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('verified', True)), fields=('iban',), name='unique_bank_account_iban'),
        ),
        migrations.AddConstraint(
            model_name='bankcard',
            constraint=models.UniqueConstraint(condition=models.Q(('verified', True)), fields=('card_pan',), name='unique_bank_card_card_pan'),
        ),
    ]
