# Generated by Django 4.0 on 2022-03-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_finotechrequest_search_key'),
        ('financial', '0017_alter_bankaccount_iban_alter_bankcard_card_pan_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('iban', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='bankcard',
            unique_together={('card_pan', 'user')},
        ),
    ]
