# Generated by Django 4.0 on 2022-03-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0018_alter_bankaccount_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaydotirGateway',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('financial.gateway',),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='type',
            field=models.CharField(choices=[('zarinpal', 'zarinpal'), ('paydotir', 'paydotir')], max_length=8),
        ),
    ]
