# Generated by Django 4.0 on 2022-03-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0019_paydotirgateway_alter_gateway_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatwithdrawrequest',
            name='providing_status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده')], default='pending', max_length=8),
        ),
    ]
