# Generated by Django 4.0 on 2022-03-29 13:04

from django.db import migrations, models
import django.db.models.deletion
import financial.validators
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_historicaluser_archived_user_archived'),
        ('financial', '0019_paydotirgateway_alter_gateway_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBankCard',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('card_pan', models.CharField(max_length=20, validators=[financial.validators.bank_card_pan_validator], verbose_name='شماره کارت')),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.user')),
            ],
            options={
                'verbose_name': 'historical کارت بانکی',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBankAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('iban', models.CharField(max_length=26, validators=[financial.validators.iban_validator], verbose_name='شبا')),
                ('bank_name', models.CharField(blank=True, max_length=256)),
                ('deposit_address', models.CharField(blank=True, max_length=64)),
                ('card_pan', models.CharField(blank=True, max_length=20)),
                ('deposit_status', models.CharField(blank=True, choices=[('active', 'active'), ('suspend', 'suspend'), ('nsuspend', 'nodep suspend'), ('stagnant', 'stagnant')], max_length=8)),
                ('owners', models.JSONField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.user')),
            ],
            options={
                'verbose_name': 'historical حساب بانکی',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
