# Generated by Django 4.0 on 2022-04-09 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0020_historicalbankcard_historicalbankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatwithdrawrequest',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='میزان قابل برداشت'),
        ),
        migrations.AlterField(
            model_name='fiatwithdrawrequest',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.bankaccount', verbose_name='حساب بانکی'),
        ),
        migrations.AlterField(
            model_name='fiatwithdrawrequest',
            name='fee_amount',
            field=models.PositiveIntegerField(verbose_name='کارمزد'),
        ),
    ]
