# Generated by Django 4.0 on 2022-03-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0021_rename_providing_status_fiatwithdrawrequest_provider_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatwithdrawrequest',
            name='provider_request_status',
            field=models.CharField(choices=[('init', 'مرحله اولیه'), ('sent', 'ارسال شده'), ('done', 'انجام شده'), ('canceled', 'لغو شده')], default='init', max_length=10),
        ),
    ]
