# Generated by Django 4.0 on 2022-04-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0021_alter_fiatwithdrawrequest_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatwithdrawrequest',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='میزان برداشت'),
        ),
    ]
