# Generated by Django 4.0 on 2022-04-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0022_alter_fiatwithdrawrequest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatwithdrawrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='نظر'),
        ),
    ]
