# Generated by Django 4.0 on 2022-04-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0023_fiatwithdrawrequest_comment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankaccount',
            name='unique_bank_account_iban',
        ),
        migrations.RemoveConstraint(
            model_name='bankcard',
            name='unique_bank_card_card_pan',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbankaccount',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbankcard',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('verified', True)), fields=('iban',), name='unique_bank_account_iban'),
        ),
        migrations.AddConstraint(
            model_name='bankcard',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('verified', True)), fields=('card_pan',), name='unique_bank_card_card_pan'),
        ),
    ]
