# Generated by Django 4.0 on 2022-04-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0024_remove_bankaccount_unique_bank_account_iban_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bankcard',
            unique_together=set(),
        ),
    ]
