# Generated by Django 4.0 on 2022-04-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0024_fiatwithdrawrequest_deleted'),
        ('financial', '0025_alter_bankaccount_unique_together_and_more'),
    ]

    operations = [
    ]
