# Generated by Django 4.0 on 2022-04-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0026_merge_20220426_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiatwithdrawrequest',
            name='deleted',
        ),
        migrations.AddField(
            model_name='fiatwithdrawrequest',
            name='done_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
