# Generated by Django 4.0 on 2022-05-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0022_alter_fiatwithdrawrequest_provider_request_status'),
        ('financial', '0028_alter_fiatwithdrawrequest_lock'),
    ]

    operations = [
    ]
