# Generated by Django 4.0 on 2022-05-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0030_remove_fiatwithdrawrequest_provider_request_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiatwithdrawrequest',
            name='provider_withdraw_id',
        ),
    ]
