# Generated by Django 4.0 on 2022-05-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0031_remove_fiatwithdrawrequest_provider_withdraw_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatwithdrawrequest',
            name='provider_withdraw_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
