# Generated by Django 4.0 on 2022-05-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0032_fiatwithdrawrequest_provider_withdraw_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiatwithdrawrequest',
            old_name='done_datetime',
            new_name='withdraw_datetime',
        ),
    ]
