# Generated by Django 4.0 on 2022-05-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0033_rename_done_datetime_fiatwithdrawrequest_withdraw_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZibalGateway',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('financial.gateway',),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='type',
            field=models.CharField(choices=[('zarinpal', 'zarinpal'), ('paydotir', 'paydotir'), ('zibal', 'zibal')], max_length=8),
        ),
    ]
