# Generated by Django 4.0 on 2022-06-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0034_zibalgateway_alter_gateway_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatwithdrawrequest',
            name='withdraw_chanel',
            field=models.CharField(choices=[('zibal', 'zibal'), ('payir', 'payir')], default='payir', max_length=10),
        ),
    ]
