# Generated by Django 4.0 on 2022-06-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0035_fiatwithdrawrequest_withdraw_chanel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiatwithdrawrequest',
            old_name='withdraw_chanel',
            new_name='withdraw_channel',
        ),
    ]
