# Generated by Django 4.0 on 2022-06-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0036_rename_withdraw_chanel_fiatwithdrawrequest_withdraw_channel'),
        ('ledger', '0098_remove_trx_check_ledger_trx_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiatwithdrawrequest',
            name='lock',
        ),
    ]
