# Generated by Django 4.0 on 2022-07-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0038_alter_gateway_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='active_for_staff',
            field=models.BooleanField(default=False),
        ),
    ]
