# Generated by Django 4.0 on 2022-07-24 06:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0105_alter_margintransfer_amount'),
        ('financial', '0039_gateway_active_for_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('full_fill_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField()),
                ('deposit', models.BooleanField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.asset')),
            ],
        ),
    ]
