# Generated by Django 4.0 on 2022-07-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0039_gateway_active_for_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='source',
            field=models.CharField(choices=[('app', 'app'), ('desktop', 'desktop')], default='desktop', max_length=16),
        ),
    ]
