# Generated by Django 4.0 on 2022-07-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0040_manualtransferhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualtransferhistory',
            name='done',
            field=models.BooleanField(default=True),
        ),
    ]
