# Generated by Django 4.0 on 2022-07-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0041_manualtransferhistory_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source', models.CharField(max_length=256)),
                ('utm_medium', models.CharField(blank=True, max_length=256)),
                ('utm_campaign', models.CharField(blank=True, max_length=256)),
                ('utm_content', models.CharField(blank=True, max_length=256)),
                ('utm_term', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'unique_together': {('utm_source', 'utm_medium', 'utm_campaign', 'utm_content', 'utm_term')},
            },
        ),
        migrations.CreateModel(
            name='MarketingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('cost', models.PositiveIntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.marketingsource')),
            ],
            options={
                'unique_together': {('date', 'cost')},
            },
        ),
    ]
