# Generated by Django 4.0 on 2022-07-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0040_paymentrequest_source'),
        ('financial', '0041_manualtransferhistory_done'),
    ]

    operations = [
    ]
