# Generated by Django 4.0 on 2022-07-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0042_marketingsource_marketingcost'),
        ('financial', '0042_merge_20220726_1244'),
    ]

    operations = [
    ]
