# Generated by Django 4.0 on 2022-07-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0042_marketingsource_marketingcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingcost',
            name='date',
            field=models.DateField(),
        ),
    ]
