# Generated by Django 4.0 on 2022-07-31 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0043_alter_marketingcost_date'),
        ('financial', '0043_merge_20220727_1615'),
    ]

    operations = [
    ]
