# Generated by Django 4.0 on 2022-08-04 14:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0117_alter_transfer_source'),
        ('financial', '0044_merge_20220731_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('done', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('self', 'self'), ('trade', 'trade'), ('stake', 'stake')], default='self', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.asset')),
            ],
            options={
                'verbose_name': 'سرمایه\u200cگذاری',
                'verbose_name_plural': 'سرمایه\u200cگذاری',
            },
        ),
        migrations.CreateModel(
            name='InvestmentRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(blank=True, max_length=256)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.investment')),
            ],
            options={
                'verbose_name': 'درآمد سرمایه\u200cگذاری',
                'verbose_name_plural': 'درآمد سرمایه\u200cگذاری',
            },
        ),
    ]
