# Generated by Django 4.0 on 2022-08-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0045_investment_investmentrevenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
    ]
