# Generated by Django 4.0 on 2022-08-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0047_alter_investment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankaccount',
            name='unique_bank_account_iban',
        ),
        migrations.RemoveConstraint(
            model_name='bankcard',
            name='unique_bank_card_card_pan',
        ),
    ]
