# Generated by Django 4.0 on 2022-08-11 10:28

from django.db import migrations, models


def populate_kyc_field(apps, schema_editor):
    BankCard = apps.get_model('financial', 'BankCard')

    bank_cards = list(BankCard.objects.filter(deleted=False).order_by('user', '-verified').distinct('user').values_list('id', flat=True))

    BankCard.objects.filter(id__in=bank_cards).update(kyc=True)


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0049_bankaccount_unique_bank_account_iban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcard',
            name='kyc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbankcard',
            name='kyc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='bankcard',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('kyc', True)), fields=('user',), name='bank_card_unique_kyc_user'),
        ),
        migrations.RunPython(
            code=populate_kyc_field, reverse_code=migrations.RunPython.noop
        )
    ]
