# Generated by Django 4.0 on 2022-08-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0051_bankcard_bank_bankcard_deposit_number_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('verified', True)), fields=('iban',), name='unique_bank_account_verified_iban'),
        ),
        migrations.AddConstraint(
            model_name='bankcard',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('verified', True)), fields=('card_pan',), name='unique_bank_card_verified_card_pan'),
        ),
    ]
