# Generated by Django 4.0 on 2022-08-17 08:23

from django.db import migrations, models


def move_amount(apps, schema_editor):
    Investment = apps.get_model('financial', 'Investment')
    InvestmentRevenue = apps.get_model('financial', 'InvestmentRevenue')

    for investment in Investment.objects.all():
        InvestmentRevenue.objects.create(investment=investment, amount=investment.amount, description='پول پایه')


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0052_bankaccount_unique_bank_account_verified_iban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='title',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentrevenue',
            name='revenue',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            code=move_amount, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='investment',
            name='amount',
        ),
    ]
