# Generated by Django 4.0 on 2022-08-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0053_remove_investment_amount_investment_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='exclude_from_total_assets',
            field=models.BooleanField(default=False),
        ),
    ]
