# Generated by Django 4.0 on 2022-08-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0054_investment_exclude_from_total_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='invested',
            field=models.BooleanField(default=False),
        ),
    ]
