# Generated by Django 4.0 on 2022-09-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0058_fiathedgetrx'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatwithdrawrequest',
            name='receive_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
