# Generated by Django 4.0 on 2022-09-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0059_fiatwithdrawrequest_receive_datetime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketingcost',
            unique_together={('date', 'source')},
        ),
    ]
