# Generated by Django 4.0 on 2022-09-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0061_alter_fiatwithdrawrequest_withdraw_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JibitGateway',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('financial.gateway',),
        ),
    ]
