# Generated by Django 4.0 on 2022-09-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0062_jibitgateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='authority',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
