# Generated by Django 4.0 on 2022-11-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0063_alter_paymentrequest_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatwithdrawrequest',
            name='withdraw_channel',
            field=models.CharField(choices=[('zibal', 'zibal'), ('payir', 'payir'), ('jibit', 'jibit'), ('manual', 'manual')], default='payir', max_length=10),
        ),
    ]
