# Generated by Django 4.1.3 on 2022-12-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0065_alter_payment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='max_deposit_amount',
            field=models.PositiveIntegerField(default=50000000),
        ),
        migrations.AddField(
            model_name='gateway',
            name='min_deposit_amount',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
