# Generated by Django 4.1.3 on 2023-01-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0066_gateway_max_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatwithdrawrequest',
            name='risks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiatwithdrawrequest',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('done', 'done'), ('canceled', 'canceled')], default='init', max_length=10),
        ),
    ]
