# Generated by Django 4.1.3 on 2023-01-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0067_fiatwithdrawrequest_risks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentrevenue',
            name='investment',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='InvestmentRevenue',
        ),
    ]
