# Generated by Django 4.1.3 on 2023-02-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0068_remove_investmentrevenue_investment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='max_auto_withdraw_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
