# Generated by Django 4.1.3 on 2023-02-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0069_gateway_max_auto_withdraw_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='expected_withdraw_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
