# Generated by Django 4.1.3 on 2023-02-06 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0070_gateway_expected_withdraw_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFiatWithdrawRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('amount', models.PositiveIntegerField(verbose_name='میزان برداشت')),
                ('fee_amount', models.PositiveIntegerField(verbose_name='کارمزد')),
                ('status', models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('done', 'done'), ('canceled', 'canceled')], default='init', max_length=10)),
                ('ref_id', models.CharField(blank=True, max_length=128, verbose_name='شماره پیگیری')),
                ('ref_doc', models.TextField(blank=True, max_length=100, null=True, verbose_name='رسید انتقال')),
                ('comment', models.TextField(blank=True, verbose_name='نظر')),
                ('withdraw_datetime', models.DateTimeField(blank=True, null=True)),
                ('receive_datetime', models.DateTimeField(blank=True, null=True)),
                ('provider_withdraw_id', models.CharField(blank=True, max_length=64)),
                ('withdraw_channel', models.CharField(choices=[('zibal', 'zibal'), ('payir', 'payir'), ('jibit', 'jibit'), ('manual', 'manual')], default='payir', max_length=10)),
                ('risks', models.JSONField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial.bankaccount', verbose_name='حساب بانکی')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical درخواست برداشت',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
