# Generated by Django 4.1.3 on 2023-02-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0071_historicalfiatwithdrawrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiatwithdrawrequest',
            name='provider_withdraw_id',
        ),
        migrations.RemoveField(
            model_name='historicalfiatwithdrawrequest',
            name='provider_withdraw_id',
        ),
    ]
