# Generated by Django 4.1.3 on 2023-02-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0072_remove_fiatwithdrawrequest_provider_withdraw_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FiatHedgeTrx',
        ),
    ]
