# Generated by Django 4.1.3 on 2023-02-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0073_delete_fiathedgetrx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FiatTransaction',
        ),
    ]
