# Generated by Django 4.1.3 on 2023-03-18 21:28

from django.db import migrations, models
import django.db.models.deletion


def populate_gateway(apps, schema_editor):
    Gateway = apps.get_model('financial', 'Gateway')
    FiatWithdrawRequest = apps.get_model('financial', 'FiatWithdrawRequest')

    gateways = {g.type: g for g in Gateway.objects.all()}
    withdraws = list(FiatWithdrawRequest.objects.all())

    for w in withdraws:
        w.gateway = gateways[w.withdraw_channel]

    FiatWithdrawRequest.objects.bulk_update(withdraws, fields=['gateway'])


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0075_alter_fiatwithdrawrequest_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatwithdrawrequest',
            name='gateway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='financial.gateway'),
            preserve_default=False,
        ),
        migrations.RunPython(populate_gateway, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fiatwithdrawrequest',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.gateway'),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='gateway',
            name='api_key',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='gateway',
            name='api_secret_encrypted',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='gateway',
            name='wallet_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='withdraw_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfiatwithdrawrequest',
            name='gateway',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial.gateway'),
        ),
        migrations.RemoveField(
            model_name='fiatwithdrawrequest',
            name='withdraw_channel',
        ),
        migrations.RemoveField(
            model_name='historicalfiatwithdrawrequest',
            name='withdraw_channel',
        ),
    ]
