# Generated by Django 4.1.3 on 2023-04-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0076_remove_fiatwithdrawrequest_withdraw_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiatwithdrawrequest',
            name='ref_doc',
        ),
        migrations.RemoveField(
            model_name='historicalfiatwithdrawrequest',
            name='ref_doc',
        ),
    ]
