# Generated by Django 4.1.3 on 2023-04-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0077_remove_fiatwithdrawrequest_ref_doc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gateway',
            old_name='api_key',
            new_name='withdraw_api_key',
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='api_secret_encrypted',
            new_name='withdraw_api_secret_encrypted',
        ),
        migrations.AddField(
            model_name='gateway',
            name='deposit_api_key',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='gateway',
            name='deposit_api_secret_encrypted',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
