# Generated by Django 4.1.3 on 2023-04-30 11:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0078_rename_api_key_gateway_withdraw_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('process', 'process'), ('done', 'done')], default='process', max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='stake_holder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbankaccount',
            name='stake_holder',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ManualTransferHistory',
        ),
        migrations.AddField(
            model_name='manualtransfer',
            name='bank_account',
            field=models.ForeignKey(limit_choices_to={'stake_holder': True}, on_delete=django.db.models.deletion.CASCADE, to='financial.bankaccount'),
        ),
        migrations.AddField(
            model_name='manualtransfer',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.gateway'),
        ),
    ]
