# Generated by Django 4.1.3 on 2023-05-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0080_alter_manualtransfer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatwithdrawrequest',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], default='init', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfiatwithdrawrequest',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], default='init', max_length=10),
        ),
    ]
