# Generated by Django 4.1.3 on 2023-06-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0082_bankpaymentid_paymentidrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='payment_id_api_key',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='gateway',
            name='payment_id_secret_encrypted',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
