# Generated by Django 4.1.3 on 2023-06-11 18:20

from django.db import migrations, models

def populate_gateway(apps, schema_editor):
    Gateway = apps.get_model('financial', 'Gateway')
    g = Gateway.objects.filter(active=True).order_by('id').first()
    if g:
        g.primary = True
        g.save()


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0083_gateway_payment_id_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='gateway',
            constraint=models.UniqueConstraint(condition=models.Q(('primary', True)), fields=('primary',), name='financial_gateway_unique_primary'),
        ),
        migrations.RunPython(
            code=populate_gateway,
            reverse_code=migrations.RunPython.noop
        )
    ]
