# Generated by Django 4.1.3 on 2023-06-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0085_generalbankaccount_paymentid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gateway',
            name='financial_gateway_unique_primary',
        ),
        migrations.AddField(
            model_name='gateway',
            name='deposit_priority',
            field=models.SmallIntegerField(default=1),
        ),
    ]
