# Generated by Django 4.1.3 on 2023-06-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0086_remove_gateway_financial_gateway_unique_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='max_daily_deposit_amount',
            field=models.PositiveIntegerField(default=100000000),
        ),
    ]
