# Generated by Django 4.1.3 on 2023-06-15 13:49

from django.db import migrations, models
import financial.validators


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0088_paymentidrequest_deposit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentidrequest',
            name='source_iban',
            field=models.CharField(max_length=26, validators=[financial.validators.iban_validator], verbose_name='شبا'),
        ),
    ]
