# Generated by Django 4.1.3 on 2023-06-26 13:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0089_alter_paymentidrequest_source_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='ipg_fee_max',
            field=models.SmallIntegerField(default=4000),
        ),
        migrations.AddField(
            model_name='gateway',
            name='ipg_fee_min',
            field=models.SmallIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='gateway',
            name='ipg_fee_percent',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.02'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='paymentidrequest',
            name='fee',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='fee',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
