# Generated by Django 4.1.3 on 2023-07-08 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0135_delete_externalnotification'),
        ('financial', '0091_alter_gateway_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatwithdrawrequest',
            name='login_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.loginactivity'),
        ),
        migrations.AddField(
            model_name='historicalfiatwithdrawrequest',
            name='login_activity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.loginactivity'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='login_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.loginactivity'),
        ),
    ]
