# Generated by Django 4.1.3 on 2023-07-11 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0092_remove_payment_check_financial_payment_requests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group_id', models.UUIDField(default=uuid.uuid4)),
                ('destination_type', models.CharField(choices=[('jibimo', 'jibimo')], default='jibimo', max_length=16)),
                ('amount', models.PositiveIntegerField()),
                ('ref_id', models.CharField(blank=True, max_length=256)),
                ('receipt', models.FileField(upload_to='')),
                ('destination_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.payment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('destination_id', 'destination_type')},
            },
        ),
    ]
