# Generated by Django 4.1.3 on 2023-07-11 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0093_bankpaymentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_id_request',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_request',
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
