# Generated by Django 4.1.3 on 2023-07-11 10:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0094_remove_payment_payment_id_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
