# Generated by Django 4.1.3 on 2023-07-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0095_alter_paymentrequest_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='group_id',
            field=models.UUIDField(default=None, unique=True),
        ),
    ]
