# Generated by Django 4.1.3 on 2023-07-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0097_payment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpaymentrequest',
            name='ref_id',
            field=models.PositiveIntegerField(blank=True, max_length=256),
        ),
    ]
