# Generated by Django 4.1.3 on 2023-07-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0092_fiatwithdrawrequest_login_activity_and_more'),
        ('financial', '0097_payment_description'),
    ]

    operations = [
    ]
