# Generated by Django 4.1.3 on 2023-07-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0098_alter_bankpaymentrequest_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpaymentrequest',
            name='ref_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
