# Generated by Django 4.1.3 on 2023-07-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0098_merge_20230716_0956'),
        ('financial', '0099_alter_bankpaymentrequest_ref_id_alter_payment_ref_id'),
    ]

    operations = [
    ]
