# Generated by Django 4.1.3 on 2023-07-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0100_merge_20230717_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='withdraw_api_password_encrypted',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
