# Generated by Django 4.1.3 on 2023-08-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0102_gateway_batch_id_manualtransfer_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpaymentrequest',
            name='amount',
            field=models.PositiveBigIntegerField(),
        ),
    ]
