# Generated by Django 4.1.3 on 2023-08-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0104_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatwithdrawrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfiatwithdrawrequest',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='manualtransfer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
