# Generated by Django 4.1.3 on 2023-09-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0105_alter_fiatwithdrawrequest_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='withdraw_bank',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
