# Generated by Django 4.1.3 on 2023-10-22 12:23

from django.db import migrations, models
import uuid


def populate_payment_id_group_id(apps, schema_editor):
    PaymentId = apps.get_model('financial', 'PaymentId')

    for p in PaymentId.objects.all():
        p.group_id = uuid.uuid4()
        p.save(update_fields=['group_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0106_gateway_withdraw_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentid',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='paymentid',
            name='provider_reason',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='paymentid',
            name='provider_status',
            field=models.CharField(blank=True, max_length=256),
        ),

        migrations.RunPython(
            code=populate_payment_id_group_id,
            reverse_code=migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name='paymentid',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4),
        )
    ]
