# Generated by Django 4.1.3 on 2023-10-24 10:44

from django.db import migrations, models
import django.db.models.deletion


def populate_receipt(apps, schema_editor):
    BankPaymentRequest = apps.get_model('financial', 'BankPaymentRequest')
    BankPaymentRequestReceipt = apps.get_model('financial', 'BankPaymentRequestReceipt')

    for payment in BankPaymentRequest.objects.all():
        BankPaymentRequestReceipt.objects.create(payment_request=payment, receipt=payment.receipt)


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0107_paymentid_group_id_paymentid_provider_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankPaymentRequestReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.FileField(upload_to='')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.bankpaymentrequest')),
            ],
        ),
        migrations.RunPython(
            code=populate_receipt,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='BankPaymentRequest',
            name='receipt'
        )
    ]
