# Generated by Django 4.1.3 on 2023-11-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0108_bankpaymentrequestreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentidrequest',
            name='amount',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentidrequest',
            name='fee',
            field=models.PositiveBigIntegerField(),
        ),
    ]
