# Generated by Django 4.1.3 on 2024-01-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0109_alter_paymentidrequest_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
