# Generated by Django 4.1.3 on 2024-01-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0111_paymentid_deleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentid',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='paymentid',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('user', 'gateway'), name='unique_financial_paymentid_user_gateway'),
        ),
        migrations.AddConstraint(
            model_name='paymentid',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('pay_id', 'gateway'), name='unique_financial_paymentid_pay_id_gateway'),
        ),
    ]
