# Generated by Django 4.1.3 on 2024-01-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0112_alter_paymentid_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='type',
            field=models.CharField(choices=[('manual', 'manual'), ('zarinpal', 'zarinpal'), ('payir', 'payir'), ('zibal', 'zibal'), ('jibit', 'jibit'), ('jibimo', 'jibimo'), ('paystar', 'paystar')], max_length=8),
        ),
    ]
