# Generated by Django 4.1.3 on 2024-01-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0113_alter_gateway_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystarGateway',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('financial.gateway',),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='token',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
