# Generated by Django 4.1.3 on 2024-01-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0114_paystargateway_paymentrequest_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='primary',
        ),
        migrations.AddField(
            model_name='gateway',
            name='ipg_deposit_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='pay_id_deposit_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='paymentidrequest',
            name='status',
            field=models.CharField(choices=[('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], default='pending', max_length=8),
        ),
    ]
