# Generated by Django 4.1.3 on 2024-01-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0115_remove_gateway_primary_gateway_ipg_deposit_enable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='wallet_id',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
    ]
