# Generated by Django 4.1.3 on 2024-01-23 15:56

from django.db import migrations

from financial.utils.encryption import encrypt


def alter_withdraw_api_key_encrypted(apps, schema_editor):
    Gateway = apps.get_model('financial', 'Gateway')

    for gateway in Gateway.objects.exclude(withdraw_api_key_encrypted=''):
        gateway.withdraw_api_key_encrypted = encrypt(gateway.withdraw_api_key_encrypted)
        gateway.save(update_fields=['withdraw_api_key_encrypted'])


class Migration(migrations.Migration):
    dependencies = [
        ('financial', '0116_alter_gateway_wallet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gateway',
            old_name='withdraw_api_key',
            new_name='withdraw_api_key_encrypted',
        ),
        migrations.RunPython(
            code=alter_withdraw_api_key_encrypted,
            reverse_code=migrations.RunPython.noop
        ),
    ]
