# Generated by Django 4.1.3 on 2024-01-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0117_rename_withdraw_api_key_gateway_withdraw_api_key_encrypted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='withdraw_bank',
        ),
    ]
