# Generated by Django 4.1.3 on 2024-02-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0119_gateway_withdraw_refresh_token_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatwithdrawrequest',
            name='status',
            field=models.CharField(choices=[('init', 'در حال بررسی'), ('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='historicalfiatwithdrawrequest',
            name='status',
            field=models.CharField(choices=[('init', 'در حال بررسی'), ('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('init', 'در حال بررسی'), ('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='paymentidrequest',
            name='status',
            field=models.CharField(choices=[('init', 'در حال بررسی'), ('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], db_index=True, default='pending', max_length=8),
        ),
    ]
