# Generated by Django 4.1.3 on 2024-02-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0122_gateway_instant_withdraw_banks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovinpalGateway',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('financial.gateway',),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='type',
            field=models.CharField(choices=[('manual', 'manual'), ('zarinpal', 'zarinpal'), ('payir', 'payir'), ('zibal', 'zibal'), ('jibit', 'jibit'), ('jibimo', 'jibimo'), ('paystar', 'paystar'), ('novinpal', 'novinpal')], max_length=8),
        ),
    ]
