# Generated by Django 4.1.3 on 2024-02-15 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_payment_sources(apps, schema_editor):
    Payment = apps.get_model('financial', 'Payment')
    Payment.objects.filter(paymentrequest__isnull=False).update(source='ipg')
    Payment.objects.filter(paymentidrequest__isnull=False).update(source='pay_id')
    Payment.objects.filter(paymentidrequest__isnull=True, paymentrequest__isnull=True).update(source='manual')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0124_alter_gateway_instant_withdraw_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='source',
            field=models.CharField(choices=[('ipg', 'ipg'), ('pay_id', 'pay_id'), ('manual', 'manual')], default='', max_length=16, db_index=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentid',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_payment_sources, reverse_code=migrations.RunPython.noop)
    ]
