# Generated by Django 4.1.3 on 2024-02-15 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0125_payment_source_paymentid_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
