# Generated by Django 4.1.3 on 2024-03-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0128_fiatwithdrawrequest_accepted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentid',
            name='full_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
