# Generated by Django 4.1.3 on 2024-04-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0129_paymentid_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='ipg_callback_host',
            field=models.URLField(blank=True),
        ),
    ]
