# Generated by Django 4.1.3 on 2024-07-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0132_alter_gateway_instant_withdraw_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
