# Generated by Django 4.1.3 on 2024-07-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0133_paymentrequest_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='active_for_trusted',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='max_daily_deposit_amount',
        ),
        migrations.AlterField(
            model_name='gateway',
            name='max_deposit_amount',
            field=models.PositiveIntegerField(default=25000000),
        ),
    ]
