# Generated by Django 4.1.3 on 2024-07-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0134_remove_gateway_active_for_trusted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_pan',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
