# Generated by Django 4.1.3 on 2024-08-04 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0135_payment_card_pan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'permissions': [('list_bankaccount', 'Can list bank account')], 'verbose_name': 'حساب بانکی', 'verbose_name_plural': 'حساب\u200cهای بانکی'},
        ),
        migrations.AlterModelOptions(
            name='bankcard',
            options={'permissions': [('list_bankcard', 'Can list bank card')], 'verbose_name': 'کارت بانکی', 'verbose_name_plural': 'کارت\u200cهای بانکی'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': [('list_payment', 'Can list payment')]},
        ),
        migrations.AlterModelOptions(
            name='paymentrequest',
            options={'permissions': [('list_paymentrequest', 'Can list payment request')]},
        ),
    ]
