# Generated by Django 4.1.3 on 2024-08-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0136_alter_bankaccount_options_alter_bankcard_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiatwithdrawrequest',
            options={'permissions': [('list_fiatwithdrawrequest', 'Can list fiat withdraw request')], 'verbose_name': 'درخواست برداشت', 'verbose_name_plural': 'درخواست\u200cهای برداشت'},
        ),
    ]
