# Generated by Django 4.1.3 on 2024-08-31 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0222_alter_historicaluser_promotion_alter_user_promotion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0137_alter_fiatwithdrawrequest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPaymentRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('amount', models.PositiveIntegerField()),
                ('fee', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('app', 'app'), ('desktop', 'desktop')], default='desktop', max_length=16)),
                ('authority', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('token', models.CharField(blank=True, max_length=256)),
                ('group_id', models.UUIDField(default=uuid.uuid4)),
                ('details', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_card', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial.bankcard')),
                ('gateway', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial.gateway')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('login_activity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.loginactivity')),
                ('payment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial.payment')),
            ],
            options={
                'verbose_name': 'historical payment request',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('group_id', models.UUIDField(default=uuid.uuid4)),
                ('amount', models.PositiveBigIntegerField()),
                ('fee', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8)),
                ('ref_id', models.CharField(blank=True, max_length=256, null=True)),
                ('ref_status', models.SmallIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('source', models.CharField(choices=[('ipg', 'ipg'), ('pay_id', 'pay_id'), ('manual', 'manual')], db_index=True, max_length=16)),
                ('card_pan', models.CharField(blank=True, max_length=32)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical payment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
