# Generated by Django 4.1.3 on 2024-08-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0138_paymentrequest_user_alter_paymentrequest_bank_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='is_for_widget',
            field=models.BooleanField(default=False),
        ),
    ]
