# Generated by Django 4.1.3 on 2024-09-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0138_historicalpaymentrequest_historicalpayment'),
        ('financial', '0139_gateway_widget_enable'),
    ]

    operations = [
    ]
