# Generated by Django 4.1.3 on 2024-08-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0139_auto_20240818_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='widget_enable',
            field=models.BooleanField(default=False),
        ),
    ]
