# Generated by Django 4.1.3 on 2024-09-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0141_historicalpaymentrequest_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gateway',
            old_name='is_for_widget',
            new_name='widget_deposit_enable',
        ),
    ]
