# Generated by Django 4.1.3 on 2024-09-10 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0142_rename_is_for_widget_gateway_widget_deposit_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
