# Generated by Django 4.1.3 on 2024-10-05 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0144_alter_historicalpayment_ref_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='group_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='payment',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
