# Generated by Django 4.1.3 on 2024-10-19 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0145_alter_historicalpayment_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatwithdrawrequest',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalfiatwithdrawrequest',
            name='group_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='manualtransfer',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
