# Generated by Django 4.1.3 on 2024-11-03 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0146_alter_bankaccount_user_alter_bankcard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='bank_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.bankcard'),
        ),
    ]
