# Generated by Django 4.1.3 on 2024-12-01 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0147_alter_paymentrequest_bank_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalbankaccount',
            old_name='rejected_by',
            new_name='verifier',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='rejected_by',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbankaccount',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalbankaccount',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='historicalbankcard',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalbankcard',
            name='verifier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
