# Generated by Django 4.1.3 on 2024-12-29 13:35

import django.db.models.deletion
from django.db import migrations, models


def migrate_gateway_fields_to_payidgateway(apps, schema_editor):
    Gateway = apps.get_model('financial', 'Gateway')
    PayIdGateway = apps.get_model('financial', 'PayIdGateway')

    gateway = Gateway.objects.exclude(payment_id_api_key='').first()
    if not gateway:
        return

    PayIdGateway.objects.update(payment_id_api_key=gateway.payment_id_api_key,
                                payment_id_secret_encrypted=gateway.payment_id_secret_encrypted)


class Migration(migrations.Migration):
    dependencies = [
        ('financial', '0148_rename_rejected_by_historicalbankaccount_verifier_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralBankAccount',
            new_name='PayIdGateway',
        ),
        migrations.AddField(
            model_name='payidgateway',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payidgateway',
            name='priority',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payidgateway',
            name='payment_id_api_key',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='payidgateway',
            name='payment_id_secret_encrypted',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='payidgateway',
            name='type',
            field=models.CharField(
                choices=[('jibit_old', 'jibit_old'), ('jibit_new', 'jibit_new'), ('parsian', 'parsian')],
                default='jibit_old', max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentid',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.payidgateway'),
        ),
        migrations.RenameField(
            model_name='paymentid',
            old_name='destination',
            new_name='gateway',
        ),
        migrations.RunPython(migrate_gateway_fields_to_payidgateway, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='gateway',
            name='pay_id_deposit_enable',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='payment_id_api_key',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='payment_id_secret_encrypted',
        ),
        migrations.RemoveField(
            model_name='paymentid',
            name='gateway',
        ),
        migrations.RemoveConstraint(
            model_name='paymentid',
            name='unique_financial_paymentid_user_gateway',
        ),
        migrations.RemoveConstraint(
            model_name='paymentid',
            name='unique_financial_paymentid_pay_id_gateway',
        ),
        migrations.AddConstraint(
            model_name='paymentid',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('user', 'destination'),
                                               name='unique_financial_paymentid_user_destination'),
        ),
        migrations.AddConstraint(
            model_name='paymentid',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('pay_id', 'destination'),
                                               name='unique_financial_paymentid_pay_id_destination'),
        ),
    ]
