# Generated by Django 4.1.3 on 2024-12-29 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0148_rename_rejected_by_historicalbankaccount_verifier_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralBankAccount',
            new_name='PayIdGateway',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='pay_id_deposit_enable',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='payment_id_api_key',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='payment_id_secret_encrypted',
        ),
        migrations.RemoveField(
            model_name='paymentid',
            name='gateway',
        ),
        migrations.AddField(
            model_name='payidgateway',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payidgateway',
            name='deposit_priority',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payidgateway',
            name='payment_id_api_key',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='payidgateway',
            name='payment_id_secret_encrypted',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='payidgateway',
            name='type',
            field=models.CharField(choices=[('jibit', 'jibit'), ('jibimo', 'jibimo')], default='jibit', max_length=8),
        ),
        migrations.AddField(
            model_name='payidgateway',
            name='withdraw_priority',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paymentid',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.payidgateway'),
        ),
    ]
