# Generated by Django 4.1.3 on 2024-12-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0149_remove_gateway_pay_id_deposit_enable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payidgateway',
            options={'ordering': ('priority',)},
        ),
        migrations.AddField(
            model_name='payidgateway',
            name='title',
            field=models.CharField(default='main', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payidgateway',
            name='deposit_address',
            field=models.CharField(blank=True, max_length=64, verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='payidgateway',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='نام صاحب حساب'),
        ),
        migrations.AlterField(
            model_name='payidgateway',
            name='priority',
            field=models.SmallIntegerField(default=0),
        ),
    ]
