# Generated by Django 4.1.3 on 2024-12-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0149_remove_gateway_pay_id_deposit_enable_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentid',
            name='unique_financial_paymentid_user_gateway',
        ),
        migrations.RemoveConstraint(
            model_name='paymentid',
            name='unique_financial_paymentid_pay_id_gateway',
        ),
        migrations.AddConstraint(
            model_name='paymentid',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('user', 'destination'), name='unique_financial_paymentid_user_destination'),
        ),
        migrations.AddConstraint(
            model_name='paymentid',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('pay_id', 'destination'), name='unique_financial_paymentid_pay_id_destination'),
        ),
    ]
