# Generated by Django 4.1.3 on 2024-12-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0150_alter_payidgateway_options_payidgateway_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayIdGateway',
            new_name='PaymentIdGateway',
        ),
    ]
