# Generated by Django 4.1.3 on 2024-12-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0150_remove_paymentid_unique_financial_paymentid_user_gateway_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payidgateway',
            old_name='deposit_priority',
            new_name='priority',
        ),
        migrations.RemoveField(
            model_name='payidgateway',
            name='withdraw_priority',
        ),
        migrations.AlterField(
            model_name='payidgateway',
            name='type',
            field=models.CharField(choices=[('jibit_old', 'jibit_old'), ('jibit_new', 'jibit_new'), ('parsian', 'parsian')], default='jibit_old', max_length=16),
        ),
    ]
