# Generated by Django 4.1.3 on 2024-12-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0151_rename_payidgateway_paymentidgateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='type',
            field=models.CharField(choices=[('manual', 'manual'), ('zarinpal', 'zarinpal'), ('payir', 'payir'), ('zibal', 'zibal'), ('zibal_bajeh', 'zibal_bajeh'), ('jibit', 'jibit'), ('jibimo', 'jibimo'), ('paystar', 'paystar'), ('novinpal', 'novinpal')], max_length=32),
        ),
    ]
