# Generated by Django 4.1.3 on 2025-01-01 07:55

from django.db import migrations, models
import django.db.models.deletion
import financial.validators


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0152_alter_gateway_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('bank', models.CharField(choices=[('MELLI', 'بانک ملی'), ('REFAH', 'بانک رفاه'), ('RESALAT', 'بانک رسالت'), ('KESHAVARZI', 'بانک کشاورزی'), ('TOSEAH_TAAVON', 'بانک توسعه تعاون'), ('TOSEAH_SADERAT', 'بانک توسعه صادرات'), ('SADERAT', 'بانک صادرات'), ('KARAFARIN', 'بانک کارآفرین'), ('EGHTESAD_NOVIN', 'بانک اقتصاد نوین'), ('SHAHR', 'بانک شهر'), ('SEPAH', 'بانک سپه'), ('MEHR_IRAN', 'بانک مهر ایران'), ('PASARGAD', 'بانک پاسارگاد'), ('NOOR', 'موسسه اعتباری نور'), ('SARMAYEH', 'بانک سرمایه'), ('MELAL', 'موسسه اعتباری ملل'), ('MASKAN', 'بانک مسکن'), ('POST', 'پست بانک ایران'), ('KHAVARMIANEH', 'بانک خاورمیانه'), ('SINA', 'بانک سینا'), ('MELLAT', 'بانک ملت'), ('IRANZAMIN', 'بانک ایران زمین'), ('DAY', 'بانک دی'), ('AYANDEH', 'بانک آینده'), ('GARDESHGARI', 'بانک گردشگری'), ('SAMAN', 'بانک سامان'), ('TEJARAT', 'بانک تجارت'), ('PARSIAN', 'بانک پارسیان'), ('SANAT_VA_MADAN', 'بانک صنعت و معدن')], max_length=16)),
                ('iban', models.CharField(blank=True, max_length=26, unique=True, validators=[financial.validators.iban_validator], verbose_name='شبا')),
                ('account_number', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deposit_type', models.CharField(choices=[('d', 'deposit'), ('w', 'withdraw')], db_index=True, max_length=1)),
                ('amount', models.PositiveBigIntegerField()),
                ('transaction_date', models.DateTimeField()),
                ('account_balance', models.PositiveBigIntegerField()),
                ('sender_iban', models.CharField(blank=True, max_length=26, validators=[financial.validators.iban_validator], verbose_name='شبا')),
                ('sender_account', models.CharField(blank=True, max_length=256)),
                ('sender_name', models.CharField(blank=True, max_length=256)),
                ('deposit_number', models.CharField(blank=True, max_length=256)),
                ('sender_bank', models.CharField(blank=True, max_length=256)),
                ('reference_number', models.CharField(max_length=64, unique=True)),
                ('tracking_id', models.CharField(max_length=64)),
                ('bank_branch', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.account')),
            ],
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='finance/statements/')),
                ('status', models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8)),
                ('message', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.account')),
            ],
        ),
    ]
