# Generated by Django 4.1.3 on 2025-01-01 11:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0153_account_banktransaction_bankstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='can_add_statement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='account',
            field=models.ForeignKey(limit_choices_to={'can_add_statement': True}, on_delete=django.db.models.deletion.CASCADE, to='financial.account'),
        ),
        migrations.AlterField(
            model_name='paymentidrequest',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
