# Generated by Django 4.1.3 on 2025-01-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0154_account_can_add_statement_banktransaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentidgateway',
            name='bank',
            field=models.CharField(choices=[('MELLI', 'بانک ملی'), ('REFAH', 'بانک رفاه'), ('RESALAT', 'بانک رسالت'), ('KESHAVARZI', 'بانک کشاورزی'), ('TOSEAH_TAAVON', 'بانک توسعه تعاون'), ('TOSEAH_SADERAT', 'بانک توسعه صادرات'), ('SADERAT', 'بانک صادرات'), ('KARAFARIN', 'بانک کارآفرین'), ('EGHTESAD_NOVIN', 'بانک اقتصاد نوین'), ('SHAHR', 'بانک شهر'), ('SEPAH', 'بانک سپه'), ('MEHR_IRAN', 'بانک مهر ایران'), ('PASARGAD', 'بانک پاسارگاد'), ('NOOR', 'موسسه اعتباری نور'), ('SARMAYEH', 'بانک سرمایه'), ('MELAL', 'موسسه اعتباری ملل'), ('MASKAN', 'بانک مسکن'), ('POST', 'پست بانک ایران'), ('KHAVARMIANEH', 'بانک خاورمیانه'), ('SINA', 'بانک سینا'), ('MELLAT', 'بانک ملت'), ('IRANZAMIN', 'بانک ایران زمین'), ('DAY', 'بانک دی'), ('AYANDEH', 'بانک آینده'), ('GARDESHGARI', 'بانک گردشگری'), ('SAMAN', 'بانک سامان'), ('TEJARAT', 'بانک تجارت'), ('PARSIAN', 'بانک پارسیان'), ('SANAT_VA_MADAN', 'بانک صنعت و معدن')], max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentidgateway',
            name='type',
            field=models.CharField(choices=[('jibit_old', 'jibit_old'), ('jibit', 'jibit'), ('manual', 'manual')], default='jibit_old', max_length=16),
        ),
    ]
