# Generated by Django 4.1.3 on 2025-01-02 09:41

from django.db import migrations
from django.db import migrations, models
import django.db.models.deletion
import financial.validators


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0155_alter_paymentidgateway_bank_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankTransaction',
        ),
        migrations.DeleteModel(
            name='BankStatement',
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='finance/statements/')),
                ('status', models.CharField(
                    choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'),
                             ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='paymentidgateway',
            name='can_add_statement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='gateway',
            field=models.ForeignKey(limit_choices_to={'can_add_statement': True},
                                    on_delete=django.db.models.deletion.CASCADE, to='financial.paymentidgateway'),
        ),
        migrations.AlterField(
            model_name='paymentidrequest',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='financial.paymentid'),
        ),
        migrations.AddConstraint(
            model_name='paymentidrequest',
            constraint=models.CheckConstraint(
                check=models.Q(('status', 'init'), ('owner__isnull', False), _connector='OR'),
                name='payment_id_request_owner_null_condition'),
        ),

    ]
