# Generated by Django 4.1.3 on 2025-01-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0156_auto_20250102_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentidrequest',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
