# Generated by Django 4.1.3 on 2025-01-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0157_paymentidrequest_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentidrequest',
            old_name='source_iban',
            new_name='sender_iban',
        ),
        migrations.AddField(
            model_name='paymentidrequest',
            name='bank_transaction_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='paymentidrequest',
            name='kyt_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentidrequest',
            name='raw_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentidrequest',
            name='raw_payment_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='paymentidrequest',
            name='record_type',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='paymentidrequest',
            name='sender_identifier',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='paymentidrequest',
            name='sender_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
