# Generated by Django 4.1.3 on 2025-01-05 21:19

from django.db import migrations, models
import django.db.models.deletion


def populate_payment_id_request(apps, schema_editor):
    PaymentIdRequest = apps.get_model('financial', 'PaymentIdRequest')

    for pr in PaymentIdRequest.objects.filter(owner__isnull=False).prefetch_related('owner'):
        pr.gateway = pr.owner.gateway
        pr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0158_rename_source_iban_paymentidrequest_sender_iban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentidrequest',
            name='balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentidrequest',
            name='gateway',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='financial.paymentidgateway'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='paymentidrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('bank_transaction_id', ''), _negated=True), fields=('bank_transaction_id',), name='unique_financial_paymentidrequest_bank_transaction_id'),
        ),

        migrations.RunPython(
            code=populate_payment_id_request,
            reverse_code=migrations.RunPython.noop
        ),
    ]
