# Generated by Django 4.1.3 on 2025-01-06 06:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0159_paymentidrequest_balance_paymentidrequest_gateway_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpaymentrequest',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='fiatwithdrawrequest',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalfiatwithdrawrequest',
            name='group_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='historicalpaymentrequest',
            name='group_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='manualtransfer',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentid',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
