# Generated by Django 4.1.3 on 2025-01-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0160_alter_bankpaymentrequest_group_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentidrequest',
            name='payment_id_request_owner_null_condition',
        ),
        migrations.AddConstraint(
            model_name='paymentidrequest',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['init', 'canceled']), ('owner__isnull', False), _connector='OR'), name='payment_id_request_owner_null_condition'),
        ),
    ]
