# Generated by Django 4.1.3 on 2025-01-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0146_alter_fiatwithdrawrequest_group_id_and_more'),
        ('financial', '0161_remove_paymentidrequest_payment_id_request_owner_null_condition_and_more'),
    ]

    operations = [
    ]
