# Generated by Django 4.1.3 on 2025-01-09 12:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0161_remove_paymentidrequest_payment_id_request_owner_null_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastPaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('type', models.CharField(choices=[('v', 'v'), ('a', 'a'), ('n', 'n'), ('d', 'd'), ('a', 'a'), ('r', 'r')], default='vandar', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.CharField(max_length=56)),
                ('refresh_token_encrypted', models.CharField(blank=True, max_length=4096)),
                ('priority', models.SmallIntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('priority',),
            },
        ),
        migrations.CreateModel(
            name='FastPaymentBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('is_healthy_on_direct_debit', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('max_withdrawal_amount', models.IntegerField(blank=True, null=True, verbose_name='سقف مجاز مجموع برداشت روزانه')),
                ('max_withdrawal_amount_per_transaction', models.IntegerField(blank=True, null=True, verbose_name='سقف مجاز هر برداشت')),
                ('withdrawal_amount_currency', models.CharField(blank=True, max_length=10, verbose_name='واحد پولی سقف برداشت')),
                ('max_withdrawal_daily_count', models.IntegerField(blank=True, null=True, verbose_name='حداکثر تعداد برداشت روزانه')),
                ('max_mandate_validity_duration', models.IntegerField(blank=True, null=True, verbose_name='حداکثر مدت اعتبار مجوز پرداخت از حساب')),
                ('mandate_validity_duration_unit', models.CharField(blank=True, max_length=50, verbose_name='واحد مدت اعتبار مجوز')),
                ('payer_authentication_type', models.CharField(blank=True, max_length=100, verbose_name='نوع احراز هویت پرداخت\u200cکننده')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='financial.fastpaymentgateway', verbose_name='درگاه مرتبط')),
            ],
            options={
                'verbose_name': 'بانک پرداخت سریع',
                'verbose_name_plural': 'بانک\u200cهای پرداخت سریع',
                'unique_together': {('code', 'gateway')},
            },
        ),
        migrations.CreateModel(
            name='AuthorizationId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('auth_id', models.CharField(blank=True, max_length=32, validators=[django.core.validators.validate_integer])),
                ('verified', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=255)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.fastpaymentbank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='authorizationid',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('user', 'bank'), name='unique_financial_paymentid_user_bank'),
        ),
        migrations.AddConstraint(
            model_name='authorizationid',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('auth_id', 'bank'), name='unique_financial_authorization_id_bank'),
        ),
    ]
