# Generated by Django 4.1.3 on 2025-01-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0161_remove_paymentidrequest_payment_id_request_owner_null_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentidrequest',
            name='deposit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
