# Generated by Django 4.1.3 on 2025-01-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0162_fastpaymentgateway_fastpaymentbank_authorizationid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastpaymentgateway',
            name='type',
            field=models.CharField(choices=[('vandar', 'vandar'), ('other', 'other')], default='vandar', max_length=16),
        ),
    ]
