# Generated by Django 4.1.3 on 2025-01-13 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import financial.utils.admin
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0162_alter_paymentidrequest_deposit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectDebitBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('bank', models.CharField(choices=[('MELLI', 'بانک ملی'), ('REFAH', 'بانک رفاه'), ('RESALAT', 'بانک رسالت'), ('KESHAVARZI', 'بانک کشاورزی'), ('TOSEAH_TAAVON', 'بانک توسعه تعاون'), ('TOSEAH_SADERAT', 'بانک توسعه صادرات'), ('SADERAT', 'بانک صادرات'), ('KARAFARIN', 'بانک کارآفرین'), ('EGHTESAD_NOVIN', 'بانک اقتصاد نوین'), ('SHAHR', 'بانک شهر'), ('SEPAH', 'بانک سپه'), ('MEHR_IRAN', 'بانک مهر ایران'), ('PASARGAD', 'بانک پاسارگاد'), ('NOOR', 'موسسه اعتباری نور'), ('SARMAYEH', 'بانک سرمایه'), ('MELAL', 'موسسه اعتباری ملل'), ('MASKAN', 'بانک مسکن'), ('POST', 'پست بانک ایران'), ('KHAVARMIANEH', 'بانک خاورمیانه'), ('SINA', 'بانک سینا'), ('MELLAT', 'بانک ملت'), ('IRANZAMIN', 'بانک ایران زمین'), ('DAY', 'بانک دی'), ('AYANDEH', 'بانک آینده'), ('GARDESHGARI', 'بانک گردشگری'), ('SAMAN', 'بانک سامان'), ('TEJARAT', 'بانک تجارت'), ('PARSIAN', 'بانک پارسیان'), ('SANAT_VA_MADAN', 'بانک صنعت و معدن'), ('BLUE', 'بلو بانک'), ('FARDA', 'فردا بانک')], max_length=16)),
                ('max_withdrawal_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='سقف مجاز مجموع برداشت روزانه')),
                ('max_withdrawal_amount_per_transaction', models.PositiveIntegerField(blank=True, null=True, verbose_name='سقف مجاز هر برداشت')),
                ('max_withdrawal_daily_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر تعداد برداشت روزانه')),
                ('max_validity_duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت اعتبار مجوز')),
                ('kyc_type', models.CharField(blank=True, max_length=100, verbose_name='نوع احراز هویت پرداخت\u200cکننده')),
            ],
        ),
        migrations.CreateModel(
            name='DirectDebitConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('auth_id_encrypted', models.CharField(blank=True, max_length=4096)),
                ('verified', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=255)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.directdebitbank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DirectDebitGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vandar', 'vandar')], default='vandar', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('priority', models.SmallIntegerField(default=0)),
                ('title', models.CharField(max_length=16)),
                ('business_name', models.CharField(max_length=56)),
                ('refresh_token_encrypted', models.CharField(blank=True, max_length=4096)),
            ],
            options={
                'ordering': ('priority',),
            },
        ),
        migrations.AlterField(
            model_name='gateway',
            name='instant_withdraw_banks',
            field=financial.utils.admin.MultiSelectArrayField(base_field=models.CharField(choices=[('MELLI', 'MELLI'), ('REFAH', 'REFAH'), ('RESALAT', 'RESALAT'), ('KESHAVARZI', 'KESHAVARZI'), ('TOSEAH_TAAVON', 'TOSEAH_TAAVON'), ('TOSEAH_SADERAT', 'TOSEAH_SADERAT'), ('SADERAT', 'SADERAT'), ('KARAFARIN', 'KARAFARIN'), ('EGHTESAD_NOVIN', 'EGHTESAD_NOVIN'), ('SHAHR', 'SHAHR'), ('SEPAH', 'SEPAH'), ('MEHR_IRAN', 'MEHR_IRAN'), ('PASARGAD', 'PASARGAD'), ('NOOR', 'NOOR'), ('SARMAYEH', 'SARMAYEH'), ('MELAL', 'MELAL'), ('MASKAN', 'MASKAN'), ('POST', 'POST'), ('KHAVARMIANEH', 'KHAVARMIANEH'), ('SINA', 'SINA'), ('MELLAT', 'MELLAT'), ('IRANZAMIN', 'IRANZAMIN'), ('DAY', 'DAY'), ('AYANDEH', 'AYANDEH'), ('GARDESHGARI', 'GARDESHGARI'), ('SAMAN', 'SAMAN'), ('TEJARAT', 'TEJARAT'), ('PARSIAN', 'PARSIAN'), ('SANAT_VA_MADAN', 'SANAT_VA_MADAN'), ('BLUE', 'BLUE'), ('FARDA', 'FARDA')], max_length=16), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='source',
            field=models.CharField(choices=[('ipg', 'ipg'), ('pay_id', 'pay_id'), ('manual', 'manual'), ('direct_debit', 'direct_debit')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='source',
            field=models.CharField(choices=[('ipg', 'ipg'), ('pay_id', 'pay_id'), ('manual', 'manual'), ('direct_debit', 'direct_debit')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentidgateway',
            name='bank',
            field=models.CharField(choices=[('MELLI', 'بانک ملی'), ('REFAH', 'بانک رفاه'), ('RESALAT', 'بانک رسالت'), ('KESHAVARZI', 'بانک کشاورزی'), ('TOSEAH_TAAVON', 'بانک توسعه تعاون'), ('TOSEAH_SADERAT', 'بانک توسعه صادرات'), ('SADERAT', 'بانک صادرات'), ('KARAFARIN', 'بانک کارآفرین'), ('EGHTESAD_NOVIN', 'بانک اقتصاد نوین'), ('SHAHR', 'بانک شهر'), ('SEPAH', 'بانک سپه'), ('MEHR_IRAN', 'بانک مهر ایران'), ('PASARGAD', 'بانک پاسارگاد'), ('NOOR', 'موسسه اعتباری نور'), ('SARMAYEH', 'بانک سرمایه'), ('MELAL', 'موسسه اعتباری ملل'), ('MASKAN', 'بانک مسکن'), ('POST', 'پست بانک ایران'), ('KHAVARMIANEH', 'بانک خاورمیانه'), ('SINA', 'بانک سینا'), ('MELLAT', 'بانک ملت'), ('IRANZAMIN', 'بانک ایران زمین'), ('DAY', 'بانک دی'), ('AYANDEH', 'بانک آینده'), ('GARDESHGARI', 'بانک گردشگری'), ('SAMAN', 'بانک سامان'), ('TEJARAT', 'بانک تجارت'), ('PARSIAN', 'بانک پارسیان'), ('SANAT_VA_MADAN', 'بانک صنعت و معدن'), ('BLUE', 'بلو بانک'), ('FARDA', 'فردا بانک')], max_length=16),
        ),
        migrations.CreateModel(
            name='DirectDebitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8)),
                ('amount', models.PositiveBigIntegerField()),
                ('fee', models.PositiveBigIntegerField()),
                ('group_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.directdebitgateway')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financial.directdebitconnection')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.payment')),
            ],
        ),
        migrations.AddField(
            model_name='directdebitbank',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='financial.directdebitgateway', verbose_name='درگاه'),
        ),
        migrations.AddConstraint(
            model_name='directdebitrequest',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['init', 'canceled']), ('owner__isnull', False), _connector='OR'), name='direct_debit_request_owner_null_condition'),
        ),
        migrations.AddConstraint(
            model_name='directdebitconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('user', 'bank'), name='unique_financial_paymentid_user_bank'),
        ),
        migrations.AddConstraint(
            model_name='directdebitconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('auth_id_encrypted', 'bank'), name='unique_financial_authorization_id_bank'),
        ),
        migrations.AlterUniqueTogether(
            name='directdebitbank',
            unique_together={('bank', 'gateway')},
        ),
    ]
