# Generated by Django 4.1.3 on 2025-01-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0163_alter_paymentidrequest_deposit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentidrequest',
            name='refund_track_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='paymentidrequest',
            name='refund_type',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
