# Generated by Django 4.1.3 on 2025-01-12 12:42
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0163_directdebitbank_directdebitconnection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentidrequest',
            name='deposit_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentidrequest',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       to='financial.payment'),
        ),
    ]
