# Generated by Django 4.1.3 on 2025-01-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0163_alter_fastpaymentgateway_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fastpaymentbank',
            name='deleted',
        ),
    ]
