# Generated by Django 4.1.3 on 2025-01-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0163_alter_paymentidrequest_deposit_time'),
        ('financial', '0163_directdebitbank_directdebitconnection_and_more'),
    ]

    operations = [
    ]
