# Generated by Django 4.1.3 on 2025-01-12 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0163_authorizationid_directdebitgateway_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorizationId',
            new_name='DirectDebitConnection',
        ),
        migrations.AlterModelOptions(
            name='directdebitbank',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='directdebitconnection',
            name='unique_financial_authorization_id_bank',
        ),
        migrations.RenameField(
            model_name='directdebitbank',
            old_name='payer_authentication_type',
            new_name='kyc_type',
        ),
        migrations.RenameField(
            model_name='directdebitconnection',
            old_name='auth_id',
            new_name='auth_id_encrypted',
        ),
        migrations.AlterUniqueTogether(
            name='directdebitbank',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='directdebitrequest',
            name='balance',
        ),
        migrations.AddField(
            model_name='directdebitbank',
            name='bank',
            field=models.CharField(choices=[('MELLI', 'بانک ملی'), ('REFAH', 'بانک رفاه'), ('RESALAT', 'بانک رسالت'), ('KESHAVARZI', 'بانک کشاورزی'), ('TOSEAH_TAAVON', 'بانک توسعه تعاون'), ('TOSEAH_SADERAT', 'بانک توسعه صادرات'), ('SADERAT', 'بانک صادرات'), ('KARAFARIN', 'بانک کارآفرین'), ('EGHTESAD_NOVIN', 'بانک اقتصاد نوین'), ('SHAHR', 'بانک شهر'), ('SEPAH', 'بانک سپه'), ('MEHR_IRAN', 'بانک مهر ایران'), ('PASARGAD', 'بانک پاسارگاد'), ('NOOR', 'موسسه اعتباری نور'), ('SARMAYEH', 'بانک سرمایه'), ('MELAL', 'موسسه اعتباری ملل'), ('MASKAN', 'بانک مسکن'), ('POST', 'پست بانک ایران'), ('KHAVARMIANEH', 'بانک خاورمیانه'), ('SINA', 'بانک سینا'), ('MELLAT', 'بانک ملت'), ('IRANZAMIN', 'بانک ایران زمین'), ('DAY', 'بانک دی'), ('AYANDEH', 'بانک آینده'), ('GARDESHGARI', 'بانک گردشگری'), ('SAMAN', 'بانک سامان'), ('TEJARAT', 'بانک تجارت'), ('PARSIAN', 'بانک پارسیان'), ('SANAT_VA_MADAN', 'بانک صنعت و معدن')], default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directdebitbank',
            name='max_validity_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت اعتبار مجوز'),
        ),
        migrations.AlterField(
            model_name='directdebitbank',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='directdebitbank',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='financial.directdebitgateway', verbose_name='درگاه'),
        ),
        migrations.AlterField(
            model_name='directdebitbank',
            name='max_withdrawal_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سقف مجاز مجموع برداشت روزانه'),
        ),
        migrations.AlterField(
            model_name='directdebitbank',
            name='max_withdrawal_amount_per_transaction',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سقف مجاز هر برداشت'),
        ),
        migrations.AlterField(
            model_name='directdebitbank',
            name='max_withdrawal_daily_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر تعداد برداشت روزانه'),
        ),
        migrations.AlterField(
            model_name='directdebitgateway',
            name='type',
            field=models.CharField(choices=[('vandar', 'vandar')], default='vandar', max_length=16),
        ),
        migrations.AlterField(
            model_name='directdebitrequest',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.payment'),
        ),
        migrations.AddConstraint(
            model_name='directdebitconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('auth_id_encrypted', 'bank'), name='unique_financial_authorization_id_bank'),
        ),
        migrations.RemoveField(
            model_name='directdebitbank',
            name='code',
        ),
        migrations.RemoveField(
            model_name='directdebitbank',
            name='is_healthy_on_direct_debit',
        ),
        migrations.RemoveField(
            model_name='directdebitbank',
            name='mandate_validity_duration_unit',
        ),
        migrations.RemoveField(
            model_name='directdebitbank',
            name='max_mandate_validity_duration',
        ),
        migrations.RemoveField(
            model_name='directdebitbank',
            name='name',
        ),
        migrations.RemoveField(
            model_name='directdebitbank',
            name='withdrawal_amount_currency',
        ),
    ]
