# Generated by Django 4.1.3 on 2025-01-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0164_paymentidrequest_refund_track_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentidrequest',
            name='record_type',
            field=models.CharField(blank=True, choices=[('ach', 'ach'), ('card', 'card'), ('internal', 'internal'), ('rtgs', 'rtgs'), ('pol', 'pol')], max_length=256),
        ),
    ]
