# Generated by Django 4.1.3 on 2025-01-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0164_rename_authorizationid_directdebitconnection_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directdebitbank',
            unique_together=set(),
        ),
    ]
