# Generated by Django 4.1.3 on 2025-01-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0165_alter_directdebitbank_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directdebitbank',
            unique_together={('bank', 'gateway')},
        ),
    ]
