# Generated by Django 4.1.3 on 2025-01-13 11:08

import django.core.validators
from django.db import migrations, models
import financial.utils.admin


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0166_alter_directdebitbank_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directdebitbank',
            name='bank',
            field=models.CharField(choices=[('MELLI', 'بانک ملی'), ('REFAH', 'بانک رفاه'), ('RESALAT', 'بانک رسالت'), ('KESHAVARZI', 'بانک کشاورزی'), ('TOSEAH_TAAVON', 'بانک توسعه تعاون'), ('TOSEAH_SADERAT', 'بانک توسعه صادرات'), ('SADERAT', 'بانک صادرات'), ('KARAFARIN', 'بانک کارآفرین'), ('EGHTESAD_NOVIN', 'بانک اقتصاد نوین'), ('SHAHR', 'بانک شهر'), ('SEPAH', 'بانک سپه'), ('MEHR_IRAN', 'بانک مهر ایران'), ('PASARGAD', 'بانک پاسارگاد'), ('NOOR', 'موسسه اعتباری نور'), ('SARMAYEH', 'بانک سرمایه'), ('MELAL', 'موسسه اعتباری ملل'), ('MASKAN', 'بانک مسکن'), ('POST', 'پست بانک ایران'), ('KHAVARMIANEH', 'بانک خاورمیانه'), ('SINA', 'بانک سینا'), ('MELLAT', 'بانک ملت'), ('IRANZAMIN', 'بانک ایران زمین'), ('DAY', 'بانک دی'), ('AYANDEH', 'بانک آینده'), ('GARDESHGARI', 'بانک گردشگری'), ('SAMAN', 'بانک سامان'), ('TEJARAT', 'بانک تجارت'), ('PARSIAN', 'بانک پارسیان'), ('SANAT_VA_MADAN', 'بانک صنعت و معدن'), ('BLUE', 'بلو بانک'), ('FARDA', 'فردا بانک')], max_length=16),
        ),
        migrations.AlterField(
            model_name='directdebitconnection',
            name='auth_id_encrypted',
            field=models.CharField(blank=True, max_length=4096, validators=[django.core.validators.validate_integer]),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='instant_withdraw_banks',
            field=financial.utils.admin.MultiSelectArrayField(base_field=models.CharField(choices=[('MELLI', 'MELLI'), ('REFAH', 'REFAH'), ('RESALAT', 'RESALAT'), ('KESHAVARZI', 'KESHAVARZI'), ('TOSEAH_TAAVON', 'TOSEAH_TAAVON'), ('TOSEAH_SADERAT', 'TOSEAH_SADERAT'), ('SADERAT', 'SADERAT'), ('KARAFARIN', 'KARAFARIN'), ('EGHTESAD_NOVIN', 'EGHTESAD_NOVIN'), ('SHAHR', 'SHAHR'), ('SEPAH', 'SEPAH'), ('MEHR_IRAN', 'MEHR_IRAN'), ('PASARGAD', 'PASARGAD'), ('NOOR', 'NOOR'), ('SARMAYEH', 'SARMAYEH'), ('MELAL', 'MELAL'), ('MASKAN', 'MASKAN'), ('POST', 'POST'), ('KHAVARMIANEH', 'KHAVARMIANEH'), ('SINA', 'SINA'), ('MELLAT', 'MELLAT'), ('IRANZAMIN', 'IRANZAMIN'), ('DAY', 'DAY'), ('AYANDEH', 'AYANDEH'), ('GARDESHGARI', 'GARDESHGARI'), ('SAMAN', 'SAMAN'), ('TEJARAT', 'TEJARAT'), ('PARSIAN', 'PARSIAN'), ('SANAT_VA_MADAN', 'SANAT_VA_MADAN'), ('BLUE', 'BLUE'), ('FARDA', 'FARDA')], max_length=16), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='paymentidgateway',
            name='bank',
            field=models.CharField(choices=[('MELLI', 'بانک ملی'), ('REFAH', 'بانک رفاه'), ('RESALAT', 'بانک رسالت'), ('KESHAVARZI', 'بانک کشاورزی'), ('TOSEAH_TAAVON', 'بانک توسعه تعاون'), ('TOSEAH_SADERAT', 'بانک توسعه صادرات'), ('SADERAT', 'بانک صادرات'), ('KARAFARIN', 'بانک کارآفرین'), ('EGHTESAD_NOVIN', 'بانک اقتصاد نوین'), ('SHAHR', 'بانک شهر'), ('SEPAH', 'بانک سپه'), ('MEHR_IRAN', 'بانک مهر ایران'), ('PASARGAD', 'بانک پاسارگاد'), ('NOOR', 'موسسه اعتباری نور'), ('SARMAYEH', 'بانک سرمایه'), ('MELAL', 'موسسه اعتباری ملل'), ('MASKAN', 'بانک مسکن'), ('POST', 'پست بانک ایران'), ('KHAVARMIANEH', 'بانک خاورمیانه'), ('SINA', 'بانک سینا'), ('MELLAT', 'بانک ملت'), ('IRANZAMIN', 'بانک ایران زمین'), ('DAY', 'بانک دی'), ('AYANDEH', 'بانک آینده'), ('GARDESHGARI', 'بانک گردشگری'), ('SAMAN', 'بانک سامان'), ('TEJARAT', 'بانک تجارت'), ('PARSIAN', 'بانک پارسیان'), ('SANAT_VA_MADAN', 'بانک صنعت و معدن'), ('BLUE', 'بلو بانک'), ('FARDA', 'فردا بانک')], max_length=16),
        ),
    ]
