# Generated by Django 4.1.3 on 2025-01-19 12:00

from django.db import migrations, models
import financial.validators


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0166_remove_paymentidrequest_payment_id_request_owner_null_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentidgateway',
            name='card_pan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RenameField(
            model_name='paymentidgateway',
            old_name='type',
            new_name='channel'
        ),
        migrations.AlterField(
            model_name='paymentidgateway',
            name='iban',
            field=models.CharField(blank=True, max_length=26, validators=[financial.validators.iban_validator], verbose_name='شبا'),
        ),
        migrations.AddField(
            model_name='paymentidgateway',
            name='type',
            field=models.CharField(choices=[('paymentId', 'شناسه واریز'), ('pol', 'پل'), ('card', 'کارت به کارت')], default='paymentId', max_length=16),
        ),

    ]
