# Generated by Django 4.1.3 on 2025-01-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0167_paymentidgateway_card_pan_paymentidgateway_channel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentidgateway',
            options={'ordering': ('ordering',)},
        ),
        migrations.RenameField(
            model_name='paymentidgateway',
            old_name='priority',
            new_name='ordering',
        ),
    ]
