# Generated by Django 4.1.3 on 2025-01-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0164_merge_20250113_1748'),
        ('financial', '0168_alter_paymentidgateway_options_and_more'),
    ]

    operations = [
    ]
