# Generated by Django 4.1.3 on 2025-01-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0169_merge_20250119_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='type',
            field=models.CharField(choices=[('manual', 'manual'), ('zarinpal', 'zarinpal'), ('payir', 'payir'), ('zibal', 'zibal'), ('zibal_bajeh', 'zibal_bajeh'), ('jibit', 'jibit'), ('jibit_v2', 'jibit_v2'), ('jibimo', 'jibimo'), ('paystar', 'paystar'), ('novinpal', 'novinpal')], max_length=32),
        ),
    ]
