# Generated by Django 4.1.3 on 2025-01-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0170_alter_gateway_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentidgateway',
            options={'ordering': ('ordering', 'id')},
        ),
        migrations.AddField(
            model_name='paymentidgateway',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
