# Generated by Django 4.1.3 on 2025-01-20 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_users(apps, schema_editor):
    PaymentIdRequest = apps.get_model('financial', 'PaymentIdRequest')

    for p in PaymentIdRequest.objects.filter(owner__isnull=False):
        p.user = p.owner.user
        p.save(update_fields=['user'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0171_alter_paymentidgateway_options_paymentidgateway_hide'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='directdebitconnection',
            name='unique_financial_authorization_id_bank',
        ),
        migrations.RemoveConstraint(
            model_name='paymentidrequest',
            name='payment_id_request_owner_null_condition',
        ),
        migrations.AddField(
            model_name='paymentidrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            code=populate_users,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='paymentidrequest',
            name='owner',
        ),
        migrations.AddConstraint(
            model_name='directdebitconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), models.Q(('auth_id_encrypted', ''), _negated=True)), fields=('auth_id_encrypted', 'bank'), name='unique_financial_authorization_id_bank'),
        ),
        migrations.AddConstraint(
            model_name='paymentidrequest',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['init', 'canceled', 'refund']), ('user__isnull', False), _connector='OR'), name='payment_id_request_owner_null_condition'),
        ),
    ]
