# Generated by Django 4.1.3 on 2025-01-20 16:47

from django.db import migrations, models
import financial.validators


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0172_remove_directdebitconnection_unique_financial_authorization_id_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentidgateway',
            name='iban',
            field=models.CharField(max_length=26, unique=True, validators=[financial.validators.iban_validator], verbose_name='شبا'),
        ),
    ]
