# Generated by Django 4.1.3 on 2025-01-21 13:30

from django.db import migrations, models
import financial.validators


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0173_alter_paymentidgateway_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentidgateway',
            name='iban',
            field=models.CharField(blank=True, max_length=26, validators=[financial.validators.iban_validator], verbose_name='شبا'),
        ),
        migrations.AddConstraint(
            model_name='paymentidgateway',
            constraint=models.UniqueConstraint(condition=models.Q(('iban', ''), _negated=True), fields=('iban',), name='uniqueness_paymentidgateway_iban'),
        ),
    ]
