# Generated by Django 4.1.3 on 2025-01-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0162_merge_20250106_1540'),
        ('financial', '0173_alter_paymentidgateway_iban'),
    ]

    operations = [
    ]
