# Generated by Django 4.1.3 on 2025-01-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0174_alter_paymentidgateway_iban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatwithdrawrequest',
            name='provider_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='historicalfiatwithdrawrequest',
            name='provider_status',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
