# Generated by Django 4.1.3 on 2025-01-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0175_fiatwithdrawrequest_provider_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentidgateway',
            name='channel',
            field=models.CharField(choices=[('jibit_old', 'jibit_old'), ('jibit', 'jibit'), ('statement', 'statement'), ('mock', 'mock')], default='jibit_old', max_length=16),
        ),
    ]
