# Generated by Django 4.1.3 on 2025-02-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0174_merge_20250121_1229'),
        ('financial', '0176_alter_paymentidgateway_channel'),
    ]

    operations = [
    ]
