# Generated by Django 4.1.3 on 2024-01-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPublisherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True)),
                ('views', models.PositiveIntegerField()),
                ('clicks', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=256)),
                ('utm_campaign', models.CharField(max_length=256)),
                ('utm_content', models.CharField(max_length=256)),
                ('campaign_id', models.PositiveIntegerField()),
                ('publisher_id', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('created', 'type', 'utm_campaign', 'utm_content', 'campaign_id', 'publisher_id')},
            },
        ),
        migrations.CreateModel(
            name='AdsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True)),
                ('views', models.PositiveIntegerField()),
                ('clicks', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=256)),
                ('utm_campaign', models.CharField(max_length=256)),
                ('utm_term', models.CharField(max_length=256)),
                ('campaign_id', models.PositiveIntegerField()),
                ('ad_id', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('created', 'type', 'utm_campaign', 'utm_term', 'campaign_id', 'ad_id')},
            },
        ),
    ]
