# Generated by Django 4.1.3 on 2024-08-24 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('utm_source', models.CharField(blank=True, max_length=256)),
                ('utm_medium', models.CharField(blank=True, max_length=256)),
                ('utm_campaign', models.CharField(blank=True, max_length=256)),
                ('campaign_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('cost', models.PositiveIntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.campaigninfo')),
            ],
            options={
                'unique_together': {('created', 'campaign')},
            },
        ),
    ]
