# Generated by Django 4.1.3 on 2024-08-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_campaigninfo_campaigncost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaigninfo',
            options={'ordering': ('-id',)},
        ),
        migrations.RenameField(
            model_name='campaigncost',
            old_name='cost',
            new_name='cost_irt',
        ),
        migrations.AlterField(
            model_name='campaigncost',
            name='cost_irt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaigncost',
            name='cost_usdt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
