# Generated by Django 4.1.3 on 2024-08-24 12:07

from django.db import migrations, models
from django.db.models import F

from ledger.utils.price import get_last_price, USDT_IRT


def populate_cost_usdt(apps, schema_editor):
    CampaignCost = apps.get_model('marketing', 'CampaignCost')
    price = get_last_price(USDT_IRT) or 60_000
    CampaignCost.objects.update(cost_usdt=F('cost_irt') / price)


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_campaigninfo_campaigncost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaigninfo',
            options={'ordering': ('-id',)},
        ),
        migrations.RenameField(
            model_name='campaigncost',
            old_name='cost',
            new_name='cost_irt',
        ),
        migrations.AlterField(
            model_name='campaigncost',
            name='cost_irt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaigncost',
            name='cost_usdt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(
            code=populate_cost_usdt,
            reverse_code=migrations.RunPython.noop
        )
    ]
