# Generated by Django 4.1.3 on 2024-08-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_campaigninfo_options_remove_campaigncost_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncost',
            name='cost_usdt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
