# Generated by Django 4.1.3 on 2024-08-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_alter_campaigncost_cost_usdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigninfo',
            name='fee_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
