# Generated by Django 4.0 on 2022-01-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_system_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, choices=[('s', 'system'), ('o', 'out'), (None, 'ordinary')], max_length=1, null=True, unique=True),
        ),
    ]
