# Generated by Django 4.0 on 2022-01-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_margin_warn',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
