# Generated by Django 4.0 on 2022-02-13 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
        ('accounts', '0005_user_verification_basicaccountinfo_bankcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicaccountinfo',
            name='national_card_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='multimedia.image'),
        ),
    ]
