# Generated by Django 4.0 on 2022-02-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_basicaccountinfo_national_card_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankcard',
            old_name='card_number',
            new_name='card_pan',
        ),
    ]
