# Generated by Django 4.0 on 2022-02-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankcard',
            name='user',
        ),
    ]
