# Generated by Django 4.0 on 2022-02-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_bankcard_alter_paymentrequest_bank_card'),
        ('accounts', '0009_remove_bankcard_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankCard',
        ),
    ]
