# Generated by Django 4.0 on 2022-02-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_bankcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='verification',
            field=models.PositiveSmallIntegerField(choices=[(0, 'not verified'), (1, 'basic verified')], default=0),
        ),
    ]
