# Generated by Django 4.0 on 2022-02-23 14:00

import accounts.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_notification_title_alter_user_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinotechRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('track_id', models.UUIDField(default=uuid.uuid4)),
                ('url', models.CharField(max_length=256)),
                ('data', models.JSONField(blank=True, null=True)),
                ('method', models.CharField(max_length=8)),
                ('status_code', models.PositiveSmallIntegerField(default=0)),
                ('response', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, validators=[accounts.validators.national_card_code_validator]),
        ),
        migrations.AddField(
            model_name='user',
            name='national_code_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_status',
            field=models.CharField(choices=[('init', 'init'), ('pending', 'pending'), ('rejected', 'rejected'), ('verified', 'verified')], default='init', max_length=8),
        ),
        migrations.DeleteModel(
            name='BasicAccountInfo',
        ),
        migrations.AddField(
            model_name='finotechrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
