# Generated by Django 4.0 on 2022-02-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_finotechrequest_remove_user_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finotechrequest',
            name='search_key',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
