# Generated by Django 4.0 on 2022-03-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_finotechrequest_search_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_fiat_deposit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
