# Generated by Django 4.0 on 2022-03-06 12:38

import accounts.validators
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
        ('accounts', '0015_user_national_card_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر کاربر',
                'verbose_name_plural': 'نظر\u200cهای کاربر',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUserComment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'historical نظر کاربر',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(db_index=True, error_messages={'unique': 'شماره موبایل وارد شده از قبل در سیستم موجود است.'}, max_length=16, validators=[accounts.validators.mobile_number_validator], verbose_name='شماره موبایل')),
                ('email_verified', models.BooleanField(default=False, verbose_name='تاییدیه ایمیل')),
                ('email_verification_date', models.DateTimeField(blank=True, null=True)),
                ('first_name_verified', models.BooleanField(blank=True, null=True, verbose_name='تاییدیه نام')),
                ('last_name_verified', models.BooleanField(blank=True, null=True, verbose_name='تاییدیه نام خانوادگی')),
                ('national_code', models.CharField(blank=True, max_length=10, validators=[accounts.validators.national_card_code_validator], verbose_name='کد ملی')),
                ('national_code_verified', models.BooleanField(blank=True, null=True, verbose_name='تاییدیه کد ملی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('birth_date_verified', models.BooleanField(blank=True, null=True, verbose_name='تاییدیه تاریخ تولد')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3')], default=1, verbose_name='سطح')),
                ('verify_status', models.CharField(choices=[('init', 'init'), ('pending', 'pending'), ('rejected', 'rejected'), ('verified', 'verified')], default='init', max_length=8, verbose_name='وضعیت تایید')),
                ('first_fiat_deposit_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان اولین برداشت ریالی')),
                ('telephone', models.CharField(blank=True, db_index=True, error_messages={'unique': 'شماره موبایل وارد شده از قبل در سیستم موجود است.'}, max_length=16, null=True, validators=[accounts.validators.telephone_number_validator], verbose_name='شماره تلفن')),
                ('national_card_image_verified', models.BooleanField(blank=True, null=True, verbose_name='تاییدیه عکس کارت ملی')),
                ('selfie_image_verified', models.BooleanField(blank=True, null=True, verbose_name='تاییدیه عکس سلفی')),
                ('telephone_verified', models.BooleanField(blank=True, null=True, verbose_name='تاییدیه شماره تلفن')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user')),
                ('national_card_image', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='multimedia.image', verbose_name='عکس کارت ملی')),
                ('selfie_image', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='multimedia.image', verbose_name='عکس سلفی')),
            ],
            options={
                'verbose_name': 'historical user',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
