# Generated by Django 4.0 on 2022-03-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_historicaluser_level_2_verify_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='national_card_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_card_image',
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='first_fiat_deposit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان اولین واریز ریالی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_fiat_deposit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان اولین واریز ریالی'),
        ),
    ]
