# Generated by Django 4.0 on 2022-03-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_historicaluser_national_card_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='national_card_image_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_card_image_verified',
        ),
    ]
