# Generated by Django 4.0 on 2022-03-09 13:41

import accounts.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_historicaluser_national_card_image_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='telephone',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, validators=[accounts.validators.telephone_number_validator], verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, validators=[accounts.validators.telephone_number_validator], verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(db_index=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{4,6}$')]),
        ),
    ]
