# Generated by Django 4.0 on 2022-03-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_verificationcode_user_alter_historicaluser_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finotechrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='finotechrequest',
            name='status_code',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='وضعیت'),
        ),
    ]
