# Generated by Django 4.0 on 2022-03-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_finotechrequest_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='margin_quiz_pass_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='margin_quiz_pass_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
