# Generated by Django 4.0 on 2022-03-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_finotechrequest_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='بایگانی'),
        ),
        migrations.AddField(
            model_name='user',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='بایگانی'),
        ),
    ]
