# Generated by Django 4.0 on 2022-03-13 11:23

import accounts.utils.validation
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_finotechrequest_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='email_verification_date',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.DateTimeField(default=accounts.utils.validation.fifteen_minutes_later_datetime)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='ایمیل')),
                ('code', models.CharField(db_index=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{4,6}$')])),
                ('code_used', models.BooleanField(default=False)),
                ('scope', models.CharField(choices=[('forget', 'forget'), ('verify', 'verify')], max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
