# Generated by Django 4.0 on 2022-03-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_historicaluser_email_verification_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.EmailField(blank=True, default='a@g.com', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='a@gmail.com', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
