# Generated by Django 4.0 on 2022-04-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_historicaluser_margin_quiz_pass_date_and_more'),
        ('accounts', '0023_alter_historicaluser_national_code_verified_and_more'),
    ]

    operations = [
    ]
