# Generated by Django 4.0 on 2022-04-04 14:01

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_historicaluser_show_margin_user_show_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='national_code_duplicated_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='national_code_duplicated_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='national_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, validators=[accounts.validators.national_card_code_validator], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='national_code_verified',
            field=models.BooleanField(blank=True, null=True, verbose_name='تاییدیه کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, validators=[accounts.validators.national_card_code_validator], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code_verified',
            field=models.BooleanField(blank=True, null=True, verbose_name='تاییدیه کد ملی'),
        ),
    ]
