# Generated by Django 4.0 on 2022-04-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_historicaluser_national_code_duplicated_alert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='national_code_duplicated_alert',
            field=models.BooleanField(default=False, verbose_name='آیا شماره ملی تکراری است؟'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='show_margin',
            field=models.BooleanField(default=False, verbose_name='امکان مشاهده حساب تعهدی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code_duplicated_alert',
            field=models.BooleanField(default=False, verbose_name='آیا شماره ملی تکراری است؟'),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_margin',
            field=models.BooleanField(default=False, verbose_name='امکان مشاهده حساب تعهدی'),
        ),
    ]
