# Generated by Django 4.0 on 2022-04-06 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_historicaluser_national_code_duplicated_alert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('utm_source', models.CharField(max_length=256)),
                ('utm_medium', models.CharField(max_length=256)),
                ('utm_campaign', models.CharField(max_length=256)),
                ('utm_content', models.CharField(max_length=256)),
                ('utm_term', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'منشا ترافیک',
                'verbose_name_plural': 'منشا ترافیک',
            },
        ),
    ]
