# Generated by Django 4.0 on 2022-04-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_historicaluser_email_alter_user_email'),
        ('accounts', '0027_alter_historicaluser_national_code_duplicated_alert_and_more'),
    ]

    operations = [
    ]
