# Generated by Django 4.0 on 2022-04-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_rename_sentsms_externalnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='first_trade_prize_activate',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='level_2_prize_activate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_trade_prize_activate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='level_2_prize_activate',
        ),
    ]
