# Generated by Django 4.0 on 2022-04-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_rename_sentsms_externalnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='on_boarding_flow',
            field=models.CharField(blank=True, choices=[('fiat', 'fiat'), ('crypto', 'crypto')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='on_boarding_flow',
            field=models.CharField(blank=True, choices=[('fiat', 'fiat'), ('crypto', 'crypto')], default='', max_length=10),
        ),
    ]
