# Generated by Django 4.0 on 2022-04-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_historicaluser_on_boarding_flow_and_more'),
        ('accounts', '0032_remove_historicaluser_first_trade_prize_activate_and_more'),
    ]

    operations = [
    ]
