# Generated by Django 4.0 on 2022-04-16 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_referral_account_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_accounts', to='accounts.referral'),
        ),
    ]
