# Generated by Django 4.0 on 2022-04-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_verificationcode_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='scope',
            field=models.CharField(choices=[('forget', 'forget'), ('verify', 'verify'), ('withdraw', 'withdraw'), ('tel', 'tel'), ('change_pass', 'change_pass'), ('change_phone', 'change_phone')], max_length=32),
        ),
    ]
