# Generated by Django 4.0 on 2022-04-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_account_name_account_primary_alter_account_type_and_more'),
        ('accounts', '0035_alter_account_referred_by'),
    ]

    operations = [
    ]
