# Generated by Django 4.0 on 2022-04-20 05:39

import django.core.validators
from django.db import migrations, models

def lower_existing_shares_to_max(apps, schema_editor):
    Referral = apps.get_model('accounts', 'Referral')
    Referral.objects.filter(owner_share_percent__gt=30).update(owner_share_percent=30)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_merge_20220416_1829'),
    ]

    operations = [
        migrations.RunPython(
            code=lower_existing_shares_to_max, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='referral',
            name='owner_share_percent',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
