# Generated by Django 4.0 on 2022-04-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_merge_20220406_1017'),
        ('accounts', '0036_alter_verificationcode_scope'),
    ]

    operations = [
    ]
