# Generated by Django 4.0 on 2022-04-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_verificationcode_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='selfie_image_discard_text',
            field=models.TextField(blank=True, verbose_name='توضیحات رد کردن عکس سلفی'),
        ),
        migrations.AddField(
            model_name='user',
            name='selfie_image_discard_text',
            field=models.TextField(blank=True, verbose_name='توضیحات رد کردن عکس سلفی'),
        ),
    ]
