# Generated by Django 4.0 on 2022-04-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_verificationcode_scope'),
        ('accounts', '0036_merge_20220416_1829'),
    ]

    operations = [
    ]
