# Generated by Django 4.0 on 2022-04-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_referral_owner_share_percent'),
        ('accounts', '0037_merge_20220419_1242'),
    ]

    operations = [
    ]
