# Generated by Django 4.0 on 2022-04-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_historicaluser_selfie_image_discard_text_and_more'),
        ('accounts', '0038_merge_20220420_1129'),
    ]

    operations = [
    ]
