# Generated by Django 4.0 on 2022-04-28 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_merge_20220420_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='selfie_image_verifier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.user', verbose_name='تایید کننده عکس سلفی'),
        ),
        migrations.AddField(
            model_name='user',
            name='selfie_image_verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user', verbose_name='تایید کننده عکس سلفی'),
        ),
    ]
