# Generated by Django 4.0 on 2022-04-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_merge_20220420_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='level_2_verify_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید سطح ۲'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='level_3_verify_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید سطح 3'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level_2_verify_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید سطح ۲'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level_3_verify_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید سطح 3'),
        ),
    ]
