# Generated by Django 4.0 on 2022-05-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_historicaluser_selfie_image_verifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='withdraw_before_48h_option',
            field=models.BooleanField(default=False, verbose_name='امکان برداشت وجه پیش از سپری شدن ۴۸ ساعت از اولین واریز'),
        ),
        migrations.AddField(
            model_name='user',
            name='withdraw_before_48h_option',
            field=models.BooleanField(default=False, verbose_name='امکان برداشت وجه پیش از سپری شدن ۴۸ ساعت از اولین واریز'),
        ),
    ]
