# Generated by Django 4.0 on 2022-04-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_historicaluser_level_2_verify_datetime_and_more'),
        ('accounts', '0041_user_unique_verified_national_code'),
    ]

    operations = [
    ]
