# Generated by Django 4.0 on 2022-05-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_historicaluser_withdraw_before_48h_option_and_more'),
        ('accounts', '0042_merge_20220430_1721'),
    ]

    operations = [
    ]
