# Generated by Django 4.0 on 2022-05-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_merge_20220427_1454'),
        ('accounts', '0043_merge_20220501_1306'),
    ]

    operations = [
    ]
