# Generated by Django 4.0 on 2022-05-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_loginactivity'),
        ('accounts', '0045_account_trade_volume_irt'),
    ]

    operations = [
    ]
