# Generated by Django 4.0 on 2022-05-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_merge_20220511_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalnotification',
            name='scope',
            field=models.CharField(choices=[('level_2_prize', 'level_2_prize'), ('first_deposit_prize', 'first_deposit_prize'), ('trade_prize', 'trade_prize')], max_length=22),
        ),
    ]
