# Generated by Django 4.0 on 2022-05-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_externalnotification_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginactivity',
            options={'verbose_name': 'تاریخچه ورود به حساب', 'verbose_name_plural': 'تاریخچه ورود به حساب'},
        ),
    ]
