# Generated by Django 4.0 on 2022-05-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0087_rename_coin_coincategory_coins_and_more'),
        ('accounts', '0054_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bookmark_assets',
            field=models.ManyToManyField(blank=True, null=True, to='ledger.Asset'),
        ),
    ]
