# Generated by Django 4.0 on 2022-05-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0089_asset_margin_enable'),
        ('market', '0020_alter_stoploss_managers_remove_stoploss_completed'),
        ('accounts', '0056_historicaluser_chat_uuid_user_chat_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bookmark_assets',
            field=models.ManyToManyField(to='ledger.Asset'),
        ),
        migrations.AlterField(
            model_name='account',
            name='bookmark_market',
            field=models.ManyToManyField(to='market.PairSymbol'),
        ),
    ]
