# Generated by Django 4.0 on 2022-06-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_alter_verificationcode_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_margin_warn',
        ),
        migrations.AddField(
            model_name='account',
            name='margin_alerting',
            field=models.BooleanField(default=False),
        ),
    ]
