# Generated by Django 4.0 on 2022-06-18 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_firebasetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasetoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
