# Generated by Django 4.0 on 2022-06-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_alter_firebasetoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='on_boarding_flow',
        ),
        migrations.RemoveField(
            model_name='user',
            name='on_boarding_flow',
        ),
    ]
