# Generated by Django 4.0 on 2022-07-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_alter_externalnotification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalnotification',
            name='scope',
            field=models.CharField(choices=[('level_2_prize', 'level_2_prize'), ('first_deposit_prize', 'first_deposit_prize'), ('trade_prize', 'trade_prize'), ('margin_enable', 'margin_enable')], max_length=22, verbose_name='نوع'),
        ),
    ]
