# Generated by Django 4.0 on 2022-07-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_alter_externalnotification_scope'),
        ('accounts', '0064_firebasetoken_ip_firebasetoken_user_agent_and_more'),
    ]

    operations = [
    ]
