# Generated by Django 4.0 on 2022-07-13 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_merge_20220712_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebasetoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firebasetoken',
            name='state',
            field=models.CharField(choices=[('1', '2h'), ('2', '1d'), ('3', '7d')], default='1', max_length=1),
        ),
    ]
