# Generated by Django 4.0 on 2022-07-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_firebasetoken_created_firebasetoken_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalnotification',
            name='scope',
            field=models.CharField(choices=[('level_2_prize', 'level_2_prize'), ('first_deposit_prize', 'first_deposit_prize'), ('trade_prize', 'trade_prize'), ('margin_enable', 'margin_enable'), ('scope_trigger_upgrade_level-first', 'scope_trigger_upgrade_level-first'), ('scope-trigger_upgrade_level_second', 'scope-trigger_upgrade_level_second'), ('scope_trigger_upgrade_level_third', 'scope_trigger_upgrade_level_third'), ('scope_trigger_deposit_first', 'scope_trigger_deposit_first'), ('scope_trigger_deposit_second', 'scope_trigger_deposit_second'), ('scope_trigger_deposit_third', 'scope_trigger_deposit_third'), ('scope_trigger_deposit_fourth', 'scope_trigger_deposit_fourth'), ('scope_trigger_trade_first', 'scope_trigger_trade_first'), ('scope_trigger_trade_second', 'scope_trigger_trade_second'), ('scope_trigger_trade_third', 'scope_trigger_trade_third')], max_length=40, verbose_name='نوع'),
        ),
    ]
