# Generated by Django 4.0 on 2022-07-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_firebasetoken_created_firebasetoken_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='show_margin',
            field=models.BooleanField(default=True, verbose_name='امکان مشاهده حساب تعهدی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_margin',
            field=models.BooleanField(default=True, verbose_name='امکان مشاهده حساب تعهدی'),
        ),
    ]
