# Generated by Django 4.0 on 2022-07-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_alter_externalnotification_scope'),
        ('accounts', '0067_alter_historicaluser_show_margin_and_more'),
    ]

    operations = [
    ]
