# Generated by Django 4.0 on 2022-07-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_alter_externalnotification_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalnotification',
            name='scope',
            field=models.CharField(choices=[('top_gainers', 'top_gainers'), ('margin_enable', 'margin_enable'), ('scope_verify1', 'scope_verify1'), ('scope-verify2', 'scope-verify2'), ('scope_verify3', 'scope_verify3'), ('scope_deposit1', 'scope_deposit1'), ('scope_deposit2', 'scope_deposit2'), ('scope_deposit3', 'scope_deposit3'), ('scope_deposit4', 'scope_deposit4'), ('scope_trade1', 'scope_trade1'), ('scope_trade2', 'scope_trade2'), ('scope_trade3', 'scope_trade3')], max_length=40, verbose_name='نوع'),
        ),
    ]
