# Generated by Django 4.0 on 2022-08-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_alter_externalnotification_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='allow_level1_crypto_withdraw',
            field=models.BooleanField(default=False, verbose_name='امکان برداشت رمزارز در سطح ۱'),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_level1_crypto_withdraw',
            field=models.BooleanField(default=False, verbose_name='امکان برداشت رمزارز در سطح ۱'),
        ),
    ]
