# Generated by Django 4.0 on 2022-08-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_historicaluser_allow_level1_crypto_withdraw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='device_type',
            field=models.CharField(choices=[('tablet', 'tablet'), ('mobile', 'mobile'), ('pc', 'pc'), ('unknown', 'unknown')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='is_sign_up',
            field=models.BooleanField(default=False),
        ),
    ]
