# Generated by Django 4.0 on 2022-08-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_loginactivity_device_type_loginactivity_is_sign_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, unique=True)),
                ('latest_version', models.PositiveIntegerField(default=1)),
                ('force_update_version', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'وضعیت اپلیکیشن',
                'verbose_name_plural': 'وضعیت اپلیکیشن',
            },
        ),
    ]
