# Generated by Django 4.0 on 2022-08-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_appstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='finotechrequest',
            name='service',
            field=models.CharField(choices=[('finotech', 'finotech'), ('jibit', 'jibit')], default='finotech', max_length=8),
            preserve_default=False,
        ),
    ]
