# Generated by Django 4.0 on 2022-08-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_finotechrequest_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='national_code_phone_verified',
            field=models.BooleanField(blank=True, null=True, verbose_name='تاییدیه کد ملی و موبایل'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_code_phone_verified',
            field=models.BooleanField(blank=True, null=True, verbose_name='تاییدیه کد ملی و موبایل'),
        ),
    ]
