# Generated by Django 4.0 on 2022-08-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_remove_user_unique_verified_national_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='national_code_phone_verified',
            field=models.BooleanField(blank=True, null=True, verbose_name='تاییدیه کد ملی و موبایل (شاهکار)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code_phone_verified',
            field=models.BooleanField(blank=True, null=True, verbose_name='تاییدیه کد ملی و موبایل (شاهکار)'),
        ),
    ]
