# Generated by Django 4.0 on 2022-08-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_alter_historicaluser_national_code_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='reject_reason',
            field=models.CharField(blank=True, choices=[('duplicated-national-code', 'duplicated-national-code')], max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='reject_reason',
            field=models.CharField(blank=True, choices=[('duplicated-national-code', 'duplicated-national-code')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('level__gt', 1)), fields=('national_code',), name='unique_verified_national_code'),
        ),
    ]
