# Generated by Django 4.0 on 2022-08-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_historicaluser_reject_reason_user_reject_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficsource',
            name='gps_adid',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficsource',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trafficsource',
            name='user_agent',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tracker_code', models.CharField(blank=True, max_length=16)),
                ('network_name', models.CharField(blank=True, max_length=64)),
                ('campaign_name', models.CharField(blank=True, max_length=64)),
                ('adgroup_name', models.CharField(blank=True, max_length=64)),
                ('creative_name', models.CharField(blank=True, max_length=64)),
                ('action_name', models.CharField(blank=True, max_length=16)),
                ('reinstalled', models.BooleanField(default=False)),
                ('gps_adid', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=265)),
                ('tracker_user_id', models.CharField(blank=True, max_length=64)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=16)),
                ('city', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'unique_together': {('ip_address', 'user_agent', 'gps_adid', 'installed_at')},
            },
        ),
    ]
