# Generated by Django 4.0 on 2022-08-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_trafficsource_gps_adid_trafficsource_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTrackerCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='attribution',
            name='gps_adid',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
