# Generated by Django 4.0 on 2022-08-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_alter_attribution_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='finotechrequest',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
