# Generated by Django 4.0 on 2022-09-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_finotechrequest_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='can_withdraw',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_withdraw',
            field=models.BooleanField(default=True),
        ),
    ]
