# Generated by Django 4.0 on 2022-09-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_historicaluser_can_withdraw_user_can_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='show_strategy_bot',
            field=models.BooleanField(default=False, verbose_name='امکان مشاهده ربات'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_strategy_bot',
            field=models.BooleanField(default=False, verbose_name='امکان مشاهده ربات'),
        ),
    ]
