# Generated by Django 4.0 on 2022-09-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_historicaluser_show_strategy_bot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='country',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
