# Generated by Django 4.0 on 2022-09-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0086_loginactivity_city_loginactivity_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='ip_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
