# Generated by Django 4.0 on 2022-10-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_alter_verificationcode_scope_auth2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='promotion',
            field=models.CharField(blank=True, choices=[('shib', 'shib'), ('voucher', 'voucher')], max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='promotion',
            field=models.CharField(blank=True, choices=[('shib', 'shib'), ('voucher', 'voucher')], max_length=256),
        ),
    ]
