# Generated by Django 4.0 on 2022-11-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_historicaluser_promotion_user_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='promotion',
            field=models.CharField(blank=True, choices=[('true', 'true'), ('voucher', 'voucher')], max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='promotion',
            field=models.CharField(blank=True, choices=[('true', 'true'), ('voucher', 'voucher')], max_length=256),
        ),
    ]
