# Generated by Django 4.0 on 2022-11-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_historicaluser_promotion_user_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalnotification',
            name='scope',
            field=models.CharField(choices=[], max_length=40, verbose_name='نوع'),
        ),
    ]
