# Generated by Django 4.0 on 2022-11-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_alter_externalnotification_scope'),
        ('accounts', '0090_alter_historicaluser_promotion_alter_user_promotion'),
    ]

    operations = [
    ]
