# Generated by Django 4.0 on 2022-11-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0092_remove_historicaluser_allow_level1_crypto_withdraw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='show_community',
            field=models.BooleanField(default=False, verbose_name='امکان مشاهده کامیونیتی'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_community',
            field=models.BooleanField(default=False, verbose_name='امکان مشاهده کامیونیتی'),
        ),
    ]
