# Generated by Django 4.1.3 on 2022-11-29 07:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0093_historicaluser_show_community_user_show_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='ip_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(default='127.0.0.1'), blank=True, default=list, null=True, size=None),
        ),
    ]
