# Generated by Django 4.1.3 on 2022-12-05 10:03

from django.db import migrations, models


def populate_staking(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.update(show_staking=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_alter_customtoken_ip_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='show_staking',
            field=models.BooleanField(default=False, verbose_name='امکان مشاهده سرمایه\u200cگذاری'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_staking',
            field=models.BooleanField(default=False, verbose_name='امکان مشاهده سرمایه\u200cگذاری'),
        ),
        migrations.RunPython(populate_staking, migrations.RunPython.noop)
    ]
