# Generated by Django 4.1.3 on 2022-12-18 12:24

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0095_historicaluser_show_staking_user_show_staking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='phone',
            field=models.CharField(blank=True, db_index=True, error_messages={'unique': 'شماره موبایل وارد شده از قبل در سیستم موجود است.'}, max_length=16, null=True, validators=[accounts.validators.mobile_number_validator], verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, error_messages={'unique': 'شماره موبایل وارد شده از قبل در سیستم موجود است.'}, max_length=16, null=True, unique=True, validators=[accounts.validators.mobile_number_validator], verbose_name='شماره موبایل'),
        ),
    ]
