# Generated by Django 4.1.3 on 2022-12-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_alter_historicaluser_phone_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='withdraw_limit_whitelist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='withdraw_risk_level_multiplier',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (5, 5), (10, 10), (20, 20), (40, 40)], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='withdraw_limit_whitelist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='withdraw_risk_level_multiplier',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (5, 5), (10, 10), (20, 20), (40, 40)], default=1),
        ),
    ]
