# Generated by Django 4.1.3 on 2023-01-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0097_historicaluser_withdraw_limit_whitelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstatus',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
