# Generated by Django 4.1.3 on 2023-01-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0098_alter_appstatus_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='can_trade',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_trade',
            field=models.BooleanField(default=True),
        ),
    ]
