# Generated by Django 4.1.3 on 2023-01-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0099_historicaluser_can_trade_user_can_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='custom_crypto_withdraw_ceil',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_crypto_withdraw_ceil',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
