# Generated by Django 4.1.3 on 2023-01-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_alter_historicaluser_custom_crypto_withdraw_ceil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='first_crypto_deposit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان اولین واریز رمزارزی'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_crypto_deposit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان اولین واریز رمزارزی'),
        ),
    ]
