# Generated by Django 4.1.3 on 2023-03-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0102_historicaluser_first_crypto_deposit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='native_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auth2fa',
            name='token',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
