# Generated by Django 4.1.3 on 2023-03-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_alter_auth2fa_token_userfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='comment',
            field=models.TextField(blank=True, max_length=4096),
        ),
    ]
