# Generated by Django 4.1.3 on 2023-03-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_loginactivity_native_app_alter_auth2fa_token'),
        ('accounts', '0104_alter_userfeedback_comment'),
    ]

    operations = [
    ]
