# Generated by Django 4.0.4 on 2023-04-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0105_merge_20230314_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtoken',
            name='throttle_exempted',
            field=models.BooleanField(default=False),
        ),
    ]
