# Generated by Django 4.1.3 on 2023-04-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0105_merge_20230314_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstatus',
            name='light_apk',
            field=models.FileField(null=True, blank=True, upload_to='app/light/'),
        ),
        migrations.AddField(
            model_name='appstatus',
            name='pro_apk',
            field=models.FileField(null=True, blank=True, upload_to='app/pro/'),
        ),
    ]
