# Generated by Django 4.1.3 on 2023-04-15 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_appstatus_light_apk_appstatus_pro_apk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appstatus',
            name='light_apk',
        ),
        migrations.RenameField(
            model_name='appstatus',
            old_name='pro_apk',
            new_name='apk_link',
        ),
        migrations.AlterField(
            model_name='appstatus',
            name='apk_link',
            field=models.FileField(blank=True, null=True, upload_to='app/'),
        ),

        migrations.CreateModel(
            name='HistoricalAppStatus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('latest_version', models.PositiveIntegerField(default=1)),
                ('force_update_version', models.PositiveIntegerField(default=0)),
                ('apk_link', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical وضعیت اپلیکیشن',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
