# Generated by Django 4.0.4 on 2023-04-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_customtoken_throttle_exempted'),
        ('accounts', '0107_remove_appstatus_light_apk_remove_appstatus_pro_apk_and_more'),
    ]

    operations = [
    ]
