# Generated by Django 4.1.3 on 2023-04-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_customtoken_throttle_exempted'),
        ('accounts', '0108_alter_historicaluser_show_staking_and_more'),
    ]

    operations = [
    ]
