# Generated by Django 4.1.3 on 2023-05-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0108_alter_historicaluser_show_staking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='owned',
            field=models.BooleanField(default=False),
        ),
    ]
