# Generated by Django 4.0.4 on 2023-04-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0108_alter_historicaluser_show_staking_and_more'),
        ('accounts', '0108_merge_20230418_1036'),
    ]

    operations = [
    ]
