# Generated by Django 4.1.3 on 2023-05-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_account_owned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafficsource',
            options={'permissions': [('has_marketing_adivery_reports', 'Can read yektanet mobile analytics'), ('has_marketing_mediaad_reports', 'Can read mediaad analytics')], 'verbose_name': 'منشا ترافیک', 'verbose_name_plural': 'منشا ترافیک'},
        ),
    ]
