# Generated by Django 4.1.3 on 2023-05-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_account_owned'),
        ('accounts', '0109_merge_20230430_1516'),
    ]

    operations = [
    ]
