# Generated by Django 4.1.3 on 2023-05-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_alter_trafficsource_options'),
        ('accounts', '0110_merge_0109_account_owned_0109_merge_20230430_1516'),
    ]

    operations = [
    ]
