# Generated by Django 4.1.3 on 2023-05-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0111_merge_20230503_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='push_status',
            field=models.CharField(blank=True, choices=[('w', 'waiting'), ('s', 'sent')], db_index=True, max_length=1),
        ),
    ]
