# Generated by Django 4.1.3 on 2023-05-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0112_notification_push_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
