# Generated by Django 4.1.3 on 2023-05-06 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0113_notification_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group_id', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده')], default='pending', max_length=8)),
                ('title', models.CharField(max_length=128)),
                ('link', models.CharField(blank=True, max_length=128)),
                ('message', models.CharField(blank=True, max_length=512)),
                ('level', models.CharField(choices=[('info', 'info'), ('success', 'success'), ('warning', 'warning'), ('error', 'error')], default='info', max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='group_id',
            field=models.UUIDField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('recipient', 'group_id')},
        ),
    ]
