# Generated by Django 4.1.3 on 2023-05-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_merge_20230425_1732'),
        ('accounts', '0114_bulknotification_notification_group_id_and_more'),
    ]

    operations = [
    ]
