# Generated by Django 4.1.3 on 2023-05-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0116_smsnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsnotification',
            old_name='data',
            new_name='params',
        ),
        migrations.AddIndex(
            model_name='smsnotification',
            index=models.Index(fields=['recipient', 'template'], name='accounts_sm_recipie_a59695_idx'),
        ),
    ]
