# Generated by Django 4.1.3 on 2023-05-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0117_rename_data_smsnotification_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
