# Generated by Django 4.1.3 on 2023-05-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0118_notification_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebasetoken',
            name='native_app',
            field=models.BooleanField(default=False),
        ),
    ]
