# Generated by Django 4.1.3 on 2023-05-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0119_firebasetoken_native_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebasetoken',
            name='state',
        ),
    ]
