# Generated by Django 4.1.3 on 2023-05-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0120_alter_user_options_smsnotification_content_and_more'),
        ('accounts', '0120_remove_firebasetoken_state'),
    ]

    operations = [
    ]
