# Generated by Django 4.1.3 on 2023-06-03 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('accounts', '0121_merge_20230523_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginactivity',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session'),
        ),
    ]
