# Generated by Django 4.1.3 on 2023-06-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0122_alter_loginactivity_session'),
        ('accounts', '0122_historicaluser_can_withdraw_crypto_and_more'),
    ]

    operations = [
    ]
