# Generated by Django 4.1.3 on 2023-06-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0123_alter_bulknotification_message'),
        ('accounts', '0123_merge_20230607_1654'),
    ]

    operations = [
    ]
