# Generated by Django 4.1.3 on 2023-06-11 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0124_alter_smsnotification_content'),
        ('accounts', '0124_merge_20230610_1540'),
    ]

    operations = [
    ]
