# Generated by Django 4.1.3 on 2023-06-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0126_emailnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulknotification',
            name='status',
            field=models.CharField(choices=[('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده')], default='pending', max_length=8),
        ),
    ]
