# Generated by Django 4.1.3 on 2023-06-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0127_alter_bulknotification_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='smsnotification',
            name='accounts_sm_recipie_a59695_idx',
        ),
        migrations.RemoveField(
            model_name='smsnotification',
            name='params',
        ),
        migrations.RemoveField(
            model_name='smsnotification',
            name='template',
        ),
        migrations.AlterField(
            model_name='smsnotification',
            name='content',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
