# Generated by Django 4.1.3 on 2023-06-18 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0128_remove_smsnotification_accounts_sm_recipie_a59695_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeaturePerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('pay_id', 'pay_id')], max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'feature')},
            },
        ),
    ]
