# Generated by Django 4.1.3 on 2023-06-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0131_alter_userfeatureperm_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='promotion',
            field=models.CharField(blank=True, choices=[('true', 'true'), ('voucher', 'voucher'), ('pepe', 'pepe')], max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='promotion',
            field=models.CharField(blank=True, choices=[('true', 'true'), ('voucher', 'voucher'), ('pepe', 'pepe')], max_length=256),
        ),
        migrations.AlterField(
            model_name='userfeatureperm',
            name='feature',
            field=models.CharField(choices=[('pay_id', 'pay_id'), ('fiat_deposit_daily_limit', 'fiat_deposit_daily_limit')], max_length=32, verbose_name='ویژگی'),
        ),
    ]
