# Generated by Django 4.1.3 on 2023-06-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0133_refreshtoken_loginactivity_logout_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
