# Generated by Django 4.1.3 on 2023-07-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0134_alter_refreshtoken_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalNotification',
        ),
    ]
