# Generated by Django 4.1.3 on 2023-07-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0135_delete_externalnotification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['recipient', 'title', 'created'], name='email_notification_idx'),
        ),
        migrations.AddIndex(
            model_name='loginactivity',
            index=models.Index(fields=['user', 'ip', 'browser', 'os'], name='login_activity_idx'),
        ),
    ]
