# Generated by Django 4.1.3 on 2023-07-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0136_emailnotification_email_notification_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read', 'hidden'], name='notification_idx'),
        ),
    ]
