# Generated by Django 4.1.3 on 2023-07-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0136_alter_userfeatureperm_feature'),
        ('accounts', '0136_emailnotification_email_notification_idx_and_more'),
    ]

    operations = [
    ]
