# Generated by Django 4.1.3 on 2023-07-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0137_merge_20230711_1237'),
        ('accounts', '0137_notification_notification_idx'),
    ]

    operations = [
    ]
