# Generated by Django 4.1.3 on 2023-07-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0138_merge_20230711_1255'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notification',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='source',
            field=models.CharField(choices=[('core', 'core'), ('ninja', 'ninja'), ('crm', 'crm')], default='core', max_length=8),
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.CharField(choices=[('like', 'like'), ('comment', 'comment'), ('follow', 'follow'), ('plain', 'plain')], default='plain', max_length=8),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ord', 'ord'), ('rep', 'rep'), ('dif', 'dif')], default='ord', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('read', False), ('source', 'ninja')), fields=('group_id', 'template'), name='unique_unread_group_id'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('template', 'plain')), fields=('recipient', 'group_id'), name='unique_recipient_group_id'),
        ),
    ]
