# Generated by Django 4.1.3 on 2023-08-01 07:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0139_alter_notification_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtoken',
            name='scopes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('withdraw', 'withdraw'), ('trade', 'trade')], max_length=10), blank=True, default=['trade'], null=True, size=None),
        ),
    ]
