# Generated by Django 4.1.3 on 2023-08-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0139_alter_notification_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='withdraw_before_48h_option',
        ),
        migrations.RemoveField(
            model_name='user',
            name='withdraw_before_48h_option',
        ),
    ]
