# Generated by Django 4.1.3 on 2023-08-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0139_alter_notification_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finotechrequest',
            name='service',
            field=models.CharField(choices=[('finotech', 'finotech'), ('jibit', 'jibit'), ('zibal', 'zibal')], max_length=8),
        ),
    ]
