# Generated by Django 4.1.3 on 2023-08-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0140_alter_verificationcode_scope_delete_auth2fa'),
        ('accounts', '0140_customtoken_scopes'),
    ]

    operations = [
    ]
