# Generated by Django 4.1.3 on 2023-08-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0140_alter_verificationcode_scope_delete_auth2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تعلیق شدن کاربر'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تعلیق شدن کاربر'),
        ),
        migrations.AddIndex(
            model_name='loginactivity',
            index=models.Index(fields=['user', 'device'], name='login_suspension_idx'),
        ),
    ]
