# Generated by Django 4.1.3 on 2023-08-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0140_alter_finotechrequest_service'),
        ('accounts', '0140_remove_historicaluser_withdraw_before_48h_option_and_more'),
    ]

    operations = [
    ]
