# Generated by Django 4.1.3 on 2023-09-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0144_merge_20230911_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('is_consultation_available', models.BooleanField(default=False)),
            ],
        ),
    ]
