# Generated by Django 4.1.3 on 2023-09-17 11:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0147_rename_consultation_consultee_consultation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='withdraw_fee_max',
            field=models.SmallIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='withdraw_fee_min',
            field=models.SmallIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='withdraw_fee_percent',
            field=models.DecimalField(decimal_places=8, default=Decimal('5'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
