# Generated by Django 4.1.3 on 2023-09-12 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0008_historicalcoinpricecontent'),
        ('accounts', '0147_rename_consultation_consultee_consultation_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forget2FA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=15)),
                ('selfie_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='multimedia.image', verbose_name='عکس سلفی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست فراموشی شناسه دوعاملی',
                'verbose_name_plural': 'درخواست\u200cهای فراموشی شناسه دوعاملی',
            },
        ),
    ]
