# Generated by Django 4.1.3 on 2023-09-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0145_alter_customtoken_scopes'),
        ('accounts', '0148_alter_verificationcode_scope'),
    ]

    operations = [
    ]
