# Generated by Django 4.1.3 on 2023-09-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0149_alter_verificationcode_scope'),
        ('accounts', '0150_alter_verificationcode_scope'),
    ]

    operations = [
    ]
