# Generated by Django 4.1.3 on 2023-09-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0152_alter_verificationcode_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forget2fa',
            name='status',
            field=models.CharField(choices=[('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده')], default='pending', max_length=8),
        ),
    ]
