# Generated by Django 4.1.3 on 2023-09-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0148_systemconfig_withdraw_fee_max_and_more'),
        ('accounts', '0153_alter_forget2fa_status'),
    ]

    operations = [
    ]
