# Generated by Django 4.1.3 on 2023-09-19 08:24

import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0008_historicalcoinpricecontent'),
        ('accounts', '0154_merge_20230917_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده')], default='pending', max_length=8)),
                ('new_phone', models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True, validators=[accounts.validators.mobile_number_validator], verbose_name='شماره موبایل جدید')),
                ('selfie_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='multimedia.image', verbose_name='عکس سلفی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست تغییر شماره موبایل',
                'verbose_name_plural': 'درخواست\u200cهای تغییر شماره موبایل',
            },
        ),
    ]
