# Generated by Django 4.1.3 on 2023-09-24 14:59

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0155_changephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changephone',
            name='new_phone',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, validators=[accounts.validators.mobile_number_validator], verbose_name='شماره موبایل جدید'),
        ),
    ]
