# Generated by Django 4.1.3 on 2023-09-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0156_alter_changephone_new_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
