# Generated by Django 4.1.3 on 2023-10-24 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0157_historicaluser_suspension_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='custom_maker_fee',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='account',
            name='custom_taker_fee',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
