# Generated by Django 4.1.3 on 2023-10-28 16:33

import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0021_file'),
        ('accounts', '0158_account_custom_maker_fee_account_custom_taker_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelGrants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(unique=True)),
                ('max_daily_crypto_withdraw', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('max_daily_fiat_withdraw', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('max_daily_fiat_deposit', models.PositiveBigIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='custom_fiat_withdraw_ceil',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_fiat_withdraw_ceil',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4')], default=1, verbose_name='سطح'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4')], default=1, verbose_name='سطح'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=128)),
                ('registration_id', models.CharField(blank=True, max_length=128, unique=True)),
                ('company_registration_date', models.CharField(blank=True, max_length=128)),
                ('national_id', models.CharField(max_length=11, unique=True, validators=[accounts.validators.company_national_id_validator])),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('provider_data', models.JSONField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
                ('company_documents', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='multimedia.file', verbose_name='مدارک شرکت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت\u200cها',
            },
        ),
    ]
