# Generated by Django 4.1.3 on 2023-10-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0160_alter_levelgrants_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='verified',
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده')], default='pending', max_length=8),
        ),
    ]
