# Generated by Django 4.1.3 on 2023-11-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0162_alter_userfeatureperm_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registration_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
