# Generated by Django 4.1.3 on 2023-11-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0164_alter_company_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_verified_national_code',
        ),
    ]
