# Generated by Django 4.1.3 on 2023-11-02 06:22

from django.db import migrations


def populate_level_grants(apps, schema_editor):
    LevelGrants = apps.get_model('accounts', 'LevelGrants')

    LevelGrants.objects.get_or_create(
        level=1,
    )

    LevelGrants.objects.get_or_create(
        level=2,
        defaults={
            'max_daily_crypto_withdraw': 200_000_000,
            'max_daily_fiat_withdraw': 200_000_000,
        }
    )

    LevelGrants.objects.get_or_create(
        level=3,
        defaults={
            'max_daily_crypto_withdraw': 200_000_000,
            'max_daily_fiat_withdraw': 200_000_000,
        }
    )

    LevelGrants.objects.get_or_create(
        level=4,
        defaults={
            'max_daily_crypto_withdraw': 200_000_000,
            'max_daily_fiat_withdraw': 200_000_000,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0165_remove_user_unique_verified_national_code'),
    ]

    operations = [
        migrations.RunPython(code=populate_level_grants, reverse_code=migrations.RunPython.noop)
    ]
