# Generated by Django 4.1.3 on 2023-11-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0166_auto_20231102_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
