# Generated by Django 4.1.3 on 2023-11-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0167_alter_company_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_generate_notification', 'Can Generate All Kind Of Notification'), ('manage_users', 'Manage Users Info')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
