# Generated by Django 4.1.3 on 2023-11-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0168_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='show_strategy_bot',
            field=models.BooleanField(default=True, verbose_name='امکان مشاهده ربات'),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_strategy_bot',
            field=models.BooleanField(default=True, verbose_name='امکان مشاهده ربات'),
        ),
    ]
