# Generated by Django 4.1.3 on 2023-12-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0169_alter_historicaluser_show_strategy_bot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafficsource',
            options={'verbose_name': 'منشا ترافیک', 'verbose_name_plural': 'منشا ترافیک'},
        ),
    ]
