# Generated by Django 4.1.3 on 2023-12-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0170_alter_trafficsource_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='hedge_irt_by_internal_market',
            field=models.BooleanField(default=False),
        ),
    ]
