# Generated by Django 4.1.3 on 2023-12-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0171_systemconfig_hedge_irt_by_internal_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeatureperm',
            name='feature',
            field=models.CharField(choices=[('pay_id', 'pay_id'), ('fiat_deposit_daily_limit', 'fiat_deposit_daily_limit'), ('bank_payment', 'bank_payment'), ('ui', 'ui'), ('no_crypto_withdraw_sms', 'no_crypto_withdraw_sms')], max_length=32, verbose_name='ویژگی'),
        ),
    ]
