# Generated by Django 4.1.3 on 2023-12-23 12:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0172_alter_userfeatureperm_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='insurance_fee_percentage',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.02'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='liquidation_level',
            field=models.DecimalField(decimal_places=8, default=Decimal('1.1'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='max_margin_leverage',
            field=models.DecimalField(decimal_places=8, default=Decimal('5'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='mean_leverage',
            field=models.DecimalField(decimal_places=8, default=Decimal('3'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='total_margin_irt_base',
            field=models.DecimalField(decimal_places=8, default=Decimal('500000000'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='total_margin_usdt_base',
            field=models.DecimalField(decimal_places=8, default=Decimal('10000'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='total_user_margin_irt_base',
            field=models.DecimalField(decimal_places=8, default=Decimal('500000000'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='total_user_margin_usdt_base',
            field=models.DecimalField(decimal_places=8, default=Decimal('10000'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
