# Generated by Django 4.1.3 on 2023-12-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0174_remove_systemconfig_mean_leverage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemconfig',
            old_name='insurance_fee_percentage',
            new_name='insurance_fee',
        ),
    ]
