# Generated by Django 4.1.3 on 2024-01-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0175_rename_insurance_fee_percentage_systemconfig_insurance_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='hedge_coin_otc_from_internal_market',
            field=models.BooleanField(default=True),
        ),
    ]
