# Generated by Django 4.1.3 on 2024-01-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0176_systemconfig_hedge_coin_otc_from_internal_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='open_pay_id_to_all',
            field=models.BooleanField(default=False),
        ),
    ]
