# Generated by Django 4.1.3 on 2024-01-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0178_systemconfig_limit_ipg_to_users_without_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulknotification',
            name='status',
            field=models.CharField(choices=[('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='changephone',
            name='status',
            field=models.CharField(choices=[('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='forget2fa',
            name='status',
            field=models.CharField(choices=[('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], default='pending', max_length=8),
        ),
    ]
