# Generated by Django 4.1.3 on 2024-01-31 08:48

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0179_alter_bulknotification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='deposit_status',
            field=models.CharField(choices=[('allow', 'allow'), ('ban', 'ban'), ('ban_crypto', 'ban_crypto'), ('ban_fiat', 'ban_fiat')], default='allow', max_length=16),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='name',
            field=models.CharField(default='main', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='withdraw_status',
            field=models.CharField(choices=[('allow', 'allow'), ('ban', 'ban'), ('ban_crypto', 'ban_crypto'), ('ban_fiat', 'ban_fiat')], default='allow', max_length=16),
        ),
        migrations.CreateModel(
            name='HistoricalSystemConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('active', models.BooleanField()),
                ('is_consultation_available', models.BooleanField(default=False)),
                ('withdraw_fee_min', models.SmallIntegerField(default=1000)),
                ('withdraw_fee_max', models.SmallIntegerField(default=5000)),
                ('withdraw_fee_percent', models.DecimalField(decimal_places=8, default=Decimal('5'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('hedge_irt_by_internal_market', models.BooleanField(default=False)),
                ('hedge_coin_otc_from_internal_market', models.BooleanField(default=True)),
                ('max_margin_leverage', models.SmallIntegerField(default=5)),
                ('default_margin_leverage', models.SmallIntegerField(default=3)),
                ('total_margin_usdt_base', models.DecimalField(decimal_places=8, default=Decimal('10000'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_margin_irt_base', models.DecimalField(decimal_places=8, default=Decimal('500000000'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_user_margin_usdt_base', models.DecimalField(decimal_places=8, default=Decimal('10000'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_user_margin_irt_base', models.DecimalField(decimal_places=8, default=Decimal('500000000'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('liquidation_level', models.DecimalField(decimal_places=8, default=Decimal('1.1'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('insurance_fee', models.DecimalField(decimal_places=8, default=Decimal('0.02'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('open_pay_id_to_all', models.BooleanField(default=False)),
                ('limit_ipg_to_users_without_payment', models.BooleanField(default=False)),
                ('withdraw_status', models.CharField(choices=[('allow', 'allow'), ('ban', 'ban'), ('ban_crypto', 'ban_crypto'), ('ban_fiat', 'ban_fiat')], default='allow', max_length=16)),
                ('deposit_status', models.CharField(choices=[('allow', 'allow'), ('ban', 'ban'), ('ban_crypto', 'ban_crypto'), ('ban_fiat', 'ban_fiat')], default='allow', max_length=16)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical system config',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
