# Generated by Django 4.1.3 on 2024-02-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0180_systemconfig_deposit_status_systemconfig_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulknotification',
            name='status',
            field=models.CharField(choices=[('init', 'در حال بررسی'), ('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='changephone',
            name='status',
            field=models.CharField(choices=[('init', 'در حال بررسی'), ('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('init', 'در حال بررسی'), ('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='forget2fa',
            name='status',
            field=models.CharField(choices=[('init', 'در حال بررسی'), ('process', 'در حال پردازش'), ('pending', 'در انتظار تایید'), ('canceled', 'لغو شده'), ('done', 'انجام شده'), ('refund', 'برگشت')], db_index=True, default='pending', max_length=8),
        ),
    ]
