# Generated by Django 4.1.3 on 2024-02-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0181_alter_bulknotification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulknotification',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='changephone',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='forget2fa',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('refund', 'refund')], db_index=True, default='pending', max_length=8),
        ),
    ]
