# Generated by Django 4.1.3 on 2024-02-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0183_historicalsystemconfig_default_max_allowed_coin_network_daily_deposit_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeatureperm',
            name='feature',
            field=models.CharField(choices=[('pay_id', 'pay_id'), ('fiat_deposit_daily_limit', 'fiat_deposit_daily_limit'), ('bank_payment', 'bank_payment'), ('ui', 'ui'), ('no_crypto_withdraw_sms', 'no_crypto_withdraw_sms'), ('pay_id_master', 'pay_id_master')], max_length=32, verbose_name='ویژگی'),
        ),
    ]
