# Generated by Django 4.1.3 on 2024-03-14 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0185_historicalsystemconfig_fiat_daily_auto_verify_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
