# Generated by Django 4.1.3 on 2024-04-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0186_alter_notification_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='market_maker_emergency_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='market_maker_emergency_break',
            field=models.BooleanField(default=False),
        ),
    ]
