# Generated by Django 4.1.3 on 2024-04-29 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0187_historicalsystemconfig_market_maker_emergency_break_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='position_deadline',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='position_deadline',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
