# Generated by Django 4.1.3 on 2024-05-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0188_historicalsystemconfig_position_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='custom_max_margin_leverage',
            field=models.SmallIntegerField(null=True),
        ),
    ]
