# Generated by Django 4.1.3 on 2024-04-29 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0188_historicalsystemconfig_position_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsystemconfig',
            name='position_deadline',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='position_deadline',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
    ]
