# Generated by Django 4.1.3 on 2024-05-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0189_account_custom_max_margin_leverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='custom_max_margin_leverage',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
