# Generated by Django 4.1.3 on 2024-05-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0190_alter_account_custom_max_margin_leverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsystemconfig',
            name='default_margin_leverage',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='default_margin_leverage',
            field=models.SmallIntegerField(default=1),
        ),
    ]
