# Generated by Django 4.1.3 on 2024-05-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0191_alter_historicalsystemconfig_default_margin_leverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='dust_convert_threshold',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='dust_convert_threshold',
            field=models.PositiveIntegerField(default=100000),
        ),
    ]
