# Generated by Django 4.1.3 on 2024-05-26 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0192_historicalsystemconfig_dust_convert_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsystemconfig',
            name='dust_convert_threshold',
            field=models.PositiveIntegerField(default=100000, validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='dust_convert_threshold',
            field=models.PositiveIntegerField(default=100000, validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
