# Generated by Django 4.1.3 on 2024-06-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0193_alter_historicalsystemconfig_dust_convert_threshold_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelgrants',
            options={'verbose_name_plural': 'Level Grants'},
        ),
    ]
