# Generated by Django 4.1.3 on 2024-07-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0194_alter_levelgrants_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='show_margin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='show_margin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='show_margin',
            field=models.BooleanField(default=False, verbose_name='امکان مشاهده حساب تعهدی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_margin',
            field=models.BooleanField(default=False, verbose_name='امکان مشاهده حساب تعهدی'),
        ),
    ]
