# Generated by Django 4.1.3 on 2024-07-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0195_historicalsystemconfig_show_margin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='promotion',
            field=models.CharField(blank=True, choices=[('true', 'true'), ('voucher', 'voucher'), ('pepe', 'pepe'), ('not', 'not')], max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='promotion',
            field=models.CharField(blank=True, choices=[('true', 'true'), ('voucher', 'voucher'), ('pepe', 'pepe'), ('not', 'not')], max_length=256),
        ),
    ]
