# Generated by Django 4.1.3 on 2024-07-07 13:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0195_historicalsystemconfig_show_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='increase_fiat_withdraw_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='withdraw_fee_percent_after_max',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='withdraw_fee_percent_after_max',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='historicalsystemconfig',
            name='withdraw_fee_percent',
            field=models.DecimalField(decimal_places=8, default=Decimal('5'), max_digits=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='withdraw_fee_percent',
            field=models.DecimalField(decimal_places=8, default=Decimal('5'), max_digits=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
