# Generated by Django 4.1.3 on 2024-07-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0196_account_increase_fiat_withdraw_fee_and_more'),
        ('accounts', '0196_alter_historicaluser_promotion_alter_user_promotion'),
    ]

    operations = [
    ]
