# Generated by Django 4.1.3 on 2024-07-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0196_alter_historicaluser_promotion_alter_user_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='بایگانی'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4')], db_index=True, default=1, verbose_name='سطح'),
        ),
        migrations.AlterField(
            model_name='user',
            name='archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='بایگانی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4')], db_index=True, default=1, verbose_name='سطح'),
        ),
    ]
