# Generated by Django 4.1.3 on 2024-07-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0197_alter_historicaluser_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='promotion',
            field=models.CharField(blank=True, choices=[('true', 'true'), ('voucher', 'voucher'), ('pepe', 'pepe'), ('notcoin', 'notcoin')], max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='promotion',
            field=models.CharField(blank=True, choices=[('true', 'true'), ('voucher', 'voucher'), ('pepe', 'pepe'), ('notcoin', 'notcoin')], max_length=256),
        ),
    ]
