# Generated by Django 4.1.3 on 2024-07-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0197_alter_historicaluser_archived_and_more'),
        ('accounts', '0197_merge_20240714_1545'),
    ]

    operations = [
    ]
