# Generated by Django 4.1.3 on 2024-07-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0198_merge_20240720_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='disable_trade_with_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='disable_trade_with_api',
            field=models.BooleanField(default=False),
        ),
    ]
