# Generated by Django 4.1.3 on 2024-07-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0198_alter_historicaluser_promotion_alter_user_promotion'),
        ('accounts', '0199_historicalsystemconfig_disable_trade_with_api_and_more'),
    ]

    operations = [
    ]
