# Generated by Django 4.1.3 on 2024-07-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0200_merge_20240723_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='disable_new_positions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='disable_new_positions',
            field=models.BooleanField(default=True),
        ),
    ]
