# Generated by Django 4.1.3 on 2024-07-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0201_historicalsystemconfig_disable_new_positions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='convert_dust_retry_hours_limit',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='convert_dust_retry_hours_limit',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
