# Generated by Django 4.1.3 on 2024-07-29 08:35

from django.db import migrations, models


def populate_user_promotions(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(promotion='').update(promotion='voucher')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0201_historicalsystemconfig_disable_new_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='promotion',
            field=models.CharField(choices=[('true', 'true'), ('voucher', 'voucher'), ('pepe', 'pepe'), ('notcoin', 'notcoin')], max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='promotion',
            field=models.CharField(choices=[('true', 'true'), ('voucher', 'voucher'), ('pepe', 'pepe'), ('notcoin', 'notcoin')], max_length=256),
        ),
        migrations.RunPython(code=populate_user_promotions, reverse_code=migrations.RunPython.noop)
    ]
