# Generated by Django 4.1.3 on 2024-07-29 13:56

import accounts.utils.random
from django.db import migrations, models
import django.db.models.deletion


def populate_attribution(apps, schema_editor):
    AttributionTracker = apps.get_model('accounts', 'AttributionTracker')
    Attribution = apps.get_model('accounts', 'Attribution')

    tracker = AttributionTracker.objects.create(name="Default", type='metrix')
    Attribution.objects.update(tracker=tracker)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0202_alter_historicaluser_promotion_alter_user_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('yandex', 'yandex'), ('metrix', 'metrix')], max_length=8)),
                ('key', models.CharField(default=accounts.utils.random.get_random_str, max_length=8, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attribution',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attribution',
            name='app_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attribution',
            name='device_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attribution',
            name='device_locale',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attribution',
            name='device_manufacturer',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attribution',
            name='device_model',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attribution',
            name='device_type',
            field=models.CharField(blank=True, choices=[('PHONE', 'PHONE'), ('TABLET', 'TABLET'), ('PHABLET', 'PHABLET'), ('TV', 'TV')], max_length=8),
        ),
        migrations.AddField(
            model_name='attribution',
            name='install_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribution',
            name='os_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attribution',
            name='os_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attribution',
            name='profile_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='action_name',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='adgroup_name',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='campaign_name',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='city',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='country',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='creative_name',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='network_name',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='reinstalled',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='tracker_code',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='tracker_user_id',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='attribution',
            name='tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.attributiontracker'),
        ),
        migrations.RunPython(code=populate_attribution, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='attribution',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='accounts.attributiontracker'),
        )
    ]
