# Generated by Django 4.1.3 on 2024-07-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0203_attributiontracker_alter_attribution_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='ban_deposit_with_credit_bank_cards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ban_deposit_with_credit_bank_cards',
            field=models.BooleanField(default=False),
        ),
    ]
