# Generated by Django 4.1.3 on 2024-07-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0204_historicaluser_ban_deposit_with_credit_bank_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='click_url_params',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='attribution',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attribution',
            name='operator',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
