# Generated by Django 4.1.3 on 2024-07-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0205_attribution_click_url_params_attribution_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficsource',
            name='yandex_profile_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='trafficsource',
            name='gps_adid',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='trafficsource',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='trafficsource',
            name='utm_content',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='trafficsource',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='trafficsource',
            name='utm_source',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='trafficsource',
            name='utm_term',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
