# Generated by Django 4.1.3 on 2024-07-31 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0206_trafficsource_yandex_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficsource',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_source', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
