# Generated by Django 4.1.3 on 2024-08-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0207_alter_trafficsource_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_generate_notification', 'Can Generate All Kind Of Notification'), ('manage_users', 'Manage Users Info'), ('list_user', 'Can list user')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
