# Generated by Django 4.1.3 on 2024-08-04 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0208_alter_user_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinotechRequest',
            new_name='UserAuthRequest',
        ),
        migrations.AlterModelOptions(
            name='userauthrequest',
            options={'permissions': [('list_userauthrequest', 'Can list user auth request')]},
        ),
    ]
