# Generated by Django 4.1.3 on 2024-08-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0209_rename_finotechrequest_userauthrequest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_generate_notification', 'Can Generate All Kind Of Notification'), ('manage_users', 'Manage Users Info'), ('list_user', 'Can list user'), ('can_view_user_selfie', 'Can view user selfie')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
