# Generated by Django 4.1.3 on 2024-08-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0210_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafficsource',
            options={},
        ),
    ]
