# Generated by Django 4.1.3 on 2024-08-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0211_alter_trafficsource_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsystemconfig',
            old_name='market_maker_emergency_break',
            new_name='market_maker_emergency_brake',
        ),
        migrations.RenameField(
            model_name='systemconfig',
            old_name='market_maker_emergency_break',
            new_name='market_maker_emergency_brake',
        ),
    ]
