# Generated by Django 4.1.3 on 2024-08-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0212_rename_market_maker_emergency_break_historicalsystemconfig_market_maker_emergency_brake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='push_status',
            field=models.CharField(blank=True, choices=[('w', 'waiting'), ('s', 'sent'), ('c', 'canceled')], db_index=True, max_length=1),
        ),
    ]
