# Generated by Django 4.1.3 on 2024-08-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0202_historicalsystemconfig_convert_dust_retry_hours_limit_and_more'),
        ('accounts', '0213_alter_notification_push_status'),
    ]

    operations = [
    ]
