# Generated by Django 4.1.3 on 2024-08-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0214_merge_20240806_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='enable_otc_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_otc_limit',
            field=models.BooleanField(default=False),
        ),
    ]
