# Generated by Django 4.1.3 on 2024-08-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0215_historicalsystemconfig_enable_otc_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribution',
            name='profile_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
