# Generated by Django 4.1.3 on 2024-08-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0216_alter_attribution_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsystemconfig',
            name='enable_otc_limit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='enable_otc_limit',
            field=models.BooleanField(default=True),
        ),
    ]
