# Generated by Django 4.1.3 on 2024-08-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0217_alter_historicalsystemconfig_enable_otc_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='strategy_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='strategy_enable',
            field=models.BooleanField(default=True),
        ),
    ]
