# Generated by Django 4.1.3 on 2024-08-24 06:28

import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0027_alter_guide_options_alter_guidegroup_options_and_more'),
        ('accounts', '0218_historicalsystemconfig_strategy_enable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCompany',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=128)),
                ('registration_id', models.CharField(blank=True, max_length=128)),
                ('company_registration_date', models.CharField(blank=True, max_length=128)),
                ('national_id', models.CharField(db_index=True, max_length=11, validators=[accounts.validators.company_national_id_validator])),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('provider_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('init', 'init'), ('pending', 'pending'), ('rejected', 'rejected'), ('verified', 'verified')], default='init', max_length=8)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company_documents', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='multimedia.file', verbose_name='مدارک شرکت')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical شرکت',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
