# Generated by Django 4.1.3 on 2024-08-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0219_historicalcompany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='selfie_image_verifier',
            new_name='verifier',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='selfie_image_verifier',
            new_name='verifier',
        ),
    ]
