# Generated by Django 4.1.3 on 2024-08-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0220_rename_selfie_image_verifier_historicaluser_verifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='scope',
            field=models.CharField(choices=[('forget', 'forget'), ('verify', 'verify'), ('verify_widget', 'verify_widget'), ('withdraw', 'withdraw'), ('tel', 'tel'), ('change_pass', 'change_pass'), ('change_phone', 'change_phone'), ('change_phone_init', 'change_phone_init'), ('email_verify', 'email_verify'), ('fiat_withdraw', 'fiat_withdraw'), ('2fa', '2fa'), ('api_token', 'api_token'), ('address_book', 'address_book'), ('new_phone', 'new_phone'), ('forget_2fa', 'forget_2fa')], db_index=True, max_length=32),
        ),
    ]
