# Generated by Django 4.1.3 on 2024-08-24 11:01

from django.db import migrations


def fix_traffic_source(apps, schema_editor):
    TrafficSource = apps.get_model('accounts', 'TrafficSource')
    TrafficSource.objects.filter(yandex_profile_id='', utm_source='pwa_app', utm_medium='yandex').update(
        utm_medium='organic',
        utm_campaign='',
        utm_content='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0220_rename_selfie_image_verifier_historicaluser_verifier_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=fix_traffic_source,
            reverse_code=migrations.RunPython.noop
        )
    ]
