# Generated by Django 4.1.3 on 2024-08-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0221_alter_verificationcode_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='min_fast_buy_irt',
            field=models.PositiveIntegerField(default=50000),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='min_fast_buy_irt',
            field=models.PositiveIntegerField(default=50000),
        ),
    ]
