# Generated by Django 4.1.3 on 2024-09-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0222_alter_historicaluser_promotion_alter_user_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficsource',
            name='package_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
