# Generated by Django 4.1.3 on 2024-09-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0222_alter_historicaluser_promotion_alter_user_promotion'),
        ('accounts', '0222_historicalsystemconfig_min_fast_buy_irt_and_more'),
    ]

    operations = [
    ]
