# Generated by Django 4.1.3 on 2024-09-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0223_merge_20240901_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='check_national_code_for_widget',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='check_national_code_for_widget',
            field=models.BooleanField(default=True),
        ),
    ]
