# Generated by Django 4.1.3 on 2024-09-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0223_merge_20240901_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthrequest',
            name='search_key',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userauthrequest',
            unique_together={('search_key', 'service')},
        ),
    ]
