# Generated by Django 4.1.3 on 2024-09-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0224_historicalsystemconfig_check_national_code_for_widget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthrequest',
            name='search_key',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
    ]
