# Generated by Django 4.1.3 on 2024-09-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0223_trafficsource_package_name'),
        ('accounts', '0225_alter_userauthrequest_search_key_and_more'),
    ]

    operations = [
    ]
