# Generated by Django 4.1.3 on 2024-09-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0226_merge_20240909_1535'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userauthrequest',
            index=models.Index(condition=models.Q(('search_key', ''), _negated=True), fields=['search_key', 'service'], name='accounts_userauth_search_key'),
        ),
    ]
