# Generated by Django 4.1.3 on 2024-09-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0227_userauthrequest_accounts_userauth_search_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='max_fast_buy_irt',
            field=models.PositiveIntegerField(default=25000000),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='max_fast_buy_irt',
            field=models.PositiveIntegerField(default=25000000),
        ),
    ]
