# Generated by Django 4.1.3 on 2024-09-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0228_historicalsystemconfig_max_fast_buy_irt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=256, unique=True)),
                ('default', models.BooleanField(default=True)),
                ('yandex_api_key', models.CharField(max_length=64, unique=True)),
                ('yandex_app_id', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
