# Generated by Django 4.1.3 on 2024-09-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0229_appconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
