# Generated by Django 4.1.3 on 2024-09-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0230_alter_appconfig_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
