# Generated by Django 4.1.3 on 2024-09-28 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0230_alter_appconfig_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMTopicSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('p', 'p'), ('d', 'd'), ('f', 'f')], db_index=True, default='p', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
