# Generated by Django 4.1.3 on 2024-09-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0230_alter_appconfig_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='platform_type',
            field=models.CharField(choices=[('crypto', 'crypto'), ('gold', 'gold')], default='crypto', max_length=16),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='platform_type',
            field=models.CharField(choices=[('crypto', 'crypto'), ('gold', 'gold')], default='crypto', max_length=16),
        ),
    ]
