# Generated by Django 4.1.3 on 2024-09-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0231_fcmtopicsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtopicsubscription',
            name='status',
            field=models.CharField(choices=[('p', 'p'), ('d', 'd')], db_index=True, default='p', max_length=1),
        ),
    ]
