# Generated by Django 4.1.3 on 2024-10-06 12:55

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F, Case, When


def populate_journey(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    MissionJourney = apps.get_model('gamify', 'MissionJourney')

    whens = [
        When(promotion=j.name, then=j.id) for j in MissionJourney.objects.exclude(default=True)
    ]

    default = MissionJourney.objects.filter(default=True).first()

    User.objects.update(
        mission_journey_id=Case(
            *whens,
            default=default and default.id
        )
    )


def reverse_populate_journey(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    MissionJourney = apps.get_model('gamify', 'MissionJourney')

    # Repopulate promotion based on the mission_journey
    for journey in MissionJourney.objects.all():
        User.objects.filter(mission_journey_id=journey.id).update(promotion=journey.name)


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0024_remove_missionjourney_promotion_and_more'),
        ('accounts', '0231_spamphone_verificationcode_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='mission_journey',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='gamify.missionjourney'),
        ),
        migrations.AddField(
            model_name='user',
            name='mission_journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='gamify.missionjourney'),
        ),

        migrations.RunPython(code=populate_journey, reverse_code=reverse_populate_journey),

        migrations.RemoveField(
            model_name='historicaluser',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='promotion',
        ),
    ]
