# Generated by Django 4.1.3 on 2024-09-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0231_historicalsystemconfig_platform_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='promotion',
            field=models.CharField(blank=True, choices=[('true', 'true'), ('voucher', 'voucher'), ('pepe', 'pepe'), ('notcoin', 'notcoin'), ('dogs', 'dogs')], max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='promotion',
            field=models.CharField(blank=True, choices=[('true', 'true'), ('voucher', 'voucher'), ('pepe', 'pepe'), ('notcoin', 'notcoin'), ('dogs', 'dogs')], max_length=256),
        ),
    ]
