# Generated by Django 4.1.3 on 2024-10-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0231_fcmtopicsubscription'),
        ('accounts', '0232_remove_historicaluser_promotion_and_more'),
    ]

    operations = [
    ]
