# Generated by Django 4.1.3 on 2024-10-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0231_spamphone_verificationcode_ip_and_more'),
        ('accounts', '0232_alter_historicaluser_promotion_alter_user_promotion'),
    ]

    operations = [
    ]
