# Generated by Django 4.1.3 on 2024-10-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0233_merge_20241006_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='max_otc_irt',
            field=models.PositiveIntegerField(default=1000000000),
        ),
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='min_otc_irt',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='max_otc_irt',
            field=models.PositiveIntegerField(default=1000000000),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='min_otc_irt',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
