# Generated by Django 4.1.3 on 2024-10-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0232_remove_historicaluser_promotion_and_more'),
        ('accounts', '0233_merge_20241001_1557'),
    ]

    operations = [
    ]
