# Generated by Django 4.1.3 on 2024-10-28 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0234_historicalsystemconfig_max_otc_irt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmtopicsubscription',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fcmtopicsubscription',
            name='action',
            field=models.CharField(choices=[('subscribe', 'subscribe'), ('unsubscribe', 'unsubscribe')], max_length=50),
        ),
    ]
