# Generated by Django 4.1.3 on 2024-10-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0235_fcmtopicsubscription_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmtopicsubscription',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
