# Generated by Django 4.1.3 on 2024-10-29 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0236_fcmtopicsubscription_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebasetoken',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='firebasetoken',
            name='error',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='firebasetoken',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firebasetoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FCMTopicSubscription',
        ),
    ]
