# Generated by Django 4.1.3 on 2024-11-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0238_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficsource',
            name='signup_source',
            field=models.CharField(choices=[('main', 'main'), ('widget', 'widget')], default='main', max_length=8),
        ),
    ]
