# Generated by Django 4.1.3 on 2024-11-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0239_trafficsource_signup_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='missed_checks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
