# Generated by Django 4.1.3 on 2024-11-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0239_trafficsource_signup_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='telegram_bot_username',
            field=models.CharField(blank=True, max_length=256, default='test_bot'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='telegram_bot_username',
            field=models.CharField(blank=True, max_length=256, default='test_bot'),
        ),
    ]
