# Generated by Django 4.1.3 on 2024-11-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0240_verificationcode_missed_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='ban_sms_otp_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ban_sms_otp_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
