# Generated by Django 4.1.3 on 2024-11-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0240_historicalsystemconfig_telegram_bot_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='telegram_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_linked',
            field=models.BooleanField(default=False),
        ),
    ]
