# Generated by Django 4.1.3 on 2024-11-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0240_historicalsystemconfig_telegram_bot_username_and_more'),
        ('accounts', '0241_historicaluser_ban_sms_otp_until_and_more'),
    ]

    operations = [
    ]
