# Generated by Django 4.1.3 on 2024-11-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0241_historicaluser_telegram_linked_user_telegram_linked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='telegram_linked',
            new_name='telegram_bot_enabled',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='telegram_linked',
            new_name='telegram_bot_enabled',
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_telegram',
            field=models.BooleanField(default=True),
        ),
    ]
