# Generated by Django 4.1.3 on 2024-11-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0242_merge_20241110_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='send_notifs_to_telegram_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_telegram',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='send_notifs_to_telegram_bot',
            field=models.BooleanField(default=False),
        ),
    ]
