# Generated by Django 4.1.3 on 2024-11-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0242_rename_telegram_linked_historicaluser_telegram_bot_enabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='telegram_bot_enabled',
            new_name='send_notifs_to_telegram_bot',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='telegram_bot_enabled',
            new_name='send_notifs_to_telegram_bot',
        ),
    ]
