# Generated by Django 4.1.3 on 2024-11-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0244_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='disable_trade_with_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='disable_trade_with_api',
            field=models.BooleanField(default=False),
        ),
    ]
