# Generated by Django 4.1.3 on 2024-11-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0245_historicaluser_disable_trade_with_api_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsystemconfig',
            name='telegram_bot_username',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='telegram_bot_username',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
