# Generated by Django 4.1.3 on 2024-12-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0246_alter_historicalsystemconfig_telegram_bot_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sent_telegram',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
