# Generated by Django 4.1.3 on 2024-12-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0247_alter_notification_sent_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='otp_send_mode',
            field=models.CharField(choices=[('kavenegar', 'kavenegar'), ('kavenegar_exclusive', 'kavenegar_exclusive')], default='kavenegar', max_length=32),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='otp_send_mode',
            field=models.CharField(choices=[('kavenegar', 'kavenegar'), ('kavenegar_exclusive', 'kavenegar_exclusive')], default='kavenegar', max_length=32),
        ),
    ]
