# Generated by Django 4.1.3 on 2024-12-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0247_alter_notification_sent_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='pay_id_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='pay_id_enable',
            field=models.BooleanField(default=True),
        ),
    ]
