# Generated by Django 4.1.3 on 2024-12-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0248_historicalsystemconfig_otp_send_mode_and_more'),
        ('accounts', '0248_historicalsystemconfig_pay_id_enable_and_more'),
    ]

    operations = [
    ]
