# Generated by Django 4.1.3 on 2025-01-05 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0249_merge_20241230_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('model_name', models.CharField(max_length=255, verbose_name='Model')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Object ID')),
                ('url', models.CharField(max_length=1024, verbose_name='URL')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL, verbose_name='Admin User')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_by_admin', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
