# Generated by Django 4.1.3 on 2025-01-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0249_merge_20241230_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='pay_id_requests_process',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='pay_id_requests_process',
            field=models.BooleanField(default=False),
        ),
    ]
