# Generated by Django 4.1.3 on 2025-01-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0250_admintracker'),
        ('accounts', '0250_historicalsystemconfig_pay_id_requests_process_and_more'),
    ]

    operations = [
    ]
