# Generated by Django 4.1.3 on 2025-01-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0231_historicalsystemconfig_platform_type_and_more'),
        ('accounts', '0250_historicalsystemconfig_pay_id_requests_process_and_more'),
    ]

    operations = [
    ]
