# Generated by Django 4.1.3 on 2025-01-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0251_merge_20250107_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintracker',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='admintracker',
            name='model_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='admintracker',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Object ID'),
        ),
    ]
