# Generated by Django 4.1.3 on 2025-01-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0251_merge_20250106_1549'),
        ('accounts', '0251_merge_20250107_1000'),
    ]

    operations = [
    ]
