# Generated by Django 4.1.3 on 2025-01-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0252_merge_20250111_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='withdraw_amount_max',
            field=models.PositiveIntegerField(default=1000000000),
        ),
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='withdraw_amount_min',
            field=models.PositiveIntegerField(default=50000),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='withdraw_amount_max',
            field=models.PositiveIntegerField(default=1000000000),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='withdraw_amount_min',
            field=models.PositiveIntegerField(default=50000),
        ),
    ]
