# Generated by Django 4.1.3 on 2025-01-12 15:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0253_historicalsystemconfig_withdraw_amount_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='min_physical_gold_withdraw',
            field=models.DecimalField(decimal_places=8, default=Decimal('5'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='min_physical_silver_withdraw',
            field=models.DecimalField(decimal_places=8, default=Decimal('100'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='min_physical_gold_withdraw',
            field=models.DecimalField(decimal_places=8, default=Decimal('5'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='min_physical_silver_withdraw',
            field=models.DecimalField(decimal_places=8, default=Decimal('100'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
