# Generated by Django 4.1.3 on 2025-01-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0254_historicalsystemconfig_min_physical_gold_withdraw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='commission_type',
            field=models.CharField(choices=[('fee_deduct_receiving', 'fee_deduct_receiving'), ('fee_add_paying', 'fee_add_paying')], default='fee_deduct_receiving', help_text="Defines how trade commissions are applied. 'FEE_DEDUCT_RECEIVING' deducts the fee from the receiving amount (Raastin Behaviour), while 'FEE_ADD_PAYING' adds the fee to the paying amount (Milli Gold Behaviour).", max_length=32),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='commission_type',
            field=models.CharField(choices=[('fee_deduct_receiving', 'fee_deduct_receiving'), ('fee_add_paying', 'fee_add_paying')], default='fee_deduct_receiving', help_text="Defines how trade commissions are applied. 'FEE_DEDUCT_RECEIVING' deducts the fee from the receiving amount (Raastin Behaviour), while 'FEE_ADD_PAYING' adds the fee to the paying amount (Milli Gold Behaviour).", max_length=32),
        ),
    ]
