# Generated by Django 4.1.3 on 2025-01-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0252_alter_admintracker_created_and_more'),
        ('accounts', '0255_historicalsystemconfig_commission_type_and_more'),
    ]

    operations = [
    ]
