# Generated by Django 4.1.3 on 2025-01-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0256_merge_20250121_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsystemconfig',
            name='otp_send_mode',
            field=models.CharField(choices=[('kavenegar', 'kavenegar'), ('kavenegar_exclusive', 'kavenegar_exclusive'), ('melipayamak', 'melipayamak')], default='kavenegar', max_length=32),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='otp_send_mode',
            field=models.CharField(choices=[('kavenegar', 'kavenegar'), ('kavenegar_exclusive', 'kavenegar_exclusive'), ('melipayamak', 'melipayamak')], default='kavenegar', max_length=32),
        ),
    ]
