# Generated by Django 4.1.3 on 2025-01-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0257_alter_historicalsystemconfig_otp_send_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='kyc_service',
            field=models.CharField(choices=[('jibit', 'jibit'), ('zibal', 'zibal')], default='jibit', max_length=32),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='kyc_service',
            field=models.CharField(choices=[('jibit', 'jibit'), ('zibal', 'zibal')], default='jibit', max_length=32),
        ),
    ]
