# Generated by Django 4.1.3 on 2025-02-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0258_historicalsystemconfig_kyc_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeliPayamakTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('verify', 'Verify'), ('withdraw-accepted', 'Withdraw Accepted'), ('withdraw-rejected', 'Withdraw Rejected'), ('disable-staking', 'Disable Staking'), ('levelup-accepted', 'Level Up Accepted'), ('levelup-rejected', 'Level Up Rejected'), ('staking-activated', 'Staking Activated'), ('staking-finished', 'Staking Finished')], max_length=50, unique=True, verbose_name='Template Type')),
                ('code', models.TextField(verbose_name='Template Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MeliPayamak Template',
                'verbose_name_plural': 'MeliPayamak Templates',
                'ordering': ['template_type'],
            },
        ),
    ]
