# Generated by Django 4.1.3 on 2025-02-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0259_melipayamaktemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='melipayamaktemplate',
            options={'ordering': ['template_type'], 'verbose_name': 'الگو ملی پیامک', 'verbose_name_plural': 'الگو های ملی پیامک'},
        ),
    ]
