# Generated by Django 4.1.3 on 2025-10-11 12:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0261_alter_verificationcode_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='physical_withdraw_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Fee percentage for physical withdrawals (e.g., 3 for 3%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Physical Withdraw Fee Percentage'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='physical_withdraw_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Fee percentage for physical withdrawals (e.g., 3 for 3%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Physical Withdraw Fee Percentage'),
        ),
        migrations.AlterField(
            model_name='melipayamaktemplate',
            name='template_type',
            field=models.CharField(choices=[('verify-code', 'Verify'), ('withdraw-accepted', 'Withdraw Accepted'), ('withdraw-rejected', 'Withdraw Rejected'), ('disable-staking', 'Disable Staking'), ('levelup-accepted', 'Level Up Accepted'), ('levelup-rejected', 'Level Up Rejected'), ('staking-activated', 'Staking Activated'), ('staking-finished', 'Staking Finished')], max_length=50, unique=True, verbose_name='Template Type'),
        ),
    ]
