# Generated by Django 4.1.3 on 2025-10-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0262_historicalsystemconfig_physical_withdraw_fee_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystemconfig',
            name='pricing_currency',
            field=models.CharField(choices=[('dollar', 'dollar'), ('tether', 'tether')], default='tether', help_text='Select the currency used for pricing: dollar or tether (USDT)', max_length=16, verbose_name='Pricing Currency'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='pricing_currency',
            field=models.CharField(choices=[('dollar', 'dollar'), ('tether', 'tether')], default='tether', help_text='Select the currency used for pricing: dollar or tether (USDT)', max_length=16, verbose_name='Pricing Currency'),
        ),
    ]
