# Generated by Django 4.1.3 on 2025-11-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0263_historicalsystemconfig_pricing_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsystemconfig',
            name='pricing_currency',
            field=models.CharField(choices=[('paxg-tether', 'paxg-tether'), ('paxg-dollar', 'paxg-dollar'), ('tgju-gold18', 'tgju-gold18')], default='paxg-tether', help_text='Select the currency used for pricing: PAXG-Tether, PAXG-Dollar, or TGJU Gold 18', max_length=16, verbose_name='Pricing Currency'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='pricing_currency',
            field=models.CharField(choices=[('paxg-tether', 'paxg-tether'), ('paxg-dollar', 'paxg-dollar'), ('tgju-gold18', 'tgju-gold18')], default='paxg-tether', help_text='Select the currency used for pricing: PAXG-Tether, PAXG-Dollar, or TGJU Gold 18', max_length=16, verbose_name='Pricing Currency'),
        ),
    ]
