# Generated by Django 4.0 on 2022-10-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0004_upgrade_achievements'),
        ('ledger', '0139_alter_prize_unique_together_prize_achievement_and_more')
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='scope',
        ),
    ]
