# Generated by Django 4.0 on 2022-11-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0006_missionjourney_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='app_link',
            field=models.CharField(default='', max_length=32),
        ),
    ]
