# Generated by Django 4.0 on 2022-11-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0007_task_app_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='app_link',
            field=models.CharField(default='', max_length=256),
        ),
    ]
