# Generated by Django 4.1.3 on 2023-05-10 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0178_prize_voucher_expiration'),
        ('gamify', '0009_missionjourney_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.asset'),
        ),
    ]
