# Generated by Django 4.1.3 on 2023-05-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0010_mission_expiration_alter_achievement_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='scope',
            field=models.CharField(choices=[('verify_level2', 'verify_level2'), ('deposit', 'deposit'), ('trade', 'trade'), ('referral', 'referral'), ('set_email', 'set_email'), ('weekly_trade', 'weekly_trade')], max_length=16),
        ),
    ]
