# Generated by Django 4.1.3 on 2023-05-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0012_alter_mission_journey_usermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='expiration',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
