# Generated by Django 4.1.3 on 2023-05-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0013_alter_mission_expiration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mission',
            new_name='MissionTemplate',
        ),
    ]
