# Generated by Django 4.1.3 on 2023-05-13 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0014_rename_mission_missiontemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermission',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
