# Generated by Django 4.1.3 on 2023-06-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0016_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionjourney',
            name='promotion',
            field=models.CharField(choices=[('true', 'true'), ('voucher', 'voucher'), ('pepe', 'pepe')], max_length=8, unique=True),
        ),
    ]
