# Generated by Django 4.1.3 on 2024-03-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0018_usermission_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='scope',
            field=models.CharField(choices=[('verify_level2', 'verify_level2'), ('deposit', 'deposit'), ('trade', 'trade'), ('weekly_trade', 'weekly_trade'), ('referral', 'referral'), ('set_email', 'set_email')], max_length=16),
        ),
    ]
