# Generated by Django 4.1.3 on 2024-07-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0019_alter_task_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionjourney',
            name='promotion',
            field=models.CharField(choices=[('true', 'true'), ('voucher', 'voucher'), ('pepe', 'pepe'), ('not', 'not')], max_length=8, unique=True),
        ),
    ]
