# Generated by Django 4.1.3 on 2024-07-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0020_alter_missionjourney_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionjourney',
            name='promotion',
            field=models.CharField(choices=[('true', 'true'), ('voucher', 'voucher'), ('pepe', 'pepe'), ('notcoin', 'notcoin')], max_length=8, unique=True),
        ),
    ]
