# Generated by Django 4.1.3 on 2024-07-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0021_alter_missionjourney_promotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missiontemplate',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AlterField(
            model_name='task',
            name='scope',
            field=models.CharField(choices=[('verify_level2', 'verify_level2'), ('deposit', 'deposit'), ('deposit_from_now', 'deposit_from_now'), ('trade', 'trade'), ('weekly_trade', 'weekly_trade'), ('referral', 'referral'), ('set_email', 'set_email')], max_length=16),
        ),
    ]
