# Generated by Django 4.1.3 on 2024-08-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0022_alter_missiontemplate_options_alter_task_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionjourney',
            name='promotion',
            field=models.CharField(choices=[('true', 'true'), ('voucher', 'voucher'), ('pepe', 'pepe'), ('notcoin', 'notcoin'), ('dogs', 'dogs')], blank=True, max_length=8, unique=True),
        ),
    ]
