# Generated by Django 4.1.3 on 2024-10-06 12:55

from django.db import migrations, models
import django.db.models.deletion
import multimedia.storage


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0023_alter_missionjourney_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionjourney',
            name='promotion',
        ),
        migrations.AddField(
            model_name='missionjourney',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='missionjourney',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=multimedia.storage.PublicMediaStorage(), upload_to='missions/logo/'),
        ),
        migrations.AddField(
            model_name='missionjourney',
            name='title',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='missionjourney',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='MissionDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to='gamify.missionjourney')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
