# Generated by Django 4.1.3 on 2024-10-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0024_remove_missionjourney_promotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionjourney',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='missionjourney',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
