# Generated by Django 4.1.3 on 2024-12-23 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_type', models.CharField(choices=[('XAU', 'Gold'), ('XAG', 'Silver')], max_length=10, unique=True, verbose_name='Metal Type')),
                ('current_balance', models.DecimalField(decimal_places=3, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current Balance (grams)')),
                ('sold_amount', models.DecimalField(decimal_places=3, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sold Amount (grams)')),
                ('bank_reserved', models.DecimalField(decimal_places=3, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bank Reserved Amount (grams)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Treasuries',
            },
        ),
    ]
