# Generated by Django 4.1.3 on 2025-01-04 11:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0302_alter_otctrade_group_id'),
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalWithdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount (grams)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_id', models.UUIDField(unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.asset')),
            ],
            options={
                'verbose_name': 'دریافت فیزیکی',
                'verbose_name_plural': 'دریافت های فیزیکی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='physicalwithdraw',
            index=models.Index(fields=['status'], name='treasury_ph_status_2bb2a7_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalwithdraw',
            index=models.Index(fields=['account', 'status'], name='treasury_ph_account_9a29d5_idx'),
        ),
    ]
