# Generated by Django 4.1.3 on 2025-01-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0002_physicalwithdraw_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treasury',
            options={'verbose_name': 'خزانه', 'verbose_name_plural': 'خزانه'},
        ),
    ]
