# Generated by Django 4.1.3 on 2025-10-11 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_alter_treasury_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalwithdraw',
            name='fee_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fee Amount (grams)'),
        ),
    ]
