# Generated by Django 4.1.3 on 2023-10-08 12:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_alter_alerttype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AlertTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_ok_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='ok', max_length=8)),
                ('count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('alert_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='health.alerttype')),
            ],
        ),
    ]
