# Generated by Django 4.1.3 on 2024-06-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_alter_alerttype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttype',
            name='alert_on_same_status',
            field=models.BooleanField(default=False),
        ),
    ]
