# Generated by Django 4.1.3 on 2024-12-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_alerttype_alert_on_same_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttype',
            name='rate',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
