# Generated by Django 4.0 on 2022-09-26 07:53

from django.db import migrations, models
import django.db.models.deletion
import financial.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='نام')),
                ('iban', models.CharField(max_length=26, validators=[financial.validators.iban_validator], verbose_name='شماره شبا')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'حساب\u200cها',
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('amount', models.PositiveIntegerField(verbose_name='مقدار')),
                ('reason', models.CharField(max_length=128, verbose_name='علت')),
                ('type', models.CharField(choices=[('d', 'واریز'), ('w', 'برداشت')], max_length=1, verbose_name='نوع')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='حساب تنخواه')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='TransactionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('type', models.CharField(blank=True, choices=[('invoice', 'فاکتور'), ('receipt', 'رسید')], max_length=16, verbose_name='نوع')),
                ('file', models.FileField(upload_to='accounting/attachments/', verbose_name='ضمیمه')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.accounttransaction')),
            ],
            options={
                'verbose_name': 'ضمیمه',
                'verbose_name_plural': 'ضمیمه\u200cها',
            },
        ),
    ]
