# Generated by Django 4.1.3 on 2023-01-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_vault_historicalvaultitem_vaultitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvaultitem',
            old_name='amount',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='vaultitem',
            old_name='amount',
            new_name='balance',
        ),
    ]
