# Generated by Django 4.1.3 on 2023-01-28 14:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_rename_amount_historicalvaultitem_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='real_value',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='historicalvaultitem',
            name='balance',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
        migrations.AlterField(
            model_name='historicalvaultitem',
            name='value_irt',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
        migrations.AlterField(
            model_name='historicalvaultitem',
            name='value_usdt',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='balance',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='value_irt',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='value_usdt',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
    ]
