# Generated by Django 4.1.3 on 2023-02-27 13:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0043_alter_order_symbol_alter_pairsymbol_asset_and_more'),
        ('accounts', '0102_historicaluser_first_crypto_deposit_date_and_more'),
        ('accounting', '0008_alter_historicalvaultitem_value_irt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('side', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('source', models.CharField(choices=[('otc-m', 'otc-m'), ('otc-p', 'otc-p'), ('maker', 'maker'), ('taker', 'taker'), ('manual', 'manual')], max_length=8)),
                ('fee_revenue', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('value', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('coin_price', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('base_price', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('coin_spread', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('base_spread', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('coin_filled_price', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('filled_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('hedge_key', models.CharField(blank=True, db_index=True, max_length=16)),
                ('fiat_hedge_usdt', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('fiat_hedge_base', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.pairsymbol')),
            ],
        ),
    ]
