# Generated by Django 4.1.3 on 2023-02-28 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_traderevenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderevenue',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
