# Generated by Django 4.1.3 on 2023-02-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_traderevenue_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderevenue',
            name='source',
            field=models.CharField(choices=[('otc-m', 'otc-m'), ('otc-p', 'otc-p'), ('maker', 'maker'), ('taker', 'taker'), ('user', 'user'), ('manual', 'manual')], max_length=8),
        ),
    ]
