# Generated by Django 4.1.3 on 2023-02-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_alter_traderevenue_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderevenue',
            name='gap_revenue',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
    ]
