# Generated by Django 4.1.3 on 2023-03-01 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_traderevenue_base_irt_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderevenue',
            name='base_irt_price',
        ),
        migrations.AddField(
            model_name='traderevenue',
            name='base_usdt_price',
            field=models.DecimalField(decimal_places=20, default=1, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
