# Generated by Django 4.1.3 on 2023-03-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_remove_traderevenue_base_irt_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicFetcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('income_date', models.DateTimeField()),
                ('symbol', models.CharField(max_length=64)),
                ('income_type', models.CharField(max_length=64)),
                ('tran_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('income', models.DecimalField(decimal_places=8, max_digits=30)),
                ('coin', models.CharField(max_length=32)),
            ],
        ),
    ]
