# Generated by Django 4.1.3 on 2023-03-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_alter_blocklinkdustcost_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklinkdustcost',
            name='network',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='blocklinkincome',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalblocklinkdustcost',
            name='network',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='blocklinkincome',
            unique_together={('network', 'coin')},
        ),
    ]
