# Generated by Django 4.1.3 on 2023-03-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_alter_blocklinkdustcost_network_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blocklinkincome',
            unique_together={('network', 'start')},
        ),
    ]
