# Generated by Django 4.1.3 on 2023-05-10 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_alter_blocklinkincome_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderevenue',
            name='value_irt',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
