# Generated by Django 4.1.3 on 2023-06-28 05:41

from django.db import migrations
from django.db.models import F


def fill_gap_revenue(apps, schema_editor):
    TradeRevenue = apps.get_model("accounting", "TradeRevenue")
    TradeRevenue.objects.update(
        gap_revenue=F('gap_revenue') + F('fee_revenue') + F('fiat_hedge_usdt') + F('fiat_hedge_base') * F(
            'base_usdt_price')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_traderevenue_value_irt'),
    ]

    operations = [
        migrations.RunPython(fill_gap_revenue),
        migrations.RemoveField(
            model_name='traderevenue',
            name='fiat_hedge_base',
        ),
        migrations.RemoveField(
            model_name='traderevenue',
            name='fiat_hedge_usdt',
        ),
    ]
