# Generated by Django 4.1.3 on 2023-07-02 14:03

from django.db import migrations


def fix_sources(apps, schema_editor):
    TradeRevenue = apps.get_model("accounting", "TradeRevenue")
    TradeRevenue.objects.filter(source='sys-make').update(source='taker')
    TradeRevenue.objects.filter(source='sys-take').update(source='maker')


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_remove_traderevenue_fiat_hedge_base_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_sources),
    ]
