# Generated by Django 4.1.3 on 2023-07-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_traderevenue_value_is_fake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderevenue',
            name='base_spread',
        ),
        migrations.RemoveField(
            model_name='traderevenue',
            name='coin_spread',
        ),
    ]
