# Generated by Django 4.1.3 on 2023-07-12 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_remove_traderevenue_base_spread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='حساب'),
        ),
    ]
