# Generated by Django 4.1.3 on 2023-07-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_alter_accounttransaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvault',
            name='type',
            field=models.CharField(choices=[('provider', 'provider'), ('gateway', 'gateway'), ('hw', 'hw'), ('cw', 'cw'), ('bank', 'bank'), ('manual', 'manual')], max_length=8),
        ),
        migrations.AlterField(
            model_name='vault',
            name='type',
            field=models.CharField(choices=[('provider', 'provider'), ('gateway', 'gateway'), ('hw', 'hw'), ('cw', 'cw'), ('bank', 'bank'), ('manual', 'manual')], max_length=8),
        ),
    ]
