# Generated by Django 4.1.3 on 2023-07-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_alter_historicalvault_type_alter_vault_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
