# Generated by Django 4.1.3 on 2023-07-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_accounttransaction_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='create_vault',
            field=models.BooleanField(default=True),
        ),
    ]
