# Generated by Django 4.1.3 on 2023-07-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_account_create_vault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetprice',
            name='updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalassetprice',
            name='updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalreservedasset',
            name='updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalvaultitem',
            name='updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservedasset',
            name='updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
