# Generated by Django 4.1.3 on 2023-07-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_alter_assetprice_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvaultitem',
            name='updated',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='updated',
            field=models.DateTimeField(db_index=True),
        ),
    ]
