# Generated by Django 4.1.3 on 2023-07-26 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_alter_historicalvaultitem_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvault',
            name='updated',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vault',
            name='updated',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
