# Generated by Django 4.1.3 on 2023-10-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_historicalvault_updated_vault_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvault',
            name='expected_base_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vault',
            name='expected_base_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
