# Generated by Django 4.1.3 on 2023-11-22 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0168_alter_user_options'),
        ('accounting', '0034_historicalvault_expected_base_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderevenue',
            name='login_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.loginactivity'),
        ),
    ]
