# Generated by Django 4.1.3 on 2023-12-05 12:38

import django.core.validators
from django.db import migrations, models


def populate_expected_min_balance(apps, schema_editor):
    Vault = apps.get_model('accounting', 'Vault')
    VaultItem = apps.get_model('accounting', 'VaultItem')

    for v in Vault.objects.filter(expected_base_balance__gt=0):
        vi = VaultItem.objects.filter(vault=v, coin='USDT').first()
        if vi:
            vi.expected_min_balance = v.expected_base_balance
            vi.save(update_fields=['expected_min_balance'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_traderevenue_login_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvaultitem',
            name='expected_min_balance',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='expected_min_balance',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RunPython(
            code=populate_expected_min_balance,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='historicalvault',
            name='expected_base_balance',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='expected_base_balance',
        ),
    ]
