# Generated by Django 4.1.3 on 2023-12-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_remove_historicalvault_expected_base_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvault',
            name='expected_max_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='expected_max_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
