# Generated by Django 4.1.3 on 2024-01-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_historicalvault_expected_max_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicfetcher',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
