# Generated by Django 4.1.3 on 2024-01-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_alter_periodicfetcher_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blocklinkincome',
            unique_together={('coin', 'network', 'start')},
        ),
    ]
