# Generated by Django 4.1.3 on 2024-01-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0039_alter_blocklinkincome_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvaultitem',
            name='free',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='free',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
            preserve_default=False,
        ),
    ]
