# Generated by Django 4.1.3 on 2024-03-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_historicalvaultitem_free_vaultitem_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderevenue',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
