# Generated by Django 4.1.3 on 2024-04-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0041_alter_traderevenue_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvault',
            name='extra',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='extra',
            field=models.JSONField(null=True),
        ),
    ]
