# Generated by Django 4.1.3 on 2024-05-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_historicaltempcredit_tempcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvault',
            name='should_be_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='should_be_updated',
            field=models.BooleanField(default=True),
        ),
    ]
