# Generated by Django 4.1.3 on 2024-07-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0044_historicalvault_should_be_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvault',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vault',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
