# Generated by Django 4.1.3 on 2024-07-14 11:32

from django.db import migrations, models
import django.db.models.deletion


def populate_trade_revenue_positions(apps, sch):
    Trade = apps.get_model('market', 'Trade')
    TradeRevenue = apps.get_model('accounting', 'TradeRevenue')

    trade_dic = {t[0]: t[1] for t in Trade.objects.filter(position__isnull=False, group_id__isnull=False).values_list('group_id', 'position_id')}

    revenue_queryset = TradeRevenue.objects.filter(group_id__in=list(trade_dic.keys()))

    updated_revenues = []
    for rt in revenue_queryset:
        rt.position = trade_dic[rt.group_id]
        updated_revenues.append(rt)

    TradeRevenue.objects.bulk_update(updated_revenues, ['position'])


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0270_remove_depositrecoveryrequest_image_and_more'),
        ('accounting', '0045_alter_historicalvault_extra_alter_vault_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderevenue',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.marginposition'),
        ),
        migrations.RunPython(populate_trade_revenue_positions, migrations.RunPython.noop),
    ]
