# Generated by Django 4.1.3 on 2024-07-14 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0270_remove_depositrecoveryrequest_image_and_more'),
        ('accounting', '0045_alter_historicalvault_extra_alter_vault_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderevenue',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.marginposition'),
        ),
    ]
