# Generated by Django 4.1.3 on 2024-07-14 12:56

from django.db import migrations


def populate_trade_revenue_positions(apps, sch):
    Trade = apps.get_model('market', 'Trade')
    TradeRevenue = apps.get_model('accounting', 'TradeRevenue')

    for trade in Trade.objects.filter(position__isnull=False, group_id__isnull=False):
        TradeRevenue.objects.filter(group_id=trade.group_id).update(position=trade.position)


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0046_traderevenue_position'),
    ]

    operations = [
        migrations.RunPython(populate_trade_revenue_positions, migrations.RunPython.noop),
    ]
