# Generated by Django 4.1.3 on 2024-08-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0046_traderevenue_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvault',
            name='type',
            field=models.CharField(choices=[('provider', 'provider'), ('gateway', 'gateway'), ('hw', 'hw'), ('cw', 'cw'), ('bank', 'bank'), ('app', 'app'), ('manual', 'manual')], max_length=8),
        ),
        migrations.AlterField(
            model_name='vault',
            name='type',
            field=models.CharField(choices=[('provider', 'provider'), ('gateway', 'gateway'), ('hw', 'hw'), ('cw', 'cw'), ('bank', 'bank'), ('app', 'app'), ('manual', 'manual')], max_length=8),
        ),
    ]
