# Generated by Django 4.1.3 on 2024-12-31 15:09

from django.db import migrations, models
import financial.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0047_alter_historicalvault_type_alter_vault_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='iban',
            field=models.CharField(max_length=26, validators=[financial.validators.iban_validator], verbose_name='شبا'),
        ),
    ]
